services:
  postgres:
    image: postgres:17
    container_name: heya-postgres
    environment:
      POSTGRES_USER: heya
      POSTGRES_PASSWORD: heya
      POSTGRES_DB: heya
    ports:
      - "5440:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
