<script setup lang="ts">
import { computed, type Component } from 'vue'
import {
  PhAirplay,
  PhArrowClockwise,
  PhArrowCounterClockwise,
  PhArrowLeft,
  PhArrowRight,
  PhArrowsIn,
  PhArrowsOut,
  PhBell,
  PhBookOpen,
  PhBookOpenText,
  PhBookmarkSimple,
  PhCaretDown,
  PhCaretLeft,
  PhCaretRight,
  PhCaretUp,
  PhChartBar,
  PhChatText,
  PhCheck,
  PhCircleNotch,
  PhClipboardText,
  PhClock,
  PhClosedCaptioning,
  PhCloudArrowDown,
  PhCloudSlash,
  PhCompass,
  PhCopyright,
  PhCpu,
  PhCrown,
  PhDatabase,
  PhDotsThree,
  PhDownloadSimple,
  PhEnvelope,
  PhEye,
  PhEyeSlash,
  PhFilmSlate,
  PhFingerprint,
  PhFolder,
  PhFunnel,
  PhGearSix,
  PhGithubLogo,
  PhGlobe,
  PhHardDrives,
  PhHash,
  PhHeart,
  PhHouse,
  PhImage,
  PhInfo,
  PhKey,
  PhLightning,
  PhLinkSimple,
  PhList,
  PhMagicWand,
  PhMagnifyingGlass,
  PhMicrophone,
  PhMusicNotes,
  PhPause,
  PhPencilSimple,
  PhPlay,
  PhPlus,
  PhPulse,
  PhQueue,
  PhRadio,
  PhRepeat,
  PhRows,
  PhScissors,
  PhShieldCheck,
  PhShuffle,
  PhSignOut,
  PhSkipBack,
  PhSkipForward,
  PhSliders,
  PhSortAscending,
  PhSparkle,
  PhSpeakerHigh,
  PhSpeakerLow,
  PhSpeakerNone,
  PhSpeakerX,
  PhSpinner,
  PhSquaresFour,
  PhStar,
  PhStarHalf,
  PhStop,
  PhSubtitles,
  PhSun,
  PhTarget,
  PhTelevisionSimple,
  PhTextAa,
  PhTimer,
  PhToggleLeft,
  PhToggleRight,
  PhTranslate,
  PhTrash,
  PhTreeStructure,
  PhUser,
  PhUserPlus,
  PhUsers,
  PhWarning,
  PhWrench,
  PhX,
} from '@phosphor-icons/vue'

const props = defineProps<{
  name: string
  size?: number
  weight?: 'thin' | 'light' | 'regular' | 'bold' | 'fill' | 'duotone'
}>()

// Internal alias → phosphor kebab name. Only this explicit set is imported;
// registering the library through nuxt-phosphor-icons generated one async
// chunk for every one of its 1,500+ icons and made Workbox precache them all.
const nameMap: Record<string, string> = {
  home: 'house',
  film: 'film-slate',
  tv: 'television-simple',
  music: 'music-notes',
  book: 'book-open',
  search: 'magnifying-glass',
  settings: 'gear-six',
  play: 'play',
  pause: 'pause',
  stop: 'stop',
  prev: 'skip-back',
  next: 'skip-forward',
  skipback: 'skip-back',
  skipforward: 'skip-forward',
  shuffle: 'shuffle',
  repeat: 'repeat',
  vol: 'speaker-high',
  volmute: 'speaker-x',
  queue: 'queue',
  heart: 'heart',
  heartfill: 'heart',
  plus: 'plus',
  more: 'dots-three',
  star: 'star',
  check: 'check',
  chevup: 'caret-up',
  chevdown: 'caret-down',
  chevright: 'caret-right',
  chevleft: 'caret-left',
  close: 'x',
  cast: 'airplay',
  download: 'download-simple',
  globe: 'globe',
  image: 'image',
  mic: 'microphone',
  radio: 'radio',
  list: 'list',
  // Compact-band topbar burger (AppTopBar.vue) — reuses phosphor's 3-line
  // "list" glyph as the menu/hamburger icon; there's no separate hamburger
  // glyph in the phosphor set.
  menu: 'list',
  grid: 'squares-four',
  rows: 'rows',
  filter: 'funnel',
  sort: 'sort-ascending',
  undo: 'arrow-counter-clockwise',
  back: 'arrow-left',
  user: 'user',
  bell: 'bell',
  folder: 'folder',
  network: 'tree-structure',
  bookmark: 'bookmark-simple',
  reader: 'book-open-text',
  type: 'text-aa',
  brightness: 'sun',
  eq: 'sliders',
  lyrics: 'chat-text',
  expand: 'arrows-out',
  collapse: 'arrows-in',
  'chart-bar': 'chart-bar',
  chart: 'chart-bar',
  sparkle: 'sparkle',
  compass: 'compass',
  link: 'link-simple',
  'star-half': 'star-half',
  database: 'database',
  shield: 'shield-check',
  cpu: 'cpu',
  users: 'users',
  info: 'info',
  target: 'target',
  trash: 'trash',
  pencil: 'pencil-simple',
  warning: 'warning',
  clock: 'clock',
  envelope: 'envelope',
  'user-plus': 'user-plus',
  crown: 'crown',
  key: 'key',
  'arrow-right': 'arrow-right',
  eye: 'eye',
  'eye-slash': 'eye-slash',
  'sign-out': 'sign-out',
  wrench: 'wrench',
  'hard-drives': 'hard-drives',
  pulse: 'pulse',
  fingerprint: 'fingerprint',
  scissors: 'scissors',
  wand: 'magic-wand',
  spinner: 'spinner',
  'cloud-download': 'cloud-arrow-down',
  cloud: 'cloud-slash',
  github: 'github-logo',
  refresh: 'arrow-clockwise',
  lightning: 'lightning',
  loading: 'circle-notch',
  'toggle-on': 'toggle-right',
  'toggle-off': 'toggle-left',
  clipboard: 'clipboard-text',
  timer: 'timer',
  hash: 'hash',
  copyright: 'copyright',
  speakerhigh: 'speaker-high',
  speakerlow: 'speaker-low',
  speakernone: 'speaker-none',
  speakerx: 'speaker-x',
  subtitles: 'subtitles',
  captions: 'closed-captioning',
  translate: 'translate',
  shrink: 'arrows-in',
}

const iconComponents: Record<string, Component> = {
  house: PhHouse,
  'film-slate': PhFilmSlate,
  'television-simple': PhTelevisionSimple,
  'music-notes': PhMusicNotes,
  'book-open': PhBookOpen,
  'magnifying-glass': PhMagnifyingGlass,
  'gear-six': PhGearSix,
  play: PhPlay,
  pause: PhPause,
  stop: PhStop,
  'skip-back': PhSkipBack,
  'skip-forward': PhSkipForward,
  shuffle: PhShuffle,
  repeat: PhRepeat,
  'speaker-high': PhSpeakerHigh,
  'speaker-x': PhSpeakerX,
  queue: PhQueue,
  heart: PhHeart,
  plus: PhPlus,
  'dots-three': PhDotsThree,
  star: PhStar,
  check: PhCheck,
  'caret-up': PhCaretUp,
  'caret-down': PhCaretDown,
  'caret-right': PhCaretRight,
  'caret-left': PhCaretLeft,
  x: PhX,
  airplay: PhAirplay,
  'download-simple': PhDownloadSimple,
  globe: PhGlobe,
  image: PhImage,
  microphone: PhMicrophone,
  radio: PhRadio,
  list: PhList,
  'squares-four': PhSquaresFour,
  rows: PhRows,
  funnel: PhFunnel,
  'sort-ascending': PhSortAscending,
  'arrow-counter-clockwise': PhArrowCounterClockwise,
  'arrow-left': PhArrowLeft,
  user: PhUser,
  bell: PhBell,
  folder: PhFolder,
  'tree-structure': PhTreeStructure,
  'bookmark-simple': PhBookmarkSimple,
  'book-open-text': PhBookOpenText,
  'text-aa': PhTextAa,
  sun: PhSun,
  sliders: PhSliders,
  'chat-text': PhChatText,
  'arrows-out': PhArrowsOut,
  'arrows-in': PhArrowsIn,
  'chart-bar': PhChartBar,
  sparkle: PhSparkle,
  compass: PhCompass,
  'link-simple': PhLinkSimple,
  'star-half': PhStarHalf,
  database: PhDatabase,
  'shield-check': PhShieldCheck,
  cpu: PhCpu,
  users: PhUsers,
  info: PhInfo,
  target: PhTarget,
  trash: PhTrash,
  'pencil-simple': PhPencilSimple,
  warning: PhWarning,
  clock: PhClock,
  envelope: PhEnvelope,
  'user-plus': PhUserPlus,
  crown: PhCrown,
  key: PhKey,
  'arrow-right': PhArrowRight,
  eye: PhEye,
  'eye-slash': PhEyeSlash,
  'sign-out': PhSignOut,
  wrench: PhWrench,
  'hard-drives': PhHardDrives,
  pulse: PhPulse,
  fingerprint: PhFingerprint,
  scissors: PhScissors,
  'magic-wand': PhMagicWand,
  spinner: PhSpinner,
  'cloud-arrow-down': PhCloudArrowDown,
  'cloud-slash': PhCloudSlash,
  'github-logo': PhGithubLogo,
  'arrow-clockwise': PhArrowClockwise,
  lightning: PhLightning,
  'circle-notch': PhCircleNotch,
  'toggle-right': PhToggleRight,
  'toggle-left': PhToggleLeft,
  'clipboard-text': PhClipboardText,
  timer: PhTimer,
  hash: PhHash,
  copyright: PhCopyright,
  'speaker-low': PhSpeakerLow,
  'speaker-none': PhSpeakerNone,
  subtitles: PhSubtitles,
  'closed-captioning': PhClosedCaptioning,
  translate: PhTranslate,
}

const phosphorIcon = computed(() => {
  const name = nameMap[props.name]
  return name ? iconComponents[name] ?? null : null
})

const iconWeight = computed(() => {
  if (props.weight) return props.weight
  if (props.name === 'heartfill') return 'fill'
  return 'regular'
})
</script>

<template>
  <component
    :is="phosphorIcon"
    v-if="phosphorIcon"
    :size="size || 18"
    :weight="iconWeight"
  />
</template>
