package jellyfin

// The coverage manifest: every operation in the vendored Jellyfin 10.11.11
// OpenAPI spec (spec/jellyfin-openapi-10.11.11.json.gz), triaged. This is
// how "reimplement the entire Jellyfin API" stays honest — manifest_test.go
// fails the build when a spec operation is missing here, when an entry
// claims implemented/stubbed without a matching registered route, or when a
// registered route doesn't exist in the spec (pattern typo).
//
// Statuses:
//
//	opImplemented — registered, real behavior backed by Heya services.
//	opStubbed     — registered, returns the same "feature absent/disabled"
//	                shape a stock Jellyfin with that feature off returns.
//	opPlanned     — not yet registered; the phase 1–3 work queue.
//	opOutOfScope  — no Heya equivalent (LiveTV tuners, plugin market,
//	                server config dashboard...). Phase 4 gives the probed
//	                ones graceful stubs; the rest 404 like disabled
//	                features do upstream.
type opStatus int

const (
	opPlanned opStatus = iota
	opImplemented
	opStubbed
	opOutOfScope
)

type manifestEntry struct {
	Status opStatus
	Tag    string
}

// extraRoutes are registered routes that intentionally have no spec entry:
// the WebSocket endpoint predates the OpenAPI document upstream.
var extraRoutes = map[string]bool{
	"GET /socket":        true,
	"GET /embywebsocket": true,
	// Legacy pre-10.9 user-scoped aliases still emitted by older client code
	// paths; gone from the 10.11 spec but still answered by upstream.
	"GET /Users/{userId}/Views":                          true,
	"GET /Users/{userId}/Items":                          true,
	"GET /Users/{userId}/Items/{itemId}":                 true,
	"GET /Users/{userId}/Items/Resume":                   true,
	"GET /Users/{userId}/Items/Latest":                   true,
	"POST /Users/{userId}/FavoriteItems/{itemId}":        true,
	"DELETE /Users/{userId}/FavoriteItems/{itemId}":      true,
	"POST /Users/{userId}/PlayedItems/{itemId}":          true,
	"DELETE /Users/{userId}/PlayedItems/{itemId}":        true,
	"GET /Users/{userId}/Items/Root":                     true,
	"GET /Users/{userId}/Items/{itemId}/Intros":          true,
	"GET /Users/{userId}/Items/{itemId}/LocalTrailers":   true,
	"GET /Users/{userId}/Items/{itemId}/SpecialFeatures": true,
	"GET /Users/{userId}/Items/{itemId}/Lyrics":          true,
	// Served like a real server, but not REST-spec operations.
	"GET /api-docs/openapi.json": true,
	"GET /robots.txt":            true,
	"GET /web/robots.txt":        true,
}

var manifest = map[string]manifestEntry{
	"DELETE /Audio/{itemId}/Lyrics":                                 {Status: opPlanned, Tag: "Lyrics"},
	"DELETE /Auth/Keys/{key}":                                       {Status: opOutOfScope, Tag: "ApiKey"},
	"DELETE /Branding/Splashscreen":                                 {Status: opPlanned, Tag: "Image"},
	"DELETE /Collections/{collectionId}/Items":                      {Status: opOutOfScope, Tag: "Collection"},
	"DELETE /Devices":                                               {Status: opPlanned, Tag: "Devices"},
	"DELETE /Items":                                                 {Status: opImplemented, Tag: "Library"}, // 404 unknown, 403 known: no deletes via this surface
	"DELETE /Items/{itemId}":                                        {Status: opImplemented, Tag: "Library"}, // 404 unknown, 403 known: no deletes via this surface
	"DELETE /Items/{itemId}/Images/{imageType}":                     {Status: opPlanned, Tag: "Image"},
	"DELETE /Items/{itemId}/Images/{imageType}/{imageIndex}":        {Status: opPlanned, Tag: "Image"},
	"DELETE /Library/VirtualFolders":                                {Status: opStubbed, Tag: "LibraryStructure"}, // validated, then 403: Heya-managed
	"DELETE /Library/VirtualFolders/Paths":                          {Status: opStubbed, Tag: "LibraryStructure"}, // validated, then 403: Heya-managed
	"DELETE /LiveTv/ListingProviders":                               {Status: opOutOfScope, Tag: "LiveTv"},
	"DELETE /LiveTv/Recordings/{recordingId}":                       {Status: opOutOfScope, Tag: "LiveTv"},
	"DELETE /LiveTv/SeriesTimers/{timerId}":                         {Status: opOutOfScope, Tag: "LiveTv"},
	"DELETE /LiveTv/Timers/{timerId}":                               {Status: opOutOfScope, Tag: "LiveTv"},
	"DELETE /LiveTv/TunerHosts":                                     {Status: opOutOfScope, Tag: "LiveTv"},
	"DELETE /Packages/Installing/{packageId}":                       {Status: opOutOfScope, Tag: "Package"},
	"DELETE /PlayingItems/{itemId}":                                 {Status: opPlanned, Tag: "Playstate"},
	"DELETE /Playlists/{playlistId}/Items":                          {Status: opImplemented, Tag: "Playlists"},
	"DELETE /Playlists/{playlistId}/Users/{userId}":                 {Status: opPlanned, Tag: "Playlists"},
	"DELETE /Plugins/{pluginId}":                                    {Status: opOutOfScope, Tag: "Plugins"},
	"DELETE /Plugins/{pluginId}/{version}":                          {Status: opOutOfScope, Tag: "Plugins"},
	"DELETE /ScheduledTasks/Running/{taskId}":                       {Status: opOutOfScope, Tag: "ScheduledTasks"},
	"DELETE /Sessions/{sessionId}/User/{userId}":                    {Status: opPlanned, Tag: "Session"},
	"DELETE /UserFavoriteItems/{itemId}":                            {Status: opImplemented, Tag: "UserLibrary"},
	"DELETE /UserImage":                                             {Status: opPlanned, Tag: "Image"},
	"DELETE /UserItems/{itemId}/Rating":                             {Status: opPlanned, Tag: "UserLibrary"},
	"DELETE /UserPlayedItems/{itemId}":                              {Status: opImplemented, Tag: "Playstate"},
	"DELETE /Users/{userId}":                                        {Status: opPlanned, Tag: "User"},
	"DELETE /Videos/{itemId}/AlternateSources":                      {Status: opPlanned, Tag: "Videos"},
	"DELETE /Videos/{itemId}/Subtitles/{index}":                     {Status: opPlanned, Tag: "Subtitle"},
	"DELETE /Videos/ActiveEncodings":                                {Status: opPlanned, Tag: "HlsSegment"},
	"GET /Albums/{itemId}/InstantMix":                               {Status: opImplemented, Tag: "InstantMix"},
	"GET /Albums/{itemId}/Similar":                                  {Status: opImplemented, Tag: "Library"},
	"GET /Artists":                                                  {Status: opImplemented, Tag: "Artists"},
	"GET /Artists/{itemId}/InstantMix":                              {Status: opImplemented, Tag: "InstantMix"},
	"GET /Artists/{itemId}/Similar":                                 {Status: opImplemented, Tag: "Library"},
	"GET /Artists/{name}":                                           {Status: opPlanned, Tag: "Artists"},
	"GET /Artists/{name}/Images/{imageType}/{imageIndex}":           {Status: opPlanned, Tag: "Image"},
	"GET /Artists/AlbumArtists":                                     {Status: opImplemented, Tag: "Artists"},
	"GET /Artists/InstantMix":                                       {Status: opPlanned, Tag: "InstantMix"},
	"GET /Audio/{itemId}/hls/{segmentId}/stream.aac":                {Status: opPlanned, Tag: "HlsSegment"},
	"GET /Audio/{itemId}/hls/{segmentId}/stream.mp3":                {Status: opPlanned, Tag: "HlsSegment"},
	"GET /Audio/{itemId}/hls1/{playlistId}/{segmentId}.{container}": {Status: opPlanned, Tag: "DynamicHls"},
	"GET /Audio/{itemId}/Lyrics":                                    {Status: opImplemented, Tag: "Lyrics"},
	"GET /Audio/{itemId}/main.m3u8":                                 {Status: opPlanned, Tag: "DynamicHls"},
	"GET /Audio/{itemId}/master.m3u8":                               {Status: opPlanned, Tag: "DynamicHls"},
	"GET /Audio/{itemId}/RemoteSearch/Lyrics":                       {Status: opPlanned, Tag: "Lyrics"},
	"GET /Audio/{itemId}/stream.{container}":                        {Status: opImplemented, Tag: "Audio"},
	"GET /Audio/{itemId}/stream":                                    {Status: opImplemented, Tag: "Audio"},
	"GET /Audio/{itemId}/universal":                                 {Status: opImplemented, Tag: "UniversalAudio"},
	"GET /Auth/Keys":                                                {Status: opOutOfScope, Tag: "ApiKey"},
	"GET /Auth/PasswordResetProviders":                              {Status: opStubbed, Tag: "Session"},
	"GET /Auth/Providers":                                           {Status: opStubbed, Tag: "Session"},
	"GET /Backup":                                                   {Status: opOutOfScope, Tag: "Backup"},
	"GET /Backup/Manifest":                                          {Status: opOutOfScope, Tag: "Backup"},
	"GET /Branding/Configuration":                                   {Status: opImplemented, Tag: "Branding"},
	"GET /Branding/Css.css":                                         {Status: opImplemented, Tag: "Branding"},
	"GET /Branding/Css":                                             {Status: opImplemented, Tag: "Branding"},
	"GET /Branding/Splashscreen":                                    {Status: opPlanned, Tag: "Image"},
	"GET /Channels":                                                 {Status: opStubbed, Tag: "Channels"},
	"GET /Channels/{channelId}/Features":                            {Status: opOutOfScope, Tag: "Channels"},
	"GET /Channels/{channelId}/Items":                               {Status: opOutOfScope, Tag: "Channels"},
	"GET /Channels/Features":                                        {Status: opOutOfScope, Tag: "Channels"},
	"GET /Channels/Items/Latest":                                    {Status: opOutOfScope, Tag: "Channels"},
	"GET /Devices":                                                  {Status: opStubbed, Tag: "Devices"},
	"GET /Devices/Info":                                             {Status: opPlanned, Tag: "Devices"},
	"GET /Devices/Options":                                          {Status: opPlanned, Tag: "Devices"},
	"GET /DisplayPreferences/{displayPreferencesId}":                {Status: opImplemented, Tag: "DisplayPreferences"},
	"GET /Environment/DefaultDirectoryBrowser":                      {Status: opOutOfScope, Tag: "Environment"},
	"GET /Environment/DirectoryContents":                            {Status: opOutOfScope, Tag: "Environment"},
	"GET /Environment/Drives":                                       {Status: opOutOfScope, Tag: "Environment"},
	"GET /Environment/NetworkShares":                                {Status: opOutOfScope, Tag: "Environment"},
	"GET /Environment/ParentPath":                                   {Status: opOutOfScope, Tag: "Environment"},
	"GET /FallbackFont/Fonts":                                       {Status: opPlanned, Tag: "Subtitle"},
	"GET /FallbackFont/Fonts/{name}":                                {Status: opPlanned, Tag: "Subtitle"},
	"GET /Genres":                                                   {Status: opImplemented, Tag: "Genres"},
	"GET /Genres/{genreName}":                                       {Status: opImplemented, Tag: "Genres"},
	"GET /Genres/{name}/Images/{imageType}":                         {Status: opPlanned, Tag: "Image"},
	"GET /Genres/{name}/Images/{imageType}/{imageIndex}":            {Status: opPlanned, Tag: "Image"},
	"GET /GetUtcTime":                                               {Status: opImplemented, Tag: "TimeSync"},
	"GET /Items":                                                    {Status: opImplemented, Tag: "Items"},
	"GET /Items/{itemId}":                                           {Status: opImplemented, Tag: "UserLibrary"},
	"GET /Items/{itemId}/Ancestors":                                 {Status: opStubbed, Tag: "Library"},
	"GET /Items/{itemId}/CriticReviews":                             {Status: opStubbed, Tag: "Library"},
	"GET /Items/{itemId}/Download":                                  {Status: opImplemented, Tag: "Library"},
	"GET /Items/{itemId}/ExternalIdInfos":                           {Status: opOutOfScope, Tag: "ItemLookup"},
	"GET /Items/{itemId}/File":                                      {Status: opImplemented, Tag: "Library"},
	"GET /Items/{itemId}/Images":                                    {Status: opPlanned, Tag: "Image"},
	"GET /Items/{itemId}/Images/{imageType}":                        {Status: opImplemented, Tag: "Image"},
	"GET /Items/{itemId}/Images/{imageType}/{imageIndex}":           {Status: opImplemented, Tag: "Image"},
	"GET /Items/{itemId}/Images/{imageType}/{imageIndex}/{tag}/{format}/{maxWidth}/{maxHeight}/{percentPlayed}/{unplayedCount}": {Status: opPlanned, Tag: "Image"},
	"GET /Items/{itemId}/InstantMix":                            {Status: opImplemented, Tag: "InstantMix"},
	"GET /Items/{itemId}/Intros":                                {Status: opImplemented, Tag: "UserLibrary"}, // empty: no cinema intros feature
	"GET /Items/{itemId}/LocalTrailers":                         {Status: opImplemented, Tag: "UserLibrary"}, // empty array after real validation
	"GET /Items/{itemId}/MetadataEditor":                        {Status: opOutOfScope, Tag: "ItemUpdate"},
	"GET /Items/{itemId}/PlaybackInfo":                          {Status: opImplemented, Tag: "MediaInfo"},
	"GET /Items/{itemId}/RemoteImages":                          {Status: opOutOfScope, Tag: "RemoteImage"},
	"GET /Items/{itemId}/RemoteImages/Providers":                {Status: opOutOfScope, Tag: "RemoteImage"},
	"GET /Items/{itemId}/RemoteSearch/Subtitles/{language}":     {Status: opPlanned, Tag: "Subtitle"},
	"GET /Items/{itemId}/Similar":                               {Status: opImplemented, Tag: "Library"},
	"GET /Items/{itemId}/SpecialFeatures":                       {Status: opImplemented, Tag: "UserLibrary"}, // empty array after real validation
	"GET /Items/{itemId}/ThemeMedia":                            {Status: opStubbed, Tag: "Library"},
	"GET /Items/{itemId}/ThemeSongs":                            {Status: opStubbed, Tag: "Library"},
	"GET /Items/{itemId}/ThemeVideos":                           {Status: opStubbed, Tag: "Library"},
	"GET /Items/Counts":                                         {Status: opImplemented, Tag: "Library"},
	"GET /Items/Filters":                                        {Status: opImplemented, Tag: "Filter"},
	"GET /Items/Filters2":                                       {Status: opImplemented, Tag: "Filter"},
	"GET /Items/Latest":                                         {Status: opImplemented, Tag: "UserLibrary"},
	"GET /Items/Root":                                           {Status: opImplemented, Tag: "UserLibrary"},
	"GET /Items/Suggestions":                                    {Status: opImplemented, Tag: "Suggestions"},
	"GET /Libraries/AvailableOptions":                           {Status: opPlanned, Tag: "Library"},
	"GET /Library/MediaFolders":                                 {Status: opPlanned, Tag: "Library"},
	"GET /Library/PhysicalPaths":                                {Status: opPlanned, Tag: "Library"},
	"GET /Library/VirtualFolders":                               {Status: opImplemented, Tag: "LibraryStructure"},
	"GET /LiveTv/ChannelMappingOptions":                         {Status: opOutOfScope, Tag: "LiveTv"},
	"GET /LiveTv/Channels":                                      {Status: opOutOfScope, Tag: "LiveTv"},
	"GET /LiveTv/Channels/{channelId}":                          {Status: opOutOfScope, Tag: "LiveTv"},
	"GET /LiveTv/GuideInfo":                                     {Status: opOutOfScope, Tag: "LiveTv"},
	"GET /LiveTv/Info":                                          {Status: opStubbed, Tag: "LiveTv"},
	"GET /LiveTv/ListingProviders/Default":                      {Status: opOutOfScope, Tag: "LiveTv"},
	"GET /LiveTv/ListingProviders/Lineups":                      {Status: opOutOfScope, Tag: "LiveTv"},
	"GET /LiveTv/ListingProviders/SchedulesDirect/Countries":    {Status: opOutOfScope, Tag: "LiveTv"},
	"GET /LiveTv/LiveRecordings/{recordingId}/stream":           {Status: opOutOfScope, Tag: "LiveTv"},
	"GET /LiveTv/LiveStreamFiles/{streamId}/stream.{container}": {Status: opOutOfScope, Tag: "LiveTv"},
	"GET /LiveTv/Programs":                                      {Status: opOutOfScope, Tag: "LiveTv"},
	"GET /LiveTv/Programs/{programId}":                          {Status: opOutOfScope, Tag: "LiveTv"},
	"GET /LiveTv/Programs/Recommended":                          {Status: opOutOfScope, Tag: "LiveTv"},
	"GET /LiveTv/Recordings":                                    {Status: opOutOfScope, Tag: "LiveTv"},
	"GET /LiveTv/Recordings/{recordingId}":                      {Status: opOutOfScope, Tag: "LiveTv"},
	"GET /LiveTv/Recordings/Folders":                            {Status: opOutOfScope, Tag: "LiveTv"},
	"GET /LiveTv/Recordings/Groups":                             {Status: opOutOfScope, Tag: "LiveTv"},
	"GET /LiveTv/Recordings/Groups/{groupId}":                   {Status: opOutOfScope, Tag: "LiveTv"},
	"GET /LiveTv/Recordings/Series":                             {Status: opOutOfScope, Tag: "LiveTv"},
	"GET /LiveTv/SeriesTimers":                                  {Status: opOutOfScope, Tag: "LiveTv"},
	"GET /LiveTv/SeriesTimers/{timerId}":                        {Status: opOutOfScope, Tag: "LiveTv"},
	"GET /LiveTv/Timers":                                        {Status: opOutOfScope, Tag: "LiveTv"},
	"GET /LiveTv/Timers/{timerId}":                              {Status: opOutOfScope, Tag: "LiveTv"},
	"GET /LiveTv/Timers/Defaults":                               {Status: opOutOfScope, Tag: "LiveTv"},
	"GET /LiveTv/TunerHosts/Types":                              {Status: opOutOfScope, Tag: "LiveTv"},
	"GET /LiveTv/Tuners/Discover":                               {Status: opOutOfScope, Tag: "LiveTv"},
	"GET /LiveTv/Tuners/Discvover":                              {Status: opOutOfScope, Tag: "LiveTv"},
	"GET /Localization/Countries":                               {Status: opPlanned, Tag: "Localization"},
	"GET /Localization/Cultures":                                {Status: opPlanned, Tag: "Localization"},
	"GET /Localization/Options":                                 {Status: opPlanned, Tag: "Localization"},
	"GET /Localization/ParentalRatings":                         {Status: opPlanned, Tag: "Localization"},
	"GET /MediaSegments/{itemId}":                               {Status: opImplemented, Tag: "MediaSegments"}, // media_segments rows for the item's file, ms → ticks; gated by MediaSourceInfo.HasSegments (mediaSourceForFile)
	"GET /Movies/{itemId}/Similar":                              {Status: opImplemented, Tag: "Library"},
	"GET /Movies/Recommendations":                               {Status: opImplemented, Tag: "Movies"},
	"GET /MusicGenres":                                          {Status: opStubbed, Tag: "MusicGenres"},
	"GET /MusicGenres/{genreName}":                              {Status: opPlanned, Tag: "MusicGenres"},
	"GET /MusicGenres/{name}/Images/{imageType}":                {Status: opPlanned, Tag: "Image"},
	"GET /MusicGenres/{name}/Images/{imageType}/{imageIndex}":   {Status: opPlanned, Tag: "Image"},
	"GET /MusicGenres/{name}/InstantMix":                        {Status: opPlanned, Tag: "InstantMix"},
	"GET /MusicGenres/InstantMix":                               {Status: opPlanned, Tag: "InstantMix"},
	"GET /Packages":                                             {Status: opStubbed, Tag: "Package"},
	"GET /Packages/{name}":                                      {Status: opOutOfScope, Tag: "Package"},
	"GET /Persons":                                              {Status: opStubbed, Tag: "Persons"},
	"GET /Persons/{name}":                                       {Status: opPlanned, Tag: "Persons"},
	"GET /Persons/{name}/Images/{imageType}":                    {Status: opPlanned, Tag: "Image"},
	"GET /Persons/{name}/Images/{imageType}/{imageIndex}":       {Status: opPlanned, Tag: "Image"},
	"GET /Playback/BitrateTest":                                 {Status: opImplemented, Tag: "MediaInfo"},
	"GET /Playlists/{itemId}/InstantMix":                        {Status: opImplemented, Tag: "InstantMix"},
	"GET /Playlists/{playlistId}":                               {Status: opPlanned, Tag: "Playlists"},
	"GET /Playlists/{playlistId}/Items":                         {Status: opImplemented, Tag: "Playlists"},
	"GET /Playlists/{playlistId}/Users":                         {Status: opPlanned, Tag: "Playlists"},
	"GET /Playlists/{playlistId}/Users/{userId}":                {Status: opImplemented, Tag: "Playlists"},
	"GET /Plugins":                                              {Status: opStubbed, Tag: "Plugins"},
	"GET /Plugins/{pluginId}/{version}/Image":                   {Status: opOutOfScope, Tag: "Plugins"},
	"GET /Plugins/{pluginId}/Configuration":                     {Status: opOutOfScope, Tag: "Plugins"},
	"GET /Providers/Lyrics/{lyricId}":                           {Status: opPlanned, Tag: "Lyrics"},
	"GET /Providers/Subtitles/Subtitles/{subtitleId}":           {Status: opPlanned, Tag: "Subtitle"},
	"GET /QuickConnect/Connect":                                 {Status: opPlanned, Tag: "QuickConnect"},
	"GET /QuickConnect/Enabled":                                 {Status: opImplemented, Tag: "QuickConnect"},
	"GET /Repositories":                                         {Status: opOutOfScope, Tag: "Package"},
	"GET /ScheduledTasks":                                       {Status: opStubbed, Tag: "ScheduledTasks"},
	"GET /ScheduledTasks/{taskId}":                              {Status: opOutOfScope, Tag: "ScheduledTasks"},
	"GET /Search/Hints":                                         {Status: opImplemented, Tag: "Search"},
	"GET /Sessions":                                             {Status: opImplemented, Tag: "Session"},
	"GET /Shows/{itemId}/Similar":                               {Status: opImplemented, Tag: "Library"},
	"GET /Shows/{seriesId}/Episodes":                            {Status: opImplemented, Tag: "TvShows"},
	"GET /Shows/{seriesId}/Seasons":                             {Status: opImplemented, Tag: "TvShows"},
	"GET /Shows/NextUp":                                         {Status: opImplemented, Tag: "TvShows"},
	"GET /Shows/Upcoming":                                       {Status: opStubbed, Tag: "TvShows"},
	"GET /Songs/{itemId}/InstantMix":                            {Status: opImplemented, Tag: "InstantMix"},
	"GET /Startup/Configuration":                                {Status: opStubbed, Tag: "Startup"}, // 401: wizard is always complete on Heya
	"GET /Startup/FirstUser":                                    {Status: opStubbed, Tag: "Startup"}, // 401: wizard is always complete on Heya
	"GET /Startup/User":                                         {Status: opStubbed, Tag: "Startup"}, // 401: wizard is always complete on Heya
	"GET /Studios":                                              {Status: opStubbed, Tag: "Studios"},
	"GET /Studios/{name}":                                       {Status: opPlanned, Tag: "Studios"},
	"GET /Studios/{name}/Images/{imageType}":                    {Status: opPlanned, Tag: "Image"},
	"GET /Studios/{name}/Images/{imageType}/{imageIndex}":       {Status: opPlanned, Tag: "Image"},
	"GET /SyncPlay/{id}":                                        {Status: opOutOfScope, Tag: "SyncPlay"},
	"GET /SyncPlay/List":                                        {Status: opOutOfScope, Tag: "SyncPlay"},
	"GET /System/ActivityLog/Entries":                           {Status: opStubbed, Tag: "ActivityLog"}, // empty page: feed not mapped yet
	"GET /System/Configuration":                                 {Status: opOutOfScope, Tag: "Configuration"},
	"GET /System/Configuration/{key}":                           {Status: opOutOfScope, Tag: "Configuration"},
	"GET /System/Configuration/MetadataOptions/Default":         {Status: opOutOfScope, Tag: "Configuration"},
	"GET /System/Endpoint":                                      {Status: opStubbed, Tag: "System"},
	"GET /System/Info":                                          {Status: opImplemented, Tag: "System"},
	"GET /System/Info/Public":                                   {Status: opImplemented, Tag: "System"},
	"GET /System/Info/Storage":                                  {Status: opPlanned, Tag: "System"},
	"GET /System/Logs":                                          {Status: opPlanned, Tag: "System"},
	"GET /System/Logs/Log":                                      {Status: opPlanned, Tag: "System"},
	"GET /System/Ping":                                          {Status: opImplemented, Tag: "System"},
	"GET /Tmdb/ClientConfiguration":                             {Status: opOutOfScope, Tag: "Tmdb"},
	"GET /Trailers":                                             {Status: opPlanned, Tag: "Trailers"},
	"GET /Trailers/{itemId}/Similar":                            {Status: opImplemented, Tag: "Library"},
	"GET /UserImage":                                            {Status: opPlanned, Tag: "Image"},
	"GET /UserItems/{itemId}/UserData":                          {Status: opPlanned, Tag: "Items"},
	"GET /UserItems/Resume":                                     {Status: opImplemented, Tag: "Items"},
	"GET /Users":                                                {Status: opImplemented, Tag: "User"},
	"GET /Users/{userId}":                                       {Status: opImplemented, Tag: "User"},
	"GET /Users/Me":                                             {Status: opImplemented, Tag: "User"},
	"GET /Users/Public":                                         {Status: opImplemented, Tag: "User"},
	"GET /UserViews":                                            {Status: opImplemented, Tag: "UserViews"},
	"GET /UserViews/GroupingOptions":                            {Status: opStubbed, Tag: "UserViews"},
	"GET /Videos/{itemId}/{mediaSourceId}/Subtitles/{index}/subtitles.m3u8": {Status: opPlanned, Tag: "Subtitle"},
	"GET /Videos/{itemId}/AdditionalParts":                                  {Status: opStubbed, Tag: "Videos"},
	"GET /Videos/{itemId}/hls/{playlistId}/{segmentId}.{segmentContainer}":  {Status: opPlanned, Tag: "HlsSegment"},
	"GET /Videos/{itemId}/hls/{playlistId}/stream.m3u8":                     {Status: opPlanned, Tag: "HlsSegment"},
	"GET /Videos/{itemId}/hls1/{playlistId}/{segmentId}.{container}":        {Status: opPlanned, Tag: "DynamicHls"},
	"GET /Videos/{itemId}/live.m3u8":                                        {Status: opPlanned, Tag: "DynamicHls"},
	"GET /Videos/{itemId}/main.m3u8":                                        {Status: opPlanned, Tag: "DynamicHls"},
	"GET /Videos/{itemId}/master.m3u8":                                      {Status: opPlanned, Tag: "DynamicHls"},
	"GET /Videos/{itemId}/stream.{container}":                               {Status: opImplemented, Tag: "Videos"},
	"GET /Videos/{itemId}/stream":                                           {Status: opImplemented, Tag: "Videos"},
	"GET /Videos/{itemId}/Trickplay/{width}/{index}.jpg":                    {Status: opImplemented, Tag: "Trickplay"}, // serves the native 320px sheets whatever width is asked
	"GET /Videos/{itemId}/Trickplay/{width}/tiles.m3u8":                     {Status: opPlanned, Tag: "Trickplay"},
	"GET /Videos/{routeItemId}/{routeMediaSourceId}/Subtitles/{routeIndex}/{routeStartPositionTicks}/Stream.{routeFormat}": {Status: opImplemented, Tag: "Subtitle"},
	"GET /Videos/{routeItemId}/{routeMediaSourceId}/Subtitles/{routeIndex}/Stream.{routeFormat}":                           {Status: opImplemented, Tag: "Subtitle"},
	"GET /Videos/{videoId}/{mediaSourceId}/Attachments/{index}":                                                            {Status: opPlanned, Tag: "VideoAttachments"},
	"GET /web/ConfigurationPage":  {Status: opStubbed, Tag: "Dashboard"}, // 404: no plugin pages
	"GET /web/ConfigurationPages": {Status: opStubbed, Tag: "Dashboard"}, // []: no plugins
	"GET /Years":                  {Status: opStubbed, Tag: "Years"},
	"GET /Years/{year}":           {Status: opPlanned, Tag: "Years"},
	"HEAD /Artists/{name}/Images/{imageType}/{imageIndex}": {Status: opPlanned, Tag: "Image"},
	"HEAD /Audio/{itemId}/master.m3u8":                     {Status: opPlanned, Tag: "DynamicHls"},
	"HEAD /Audio/{itemId}/stream.{container}":              {Status: opImplemented, Tag: "Audio"},
	"HEAD /Audio/{itemId}/stream":                          {Status: opImplemented, Tag: "Audio"},
	"HEAD /Audio/{itemId}/universal":                       {Status: opImplemented, Tag: "UniversalAudio"},
	"HEAD /Genres/{name}/Images/{imageType}":               {Status: opPlanned, Tag: "Image"},
	"HEAD /Genres/{name}/Images/{imageType}/{imageIndex}":  {Status: opPlanned, Tag: "Image"},
	"HEAD /Items/{itemId}/Images/{imageType}":              {Status: opPlanned, Tag: "Image"},
	"HEAD /Items/{itemId}/Images/{imageType}/{imageIndex}": {Status: opPlanned, Tag: "Image"},
	"HEAD /Items/{itemId}/Images/{imageType}/{imageIndex}/{tag}/{format}/{maxWidth}/{maxHeight}/{percentPlayed}/{unplayedCount}": {Status: opPlanned, Tag: "Image"},
	"HEAD /MusicGenres/{name}/Images/{imageType}":              {Status: opPlanned, Tag: "Image"},
	"HEAD /MusicGenres/{name}/Images/{imageType}/{imageIndex}": {Status: opPlanned, Tag: "Image"},
	"HEAD /Persons/{name}/Images/{imageType}":                  {Status: opPlanned, Tag: "Image"},
	"HEAD /Persons/{name}/Images/{imageType}/{imageIndex}":     {Status: opPlanned, Tag: "Image"},
	"HEAD /Studios/{name}/Images/{imageType}":                  {Status: opPlanned, Tag: "Image"},
	"HEAD /Studios/{name}/Images/{imageType}/{imageIndex}":     {Status: opPlanned, Tag: "Image"},
	"HEAD /UserImage":                                             {Status: opPlanned, Tag: "Image"},
	"HEAD /Videos/{itemId}/master.m3u8":                           {Status: opPlanned, Tag: "DynamicHls"},
	"HEAD /Videos/{itemId}/stream.{container}":                    {Status: opImplemented, Tag: "Videos"},
	"HEAD /Videos/{itemId}/stream":                                {Status: opImplemented, Tag: "Videos"},
	"POST /Audio/{itemId}/Lyrics":                                 {Status: opPlanned, Tag: "Lyrics"},
	"POST /Audio/{itemId}/RemoteSearch/Lyrics/{lyricId}":          {Status: opPlanned, Tag: "Lyrics"},
	"POST /Auth/Keys":                                             {Status: opOutOfScope, Tag: "ApiKey"},
	"POST /Backup/Create":                                         {Status: opOutOfScope, Tag: "Backup"},
	"POST /Backup/Restore":                                        {Status: opOutOfScope, Tag: "Backup"},
	"POST /Branding/Splashscreen":                                 {Status: opPlanned, Tag: "Image"},
	"POST /ClientLog/Document":                                    {Status: opOutOfScope, Tag: "ClientLog"},
	"POST /Collections":                                           {Status: opOutOfScope, Tag: "Collection"},
	"POST /Collections/{collectionId}/Items":                      {Status: opOutOfScope, Tag: "Collection"},
	"POST /Devices/Options":                                       {Status: opPlanned, Tag: "Devices"},
	"POST /DisplayPreferences/{displayPreferencesId}":             {Status: opImplemented, Tag: "DisplayPreferences"},
	"POST /Environment/ValidatePath":                              {Status: opOutOfScope, Tag: "Environment"},
	"POST /Items/{itemId}":                                        {Status: opOutOfScope, Tag: "ItemUpdate"},
	"POST /Items/{itemId}/ContentType":                            {Status: opOutOfScope, Tag: "ItemUpdate"},
	"POST /Items/{itemId}/Images/{imageType}":                     {Status: opPlanned, Tag: "Image"},
	"POST /Items/{itemId}/Images/{imageType}/{imageIndex}":        {Status: opPlanned, Tag: "Image"},
	"POST /Items/{itemId}/Images/{imageType}/{imageIndex}/Index":  {Status: opPlanned, Tag: "Image"},
	"POST /Items/{itemId}/PlaybackInfo":                           {Status: opImplemented, Tag: "MediaInfo"},
	"POST /Items/{itemId}/Refresh":                                {Status: opOutOfScope, Tag: "ItemRefresh"},
	"POST /Items/{itemId}/RemoteImages/Download":                  {Status: opOutOfScope, Tag: "RemoteImage"},
	"POST /Items/{itemId}/RemoteSearch/Subtitles/{subtitleId}":    {Status: opPlanned, Tag: "Subtitle"},
	"POST /Items/RemoteSearch/Apply/{itemId}":                     {Status: opOutOfScope, Tag: "ItemLookup"},
	"POST /Items/RemoteSearch/Book":                               {Status: opOutOfScope, Tag: "ItemLookup"},
	"POST /Items/RemoteSearch/BoxSet":                             {Status: opOutOfScope, Tag: "ItemLookup"},
	"POST /Items/RemoteSearch/Movie":                              {Status: opOutOfScope, Tag: "ItemLookup"},
	"POST /Items/RemoteSearch/MusicAlbum":                         {Status: opOutOfScope, Tag: "ItemLookup"},
	"POST /Items/RemoteSearch/MusicArtist":                        {Status: opOutOfScope, Tag: "ItemLookup"},
	"POST /Items/RemoteSearch/MusicVideo":                         {Status: opOutOfScope, Tag: "ItemLookup"},
	"POST /Items/RemoteSearch/Person":                             {Status: opOutOfScope, Tag: "ItemLookup"},
	"POST /Items/RemoteSearch/Series":                             {Status: opOutOfScope, Tag: "ItemLookup"},
	"POST /Items/RemoteSearch/Trailer":                            {Status: opOutOfScope, Tag: "ItemLookup"},
	"POST /Library/Media/Updated":                                 {Status: opPlanned, Tag: "Library"},
	"POST /Library/Movies/Added":                                  {Status: opPlanned, Tag: "Library"},
	"POST /Library/Movies/Updated":                                {Status: opPlanned, Tag: "Library"},
	"POST /Library/Refresh":                                       {Status: opPlanned, Tag: "Library"},
	"POST /Library/Series/Added":                                  {Status: opPlanned, Tag: "Library"},
	"POST /Library/Series/Updated":                                {Status: opPlanned, Tag: "Library"},
	"POST /Library/VirtualFolders":                                {Status: opStubbed, Tag: "LibraryStructure"}, // 403: Heya-managed
	"POST /Library/VirtualFolders/LibraryOptions":                 {Status: opStubbed, Tag: "LibraryStructure"}, // validated, then 403: Heya-managed
	"POST /Library/VirtualFolders/Name":                           {Status: opStubbed, Tag: "LibraryStructure"}, // validated, then 403: Heya-managed
	"POST /Library/VirtualFolders/Paths":                          {Status: opStubbed, Tag: "LibraryStructure"}, // validated, then 404: Heya-managed
	"POST /Library/VirtualFolders/Paths/Update":                   {Status: opStubbed, Tag: "LibraryStructure"}, // validated, then 403: Heya-managed
	"POST /LiveStreams/Close":                                     {Status: opPlanned, Tag: "MediaInfo"},
	"POST /LiveStreams/Open":                                      {Status: opPlanned, Tag: "MediaInfo"},
	"POST /LiveTv/ChannelMappings":                                {Status: opOutOfScope, Tag: "LiveTv"},
	"POST /LiveTv/ListingProviders":                               {Status: opOutOfScope, Tag: "LiveTv"},
	"POST /LiveTv/Programs":                                       {Status: opOutOfScope, Tag: "LiveTv"},
	"POST /LiveTv/SeriesTimers":                                   {Status: opOutOfScope, Tag: "LiveTv"},
	"POST /LiveTv/SeriesTimers/{timerId}":                         {Status: opOutOfScope, Tag: "LiveTv"},
	"POST /LiveTv/Timers":                                         {Status: opOutOfScope, Tag: "LiveTv"},
	"POST /LiveTv/Timers/{timerId}":                               {Status: opOutOfScope, Tag: "LiveTv"},
	"POST /LiveTv/TunerHosts":                                     {Status: opStubbed, Tag: "LiveTv"}, // 404: no LiveTV
	"POST /LiveTv/Tuners/{tunerId}/Reset":                         {Status: opOutOfScope, Tag: "LiveTv"},
	"POST /Packages/Installed/{name}":                             {Status: opOutOfScope, Tag: "Package"},
	"POST /PlayingItems/{itemId}":                                 {Status: opPlanned, Tag: "Playstate"},
	"POST /PlayingItems/{itemId}/Progress":                        {Status: opPlanned, Tag: "Playstate"},
	"POST /Playlists":                                             {Status: opImplemented, Tag: "Playlists"},
	"POST /Playlists/{playlistId}":                                {Status: opPlanned, Tag: "Playlists"},
	"POST /Playlists/{playlistId}/Items":                          {Status: opImplemented, Tag: "Playlists"},
	"POST /Playlists/{playlistId}/Items/{itemId}/Move/{newIndex}": {Status: opPlanned, Tag: "Playlists"},
	"POST /Playlists/{playlistId}/Users/{userId}":                 {Status: opPlanned, Tag: "Playlists"},
	"POST /Plugins/{pluginId}/{version}/Disable":                  {Status: opOutOfScope, Tag: "Plugins"},
	"POST /Plugins/{pluginId}/{version}/Enable":                   {Status: opOutOfScope, Tag: "Plugins"},
	"POST /Plugins/{pluginId}/Configuration":                      {Status: opOutOfScope, Tag: "Plugins"},
	"POST /Plugins/{pluginId}/Manifest":                           {Status: opOutOfScope, Tag: "Plugins"},
	"POST /QuickConnect/Authorize":                                {Status: opPlanned, Tag: "QuickConnect"},
	"POST /QuickConnect/Initiate":                                 {Status: opPlanned, Tag: "QuickConnect"},
	"POST /Repositories":                                          {Status: opOutOfScope, Tag: "Package"},
	"POST /ScheduledTasks/{taskId}/Triggers":                      {Status: opOutOfScope, Tag: "ScheduledTasks"},
	"POST /ScheduledTasks/Running/{taskId}":                       {Status: opOutOfScope, Tag: "ScheduledTasks"},
	"POST /Sessions/{sessionId}/Command":                          {Status: opStubbed, Tag: "Session"},
	"POST /Sessions/{sessionId}/Command/{command}":                {Status: opStubbed, Tag: "Session"},
	"POST /Sessions/{sessionId}/Message":                          {Status: opStubbed, Tag: "Session"},
	"POST /Sessions/{sessionId}/Playing":                          {Status: opStubbed, Tag: "Session"},
	"POST /Sessions/{sessionId}/Playing/{command}":                {Status: opStubbed, Tag: "Session"},
	"POST /Sessions/{sessionId}/System/{command}":                 {Status: opStubbed, Tag: "Session"},
	"POST /Sessions/{sessionId}/User/{userId}":                    {Status: opPlanned, Tag: "Session"},
	"POST /Sessions/{sessionId}/Viewing":                          {Status: opStubbed, Tag: "Session"},
	"POST /Sessions/Capabilities":                                 {Status: opImplemented, Tag: "Session"},
	"POST /Sessions/Capabilities/Full":                            {Status: opImplemented, Tag: "Session"},
	"POST /Sessions/Logout":                                       {Status: opImplemented, Tag: "Session"},
	"POST /Sessions/Playing":                                      {Status: opImplemented, Tag: "Playstate"},
	"POST /Sessions/Playing/Ping":                                 {Status: opImplemented, Tag: "Playstate"},
	"POST /Sessions/Playing/Progress":                             {Status: opImplemented, Tag: "Playstate"},
	"POST /Sessions/Playing/Stopped":                              {Status: opImplemented, Tag: "Playstate"},
	"POST /Sessions/Viewing":                                      {Status: opImplemented, Tag: "Session"},
	"POST /Startup/Complete":                                      {Status: opStubbed, Tag: "Startup"}, // 401: wizard is always complete on Heya
	"POST /Startup/Configuration":                                 {Status: opStubbed, Tag: "Startup"}, // 401: wizard is always complete on Heya
	"POST /Startup/RemoteAccess":                                  {Status: opOutOfScope, Tag: "Startup"},
	"POST /Startup/User":                                          {Status: opStubbed, Tag: "Startup"}, // 401: wizard is always complete on Heya
	"POST /SyncPlay/Buffering":                                    {Status: opOutOfScope, Tag: "SyncPlay"},
	"POST /SyncPlay/Join":                                         {Status: opOutOfScope, Tag: "SyncPlay"},
	"POST /SyncPlay/Leave":                                        {Status: opOutOfScope, Tag: "SyncPlay"},
	"POST /SyncPlay/MovePlaylistItem":                             {Status: opOutOfScope, Tag: "SyncPlay"},
	"POST /SyncPlay/New":                                          {Status: opOutOfScope, Tag: "SyncPlay"},
	"POST /SyncPlay/NextItem":                                     {Status: opOutOfScope, Tag: "SyncPlay"},
	"POST /SyncPlay/Pause":                                        {Status: opOutOfScope, Tag: "SyncPlay"},
	"POST /SyncPlay/Ping":                                         {Status: opOutOfScope, Tag: "SyncPlay"},
	"POST /SyncPlay/PreviousItem":                                 {Status: opOutOfScope, Tag: "SyncPlay"},
	"POST /SyncPlay/Queue":                                        {Status: opOutOfScope, Tag: "SyncPlay"},
	"POST /SyncPlay/Ready":                                        {Status: opOutOfScope, Tag: "SyncPlay"},
	"POST /SyncPlay/RemoveFromPlaylist":                           {Status: opOutOfScope, Tag: "SyncPlay"},
	"POST /SyncPlay/Seek":                                         {Status: opOutOfScope, Tag: "SyncPlay"},
	"POST /SyncPlay/SetIgnoreWait":                                {Status: opOutOfScope, Tag: "SyncPlay"},
	"POST /SyncPlay/SetNewQueue":                                  {Status: opOutOfScope, Tag: "SyncPlay"},
	"POST /SyncPlay/SetPlaylistItem":                              {Status: opOutOfScope, Tag: "SyncPlay"},
	"POST /SyncPlay/SetRepeatMode":                                {Status: opOutOfScope, Tag: "SyncPlay"},
	"POST /SyncPlay/SetShuffleMode":                               {Status: opOutOfScope, Tag: "SyncPlay"},
	"POST /SyncPlay/Stop":                                         {Status: opOutOfScope, Tag: "SyncPlay"},
	"POST /SyncPlay/Unpause":                                      {Status: opOutOfScope, Tag: "SyncPlay"},
	"POST /System/Configuration":                                  {Status: opOutOfScope, Tag: "Configuration"},
	"POST /System/Configuration/{key}":                            {Status: opOutOfScope, Tag: "Configuration"},
	"POST /System/Configuration/Branding":                         {Status: opOutOfScope, Tag: "Configuration"},
	"POST /System/Ping":                                           {Status: opImplemented, Tag: "System"},
	"POST /System/Restart":                                        {Status: opPlanned, Tag: "System"},
	"POST /System/Shutdown":                                       {Status: opPlanned, Tag: "System"},
	"POST /UserFavoriteItems/{itemId}":                            {Status: opImplemented, Tag: "UserLibrary"},
	"POST /UserImage":                                             {Status: opPlanned, Tag: "Image"},
	"POST /UserItems/{itemId}/Rating":                             {Status: opPlanned, Tag: "UserLibrary"},
	"POST /UserItems/{itemId}/UserData":                           {Status: opPlanned, Tag: "Items"},
	"POST /UserPlayedItems/{itemId}":                              {Status: opImplemented, Tag: "Playstate"},
	"POST /Users":                                                 {Status: opPlanned, Tag: "User"},
	"POST /Users/{userId}/Policy":                                 {Status: opPlanned, Tag: "User"},
	"POST /Users/AuthenticateByName":                              {Status: opImplemented, Tag: "User"},
	"POST /Users/AuthenticateWithQuickConnect":                    {Status: opPlanned, Tag: "User"},
	"POST /Users/Configuration":                                   {Status: opPlanned, Tag: "User"},
	"POST /Users/ForgotPassword":                                  {Status: opPlanned, Tag: "User"},
	"POST /Users/ForgotPassword/Pin":                              {Status: opPlanned, Tag: "User"},
	"POST /Users/New":                                             {Status: opPlanned, Tag: "User"},
	"POST /Users/Password":                                        {Status: opPlanned, Tag: "User"},
	"POST /Videos/{itemId}/Subtitles":                             {Status: opPlanned, Tag: "Subtitle"},
	"POST /Videos/MergeVersions":                                  {Status: opPlanned, Tag: "Videos"},
}
