// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: collections.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countAllCollections = `-- name: CountAllCollections :one
SELECT count(*) FROM collections
`

func (q *Queries) CountAllCollections(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countAllCollections)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCollection = `-- name: CreateCollection :one
INSERT INTO collections (external_ids, name, overview, poster_path, backdrop_path)
VALUES ($1, $2, $3, $4, $5) RETURNING id, external_ids, name, overview, poster_path, backdrop_path, search_vector
`

type CreateCollectionParams struct {
	ExternalIds  []byte `json:"external_ids"`
	Name         string `json:"name"`
	Overview     string `json:"overview"`
	PosterPath   string `json:"poster_path"`
	BackdropPath string `json:"backdrop_path"`
}

func (q *Queries) CreateCollection(ctx context.Context, arg CreateCollectionParams) (Collection, error) {
	row := q.db.QueryRow(ctx, createCollection,
		arg.ExternalIds,
		arg.Name,
		arg.Overview,
		arg.PosterPath,
		arg.BackdropPath,
	)
	var i Collection
	err := row.Scan(
		&i.ID,
		&i.ExternalIds,
		&i.Name,
		&i.Overview,
		&i.PosterPath,
		&i.BackdropPath,
		&i.SearchVector,
	)
	return i, err
}

const findCollectionByName = `-- name: FindCollectionByName :one
SELECT id, external_ids, name, overview, poster_path, backdrop_path, search_vector FROM collections WHERE name = $1 LIMIT 1
`

func (q *Queries) FindCollectionByName(ctx context.Context, name string) (Collection, error) {
	row := q.db.QueryRow(ctx, findCollectionByName, name)
	var i Collection
	err := row.Scan(
		&i.ID,
		&i.ExternalIds,
		&i.Name,
		&i.Overview,
		&i.PosterPath,
		&i.BackdropPath,
		&i.SearchVector,
	)
	return i, err
}

const getCollectionByID = `-- name: GetCollectionByID :one
SELECT id, external_ids, name, overview, poster_path, backdrop_path, search_vector FROM collections WHERE id = $1
`

func (q *Queries) GetCollectionByID(ctx context.Context, id int64) (Collection, error) {
	row := q.db.QueryRow(ctx, getCollectionByID, id)
	var i Collection
	err := row.Scan(
		&i.ID,
		&i.ExternalIds,
		&i.Name,
		&i.Overview,
		&i.PosterPath,
		&i.BackdropPath,
		&i.SearchVector,
	)
	return i, err
}

const listAllCollections = `-- name: ListAllCollections :many
SELECT c.id, c.external_ids, c.name, c.overview, c.poster_path, c.backdrop_path, c.search_vector,
       (SELECT count(*) FROM movies m WHERE m.collection_id = c.id)::int AS movie_count
FROM collections c
ORDER BY c.name
LIMIT $1 OFFSET $2
`

type ListAllCollectionsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListAllCollectionsRow struct {
	ID           int64       `json:"id"`
	ExternalIds  []byte      `json:"external_ids"`
	Name         string      `json:"name"`
	Overview     string      `json:"overview"`
	PosterPath   string      `json:"poster_path"`
	BackdropPath string      `json:"backdrop_path"`
	SearchVector interface{} `json:"search_vector"`
	MovieCount   int32       `json:"movie_count"`
}

func (q *Queries) ListAllCollections(ctx context.Context, arg ListAllCollectionsParams) ([]ListAllCollectionsRow, error) {
	rows, err := q.db.Query(ctx, listAllCollections, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAllCollectionsRow{}
	for rows.Next() {
		var i ListAllCollectionsRow
		if err := rows.Scan(
			&i.ID,
			&i.ExternalIds,
			&i.Name,
			&i.Overview,
			&i.PosterPath,
			&i.BackdropPath,
			&i.SearchVector,
			&i.MovieCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCollectionMovies = `-- name: ListCollectionMovies :many
SELECT mi.id, mi.library_id, mi.media_type, mi.title, mi.sort_title, mi.year, mi.description, mi.poster_path, mi.backdrop_path, mi.external_ids, mi.slug, mi.homepage, mi.tagline, mi.original_title, mi.original_language, mi.status, mi.provider_kind, mi.heya_slug, mi.heya_enriched_at, mi.metadata_refreshed_at, mi.created_at, mi.updated_at, mi.search_vector, mi.matched_at, mi.enrichment_status, mi.base_enriched_at, mi.people_enriched_at, mi.extras_enriched_at, mi.images_enriched_at, mi.structure_enriched_at, mi.last_enrich_attempt_at, mi.last_enrich_error, mi.field_provenance, mi.match_confidence, mi.local_identity_key, mi.slug_locked
FROM media_items mi
JOIN movies m ON m.media_item_id = mi.id
WHERE m.collection_id = $1
ORDER BY m.release_date NULLS LAST
`

func (q *Queries) ListCollectionMovies(ctx context.Context, collectionID pgtype.Int8) ([]MediaItem, error) {
	rows, err := q.db.Query(ctx, listCollectionMovies, collectionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MediaItem{}
	for rows.Next() {
		var i MediaItem
		if err := rows.Scan(
			&i.ID,
			&i.LibraryID,
			&i.MediaType,
			&i.Title,
			&i.SortTitle,
			&i.Year,
			&i.Description,
			&i.PosterPath,
			&i.BackdropPath,
			&i.ExternalIds,
			&i.Slug,
			&i.Homepage,
			&i.Tagline,
			&i.OriginalTitle,
			&i.OriginalLanguage,
			&i.Status,
			&i.ProviderKind,
			&i.HeyaSlug,
			&i.HeyaEnrichedAt,
			&i.MetadataRefreshedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SearchVector,
			&i.MatchedAt,
			&i.EnrichmentStatus,
			&i.BaseEnrichedAt,
			&i.PeopleEnrichedAt,
			&i.ExtrasEnrichedAt,
			&i.ImagesEnrichedAt,
			&i.StructureEnrichedAt,
			&i.LastEnrichAttemptAt,
			&i.LastEnrichError,
			&i.FieldProvenance,
			&i.MatchConfidence,
			&i.LocalIdentityKey,
			&i.SlugLocked,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCollectionsWithLocalMedia = `-- name: ListCollectionsWithLocalMedia :many
SELECT c.id, c.name, c.poster_path,
       count(m.id)::int AS movie_count
FROM collections c
JOIN movies m ON m.collection_id = c.id
GROUP BY c.id, c.name, c.poster_path
HAVING count(m.id) > 0
ORDER BY c.name
`

type ListCollectionsWithLocalMediaRow struct {
	ID         int64  `json:"id"`
	Name       string `json:"name"`
	PosterPath string `json:"poster_path"`
	MovieCount int32  `json:"movie_count"`
}

func (q *Queries) ListCollectionsWithLocalMedia(ctx context.Context) ([]ListCollectionsWithLocalMediaRow, error) {
	rows, err := q.db.Query(ctx, listCollectionsWithLocalMedia)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCollectionsWithLocalMediaRow{}
	for rows.Next() {
		var i ListCollectionsWithLocalMediaRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.PosterPath,
			&i.MovieCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
