// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: episode_overviews.sql

package sqlc

import (
	"context"
)

const createEpisodeOverview = `-- name: CreateEpisodeOverview :exec
INSERT INTO episode_overviews (episode_id, language, overview)
VALUES ($1, $2, $3)
ON CONFLICT (episode_id, language) DO UPDATE SET overview = EXCLUDED.overview
`

type CreateEpisodeOverviewParams struct {
	EpisodeID int64  `json:"episode_id"`
	Language  string `json:"language"`
	Overview  string `json:"overview"`
}

func (q *Queries) CreateEpisodeOverview(ctx context.Context, arg CreateEpisodeOverviewParams) error {
	_, err := q.db.Exec(ctx, createEpisodeOverview, arg.EpisodeID, arg.Language, arg.Overview)
	return err
}

const deleteEpisodeOverviews = `-- name: DeleteEpisodeOverviews :exec
DELETE FROM episode_overviews WHERE episode_id = $1
`

func (q *Queries) DeleteEpisodeOverviews(ctx context.Context, episodeID int64) error {
	_, err := q.db.Exec(ctx, deleteEpisodeOverviews, episodeID)
	return err
}

const getEpisodeOverviewByLanguage = `-- name: GetEpisodeOverviewByLanguage :one
SELECT id, episode_id, language, overview FROM episode_overviews WHERE episode_id = $1 AND language = $2
`

type GetEpisodeOverviewByLanguageParams struct {
	EpisodeID int64  `json:"episode_id"`
	Language  string `json:"language"`
}

func (q *Queries) GetEpisodeOverviewByLanguage(ctx context.Context, arg GetEpisodeOverviewByLanguageParams) (EpisodeOverview, error) {
	row := q.db.QueryRow(ctx, getEpisodeOverviewByLanguage, arg.EpisodeID, arg.Language)
	var i EpisodeOverview
	err := row.Scan(
		&i.ID,
		&i.EpisodeID,
		&i.Language,
		&i.Overview,
	)
	return i, err
}

const listEpisodeOverviews = `-- name: ListEpisodeOverviews :many
SELECT id, episode_id, language, overview FROM episode_overviews WHERE episode_id = $1 ORDER BY language
`

func (q *Queries) ListEpisodeOverviews(ctx context.Context, episodeID int64) ([]EpisodeOverview, error) {
	rows, err := q.db.Query(ctx, listEpisodeOverviews, episodeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EpisodeOverview{}
	for rows.Next() {
		var i EpisodeOverview
		if err := rows.Scan(
			&i.ID,
			&i.EpisodeID,
			&i.Language,
			&i.Overview,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
