// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: favorites.sql

package sqlc

import (
	"context"
)

const isFavorited = `-- name: IsFavorited :one
SELECT EXISTS(
  SELECT 1 FROM user_favorites
  WHERE user_id = $1 AND entity_type = $2 AND entity_id = $3
) AS favorited
`

type IsFavoritedParams struct {
	UserID     int64  `json:"user_id"`
	EntityType string `json:"entity_type"`
	EntityID   int64  `json:"entity_id"`
}

func (q *Queries) IsFavorited(ctx context.Context, arg IsFavoritedParams) (bool, error) {
	row := q.db.QueryRow(ctx, isFavorited, arg.UserID, arg.EntityType, arg.EntityID)
	var favorited bool
	err := row.Scan(&favorited)
	return favorited, err
}

const listFavoritesByEntity = `-- name: ListFavoritesByEntity :many
SELECT id, user_id, entity_type, entity_id, created_at FROM user_favorites
WHERE user_id = $1 AND entity_type = $2
ORDER BY created_at DESC
`

type ListFavoritesByEntityParams struct {
	UserID     int64  `json:"user_id"`
	EntityType string `json:"entity_type"`
}

func (q *Queries) ListFavoritesByEntity(ctx context.Context, arg ListFavoritesByEntityParams) ([]UserFavorite, error) {
	rows, err := q.db.Query(ctx, listFavoritesByEntity, arg.UserID, arg.EntityType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UserFavorite{}
	for rows.Next() {
		var i UserFavorite
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.EntityType,
			&i.EntityID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserFavoriteMediaItems = `-- name: ListUserFavoriteMediaItems :many
SELECT mi.id, mi.library_id, mi.media_type, mi.title, mi.sort_title, mi.year, mi.description, mi.poster_path, mi.backdrop_path, mi.external_ids, mi.slug, mi.homepage, mi.tagline, mi.original_title, mi.original_language, mi.status, mi.provider_kind, mi.heya_slug, mi.heya_enriched_at, mi.metadata_refreshed_at, mi.created_at, mi.updated_at, mi.search_vector
FROM media_items mi
JOIN user_favorites uf ON uf.entity_id = mi.id AND uf.entity_type = 'media_item'
WHERE uf.user_id = $1
ORDER BY uf.created_at DESC
LIMIT $2 OFFSET $3
`

type ListUserFavoriteMediaItemsParams struct {
	UserID int64 `json:"user_id"`
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListUserFavoriteMediaItems(ctx context.Context, arg ListUserFavoriteMediaItemsParams) ([]MediaItem, error) {
	rows, err := q.db.Query(ctx, listUserFavoriteMediaItems, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MediaItem{}
	for rows.Next() {
		var i MediaItem
		if err := rows.Scan(
			&i.ID,
			&i.LibraryID,
			&i.MediaType,
			&i.Title,
			&i.SortTitle,
			&i.Year,
			&i.Description,
			&i.PosterPath,
			&i.BackdropPath,
			&i.ExternalIds,
			&i.Slug,
			&i.Homepage,
			&i.Tagline,
			&i.OriginalTitle,
			&i.OriginalLanguage,
			&i.Status,
			&i.ProviderKind,
			&i.HeyaSlug,
			&i.HeyaEnrichedAt,
			&i.MetadataRefreshedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SearchVector,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeFavorite = `-- name: RemoveFavorite :exec
DELETE FROM user_favorites
WHERE user_id = $1 AND entity_type = $2 AND entity_id = $3
`

type RemoveFavoriteParams struct {
	UserID     int64  `json:"user_id"`
	EntityType string `json:"entity_type"`
	EntityID   int64  `json:"entity_id"`
}

func (q *Queries) RemoveFavorite(ctx context.Context, arg RemoveFavoriteParams) error {
	_, err := q.db.Exec(ctx, removeFavorite, arg.UserID, arg.EntityType, arg.EntityID)
	return err
}

const toggleFavorite = `-- name: ToggleFavorite :one
INSERT INTO user_favorites (user_id, entity_type, entity_id)
VALUES ($1, $2, $3)
ON CONFLICT (user_id, entity_type, entity_id) DO NOTHING
RETURNING id, user_id, entity_type, entity_id, created_at
`

type ToggleFavoriteParams struct {
	UserID     int64  `json:"user_id"`
	EntityType string `json:"entity_type"`
	EntityID   int64  `json:"entity_id"`
}

func (q *Queries) ToggleFavorite(ctx context.Context, arg ToggleFavoriteParams) (UserFavorite, error) {
	row := q.db.QueryRow(ctx, toggleFavorite, arg.UserID, arg.EntityType, arg.EntityID)
	var i UserFavorite
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.EntityType,
		&i.EntityID,
		&i.CreatedAt,
	)
	return i, err
}
