// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: genres.sql

package sqlc

import (
	"context"
)

const countMediaByGenreByType = `-- name: CountMediaByGenreByType :many
SELECT mi.media_type::text AS media_type, count(*)::bigint AS count
FROM media_item_cards mi
LEFT JOIN movies m ON m.media_item_id = mi.id
LEFT JOIN tv_series ts ON ts.media_item_id = mi.id
WHERE ($1::text = ANY(m.genres) OR $1::text = ANY(ts.genres))
GROUP BY mi.media_type
`

type CountMediaByGenreByTypeRow struct {
	MediaType string `json:"media_type"`
	Count     int64  `json:"count"`
}

// Per-media_type counts for one genre — feeds both the type-filter segment
// labels and (summed / picked) the paging total.
func (q *Queries) CountMediaByGenreByType(ctx context.Context, genre string) ([]CountMediaByGenreByTypeRow, error) {
	rows, err := q.db.Query(ctx, countMediaByGenreByType, genre)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountMediaByGenreByTypeRow{}
	for rows.Next() {
		var i CountMediaByGenreByTypeRow
		if err := rows.Scan(&i.MediaType, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countMediaByKeywordByType = `-- name: CountMediaByKeywordByType :many
SELECT mi.media_type::text AS media_type, count(*)::bigint AS count
FROM media_item_cards mi
JOIN media_keywords mk ON mk.media_item_id = mi.id
JOIN keywords k ON k.id = mk.keyword_id
WHERE lower(k.name) = lower($1::text)
GROUP BY mi.media_type
`

type CountMediaByKeywordByTypeRow struct {
	MediaType string `json:"media_type"`
	Count     int64  `json:"count"`
}

func (q *Queries) CountMediaByKeywordByType(ctx context.Context, keyword string) ([]CountMediaByKeywordByTypeRow, error) {
	rows, err := q.db.Query(ctx, countMediaByKeywordByType, keyword)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountMediaByKeywordByTypeRow{}
	for rows.Next() {
		var i CountMediaByKeywordByTypeRow
		if err := rows.Scan(&i.MediaType, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllGenres = `-- name: ListAllGenres :many
SELECT genre, count(*) AS count FROM (
  SELECT unnest(genres) AS genre FROM movies
  UNION ALL
  SELECT unnest(genres) AS genre FROM tv_series
) sub
GROUP BY genre
ORDER BY genre
`

type ListAllGenresRow struct {
	Genre interface{} `json:"genre"`
	Count int64       `json:"count"`
}

func (q *Queries) ListAllGenres(ctx context.Context) ([]ListAllGenresRow, error) {
	rows, err := q.db.Query(ctx, listAllGenres)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAllGenresRow{}
	for rows.Next() {
		var i ListAllGenresRow
		if err := rows.Scan(&i.Genre, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMediaByGenre = `-- name: ListMediaByGenre :many

SELECT mi.id, mi.library_id, mi.media_type, mi.title, mi.sort_title, mi.year, mi.description, mi.poster_path, mi.backdrop_path, mi.external_ids, mi.slug, mi.homepage, mi.tagline, mi.original_title, mi.original_language, mi.status, mi.provider_kind, mi.heya_slug, mi.heya_enriched_at, mi.metadata_refreshed_at, mi.created_at, mi.updated_at, mi.search_vector, mi.matched_at, mi.enrichment_status, mi.base_enriched_at, mi.people_enriched_at, mi.extras_enriched_at, mi.images_enriched_at, mi.structure_enriched_at, mi.last_enrich_attempt_at, mi.last_enrich_error, mi.field_provenance, mi.match_confidence, mi.slug_locked, mi.public_id
FROM media_item_cards mi
LEFT JOIN movies m ON m.media_item_id = mi.id
LEFT JOIN tv_series ts ON ts.media_item_id = mi.id
WHERE ($1::text = ANY(m.genres) OR $1::text = ANY(ts.genres))
  AND ($2::text = '' OR mi.media_type::text = $2::text)
ORDER BY
  CASE WHEN $3::text = 'year-desc' THEN NULLIF(mi.year, '') END DESC NULLS LAST,
  CASE WHEN $3::text = 'year-asc'  THEN NULLIF(mi.year, '') END ASC NULLS LAST,
  mi.sort_title ASC, mi.title ASC
LIMIT $5 OFFSET $4
`

type ListMediaByGenreParams struct {
	Genre     string `json:"genre"`
	MediaType string `json:"media_type"`
	Sort      string `json:"sort"`
	Off       int32  `json:"off"`
	Lim       int32  `json:"lim"`
}

// Genre/keyword drilldowns are random-access paged (the browse grid sizes
// its scroll track to the total and fetches whatever page the scrollbar
// lands on), so sorting and type-filtering MUST happen server-side — the
// client never holds the full list. Sort keys mirror the browse UI: title
// (default), year-desc, year-asc; empty years always sink to the bottom.
func (q *Queries) ListMediaByGenre(ctx context.Context, arg ListMediaByGenreParams) ([]MediaItemCard, error) {
	rows, err := q.db.Query(ctx, listMediaByGenre,
		arg.Genre,
		arg.MediaType,
		arg.Sort,
		arg.Off,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MediaItemCard{}
	for rows.Next() {
		var i MediaItemCard
		if err := rows.Scan(
			&i.ID,
			&i.LibraryID,
			&i.MediaType,
			&i.Title,
			&i.SortTitle,
			&i.Year,
			&i.Description,
			&i.PosterPath,
			&i.BackdropPath,
			&i.ExternalIds,
			&i.Slug,
			&i.Homepage,
			&i.Tagline,
			&i.OriginalTitle,
			&i.OriginalLanguage,
			&i.Status,
			&i.ProviderKind,
			&i.HeyaSlug,
			&i.HeyaEnrichedAt,
			&i.MetadataRefreshedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SearchVector,
			&i.MatchedAt,
			&i.EnrichmentStatus,
			&i.BaseEnrichedAt,
			&i.PeopleEnrichedAt,
			&i.ExtrasEnrichedAt,
			&i.ImagesEnrichedAt,
			&i.StructureEnrichedAt,
			&i.LastEnrichAttemptAt,
			&i.LastEnrichError,
			&i.FieldProvenance,
			&i.MatchConfidence,
			&i.SlugLocked,
			&i.PublicID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMediaByKeyword = `-- name: ListMediaByKeyword :many
SELECT mi.id, mi.library_id, mi.media_type, mi.title, mi.sort_title, mi.year, mi.description, mi.poster_path, mi.backdrop_path, mi.external_ids, mi.slug, mi.homepage, mi.tagline, mi.original_title, mi.original_language, mi.status, mi.provider_kind, mi.heya_slug, mi.heya_enriched_at, mi.metadata_refreshed_at, mi.created_at, mi.updated_at, mi.search_vector, mi.matched_at, mi.enrichment_status, mi.base_enriched_at, mi.people_enriched_at, mi.extras_enriched_at, mi.images_enriched_at, mi.structure_enriched_at, mi.last_enrich_attempt_at, mi.last_enrich_error, mi.field_provenance, mi.match_confidence, mi.slug_locked, mi.public_id
FROM media_item_cards mi
JOIN media_keywords mk ON mk.media_item_id = mi.id
JOIN keywords k ON k.id = mk.keyword_id
WHERE lower(k.name) = lower($1::text)
  AND ($2::text = '' OR mi.media_type::text = $2::text)
ORDER BY
  CASE WHEN $3::text = 'year-desc' THEN NULLIF(mi.year, '') END DESC NULLS LAST,
  CASE WHEN $3::text = 'year-asc'  THEN NULLIF(mi.year, '') END ASC NULLS LAST,
  mi.sort_title ASC, mi.title ASC
LIMIT $5 OFFSET $4
`

type ListMediaByKeywordParams struct {
	Keyword   string `json:"keyword"`
	MediaType string `json:"media_type"`
	Sort      string `json:"sort"`
	Off       int32  `json:"off"`
	Lim       int32  `json:"lim"`
}

func (q *Queries) ListMediaByKeyword(ctx context.Context, arg ListMediaByKeywordParams) ([]MediaItemCard, error) {
	rows, err := q.db.Query(ctx, listMediaByKeyword,
		arg.Keyword,
		arg.MediaType,
		arg.Sort,
		arg.Off,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MediaItemCard{}
	for rows.Next() {
		var i MediaItemCard
		if err := rows.Scan(
			&i.ID,
			&i.LibraryID,
			&i.MediaType,
			&i.Title,
			&i.SortTitle,
			&i.Year,
			&i.Description,
			&i.PosterPath,
			&i.BackdropPath,
			&i.ExternalIds,
			&i.Slug,
			&i.Homepage,
			&i.Tagline,
			&i.OriginalTitle,
			&i.OriginalLanguage,
			&i.Status,
			&i.ProviderKind,
			&i.HeyaSlug,
			&i.HeyaEnrichedAt,
			&i.MetadataRefreshedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SearchVector,
			&i.MatchedAt,
			&i.EnrichmentStatus,
			&i.BaseEnrichedAt,
			&i.PeopleEnrichedAt,
			&i.ExtrasEnrichedAt,
			&i.ImagesEnrichedAt,
			&i.StructureEnrichedAt,
			&i.LastEnrichAttemptAt,
			&i.LastEnrichError,
			&i.FieldProvenance,
			&i.MatchConfidence,
			&i.SlugLocked,
			&i.PublicID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
