// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: heyametadata.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const clearMetadataWorkflowDiscovery = `-- name: ClearMetadataWorkflowDiscovery :exec
UPDATE metadata_resolution_workflows
SET discovery_id = NULL,
    state = 'pending',
    last_error = '',
    updated_at = now()
WHERE request_key = $1
`

func (q *Queries) ClearMetadataWorkflowDiscovery(ctx context.Context, requestKey string) error {
	_, err := q.db.Exec(ctx, clearMetadataWorkflowDiscovery, requestKey)
	return err
}

const commitMetadataChangeCursor = `-- name: CommitMetadataChangeCursor :exec
INSERT INTO metadata_change_consumers (consumer, next_cursor, stream_id)
VALUES ($1, $2, $3)
ON CONFLICT (consumer) DO UPDATE SET
  next_cursor = CASE
    WHEN metadata_change_consumers.stream_id IS NOT DISTINCT FROM EXCLUDED.stream_id
      THEN GREATEST(metadata_change_consumers.next_cursor, EXCLUDED.next_cursor)
    ELSE EXCLUDED.next_cursor
  END,
  stream_id = EXCLUDED.stream_id,
  updated_at = now()
`

type CommitMetadataChangeCursorParams struct {
	Consumer   string      `json:"consumer"`
	NextCursor int64       `json:"next_cursor"`
	StreamID   pgtype.UUID `json:"stream_id"`
}

func (q *Queries) CommitMetadataChangeCursor(ctx context.Context, arg CommitMetadataChangeCursorParams) error {
	_, err := q.db.Exec(ctx, commitMetadataChangeCursor, arg.Consumer, arg.NextCursor, arg.StreamID)
	return err
}

const completeMetadataWorkflow = `-- name: CompleteMetadataWorkflow :one
UPDATE metadata_resolution_workflows
SET entity_id = $2,
    state = 'completed',
    last_error = '',
    completed_at = now(),
    updated_at = now()
WHERE request_key = $1
RETURNING id, request_key, identity_id, kind, query, hints, selected_resolution, discovery_id, job_id, entity_id, state, last_error, created_at, updated_at, completed_at
`

type CompleteMetadataWorkflowParams struct {
	RequestKey string      `json:"request_key"`
	EntityID   pgtype.UUID `json:"entity_id"`
}

func (q *Queries) CompleteMetadataWorkflow(ctx context.Context, arg CompleteMetadataWorkflowParams) (MetadataResolutionWorkflow, error) {
	row := q.db.QueryRow(ctx, completeMetadataWorkflow, arg.RequestKey, arg.EntityID)
	var i MetadataResolutionWorkflow
	err := row.Scan(
		&i.ID,
		&i.RequestKey,
		&i.IdentityID,
		&i.Kind,
		&i.Query,
		&i.Hints,
		&i.SelectedResolution,
		&i.DiscoveryID,
		&i.JobID,
		&i.EntityID,
		&i.State,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const failMetadataWorkflow = `-- name: FailMetadataWorkflow :one
UPDATE metadata_resolution_workflows
SET state = 'failed',
    last_error = $2,
    updated_at = now()
WHERE request_key = $1
RETURNING id, request_key, identity_id, kind, query, hints, selected_resolution, discovery_id, job_id, entity_id, state, last_error, created_at, updated_at, completed_at
`

type FailMetadataWorkflowParams struct {
	RequestKey string `json:"request_key"`
	LastError  string `json:"last_error"`
}

func (q *Queries) FailMetadataWorkflow(ctx context.Context, arg FailMetadataWorkflowParams) (MetadataResolutionWorkflow, error) {
	row := q.db.QueryRow(ctx, failMetadataWorkflow, arg.RequestKey, arg.LastError)
	var i MetadataResolutionWorkflow
	err := row.Scan(
		&i.ID,
		&i.RequestKey,
		&i.IdentityID,
		&i.Kind,
		&i.Query,
		&i.Hints,
		&i.SelectedResolution,
		&i.DiscoveryID,
		&i.JobID,
		&i.EntityID,
		&i.State,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const getMediaItemMetadataBinding = `-- name: GetMediaItemMetadataBinding :one
SELECT local_kind, local_id, entity_id, entity_kind, schema_version, projection_version, bound_at, updated_at
FROM metadata_entity_bindings
WHERE local_kind = 'media_item' AND local_id = $1
`

func (q *Queries) GetMediaItemMetadataBinding(ctx context.Context, localID int64) (MetadataEntityBinding, error) {
	row := q.db.QueryRow(ctx, getMediaItemMetadataBinding, localID)
	var i MetadataEntityBinding
	err := row.Scan(
		&i.LocalKind,
		&i.LocalID,
		&i.EntityID,
		&i.EntityKind,
		&i.SchemaVersion,
		&i.ProjectionVersion,
		&i.BoundAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMetadataChangeCursor = `-- name: GetMetadataChangeCursor :one
SELECT next_cursor, stream_id
FROM metadata_change_consumers
WHERE consumer = $1
`

type GetMetadataChangeCursorRow struct {
	NextCursor int64       `json:"next_cursor"`
	StreamID   pgtype.UUID `json:"stream_id"`
}

func (q *Queries) GetMetadataChangeCursor(ctx context.Context, consumer string) (GetMetadataChangeCursorRow, error) {
	row := q.db.QueryRow(ctx, getMetadataChangeCursor, consumer)
	var i GetMetadataChangeCursorRow
	err := row.Scan(&i.NextCursor, &i.StreamID)
	return i, err
}

const getMetadataEntityBinding = `-- name: GetMetadataEntityBinding :one
SELECT local_kind, local_id, entity_id, entity_kind, schema_version, projection_version, bound_at, updated_at
FROM metadata_entity_bindings
WHERE local_kind = $1 AND local_id = $2
`

type GetMetadataEntityBindingParams struct {
	LocalKind string `json:"local_kind"`
	LocalID   int64  `json:"local_id"`
}

func (q *Queries) GetMetadataEntityBinding(ctx context.Context, arg GetMetadataEntityBindingParams) (MetadataEntityBinding, error) {
	row := q.db.QueryRow(ctx, getMetadataEntityBinding, arg.LocalKind, arg.LocalID)
	var i MetadataEntityBinding
	err := row.Scan(
		&i.LocalKind,
		&i.LocalID,
		&i.EntityID,
		&i.EntityKind,
		&i.SchemaVersion,
		&i.ProjectionVersion,
		&i.BoundAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMetadataWorkflowByKey = `-- name: GetMetadataWorkflowByKey :one
SELECT id, request_key, identity_id, kind, query, hints, selected_resolution, discovery_id, job_id, entity_id, state, last_error, created_at, updated_at, completed_at
FROM metadata_resolution_workflows
WHERE request_key = $1
`

func (q *Queries) GetMetadataWorkflowByKey(ctx context.Context, requestKey string) (MetadataResolutionWorkflow, error) {
	row := q.db.QueryRow(ctx, getMetadataWorkflowByKey, requestKey)
	var i MetadataResolutionWorkflow
	err := row.Scan(
		&i.ID,
		&i.RequestKey,
		&i.IdentityID,
		&i.Kind,
		&i.Query,
		&i.Hints,
		&i.SelectedResolution,
		&i.DiscoveryID,
		&i.JobID,
		&i.EntityID,
		&i.State,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const listMetadataBindingsByEntity = `-- name: ListMetadataBindingsByEntity :many
SELECT local_kind, local_id, entity_id, entity_kind, schema_version, projection_version, bound_at, updated_at
FROM metadata_entity_bindings
WHERE entity_id = $1
ORDER BY local_kind, local_id
`

func (q *Queries) ListMetadataBindingsByEntity(ctx context.Context, entityID uuid.UUID) ([]MetadataEntityBinding, error) {
	rows, err := q.db.Query(ctx, listMetadataBindingsByEntity, entityID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MetadataEntityBinding{}
	for rows.Next() {
		var i MetadataEntityBinding
		if err := rows.Scan(
			&i.LocalKind,
			&i.LocalID,
			&i.EntityID,
			&i.EntityKind,
			&i.SchemaVersion,
			&i.ProjectionVersion,
			&i.BoundAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMetadataBindingsByLocalIDs = `-- name: ListMetadataBindingsByLocalIDs :many
SELECT local_kind, local_id, entity_id, entity_kind, schema_version, projection_version, bound_at, updated_at
FROM metadata_entity_bindings
WHERE local_kind = $1 AND local_id = ANY($2::bigint[])
ORDER BY local_id
`

type ListMetadataBindingsByLocalIDsParams struct {
	LocalKind string  `json:"local_kind"`
	Column2   []int64 `json:"column_2"`
}

func (q *Queries) ListMetadataBindingsByLocalIDs(ctx context.Context, arg ListMetadataBindingsByLocalIDsParams) ([]MetadataEntityBinding, error) {
	rows, err := q.db.Query(ctx, listMetadataBindingsByLocalIDs, arg.LocalKind, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MetadataEntityBinding{}
	for rows.Next() {
		var i MetadataEntityBinding
		if err := rows.Scan(
			&i.LocalKind,
			&i.LocalID,
			&i.EntityID,
			&i.EntityKind,
			&i.SchemaVersion,
			&i.ProjectionVersion,
			&i.BoundAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMetadataChangeTargetsByEntities = `-- name: ListMetadataChangeTargetsByEntities :many
WITH bindings AS (
  SELECT entity_id, local_kind, local_id, projection_version
  FROM metadata_entity_bindings
  WHERE entity_id = ANY($1::uuid[])
)
SELECT entity_id, projection_version, 'person'::text AS target_kind, local_id AS target_id
FROM bindings
WHERE local_kind = 'person'
UNION ALL
SELECT entity_id, projection_version, 'media_item', local_id
FROM bindings
WHERE local_kind = 'media_item'
UNION ALL
SELECT binding.entity_id, binding.projection_version, 'media_item', artist.media_item_id
FROM bindings binding JOIN artists artist ON binding.local_kind = 'artist' AND artist.id = binding.local_id
UNION ALL
SELECT binding.entity_id, binding.projection_version, 'media_item', artist.media_item_id
FROM bindings binding
JOIN albums album ON binding.local_kind = 'album' AND album.id = binding.local_id
JOIN artists artist ON artist.id = album.artist_id
UNION ALL
SELECT binding.entity_id, binding.projection_version, 'media_item', artist.media_item_id
FROM bindings binding
JOIN tracks track ON binding.local_kind = 'track' AND track.id = binding.local_id
JOIN albums album ON album.id = track.album_id
JOIN artists artist ON artist.id = album.artist_id
UNION ALL
SELECT binding.entity_id, binding.projection_version, 'media_item', series.media_item_id
FROM bindings binding
JOIN tv_seasons season ON binding.local_kind = 'tv_season' AND season.id = binding.local_id
JOIN tv_series series ON series.id = season.series_id
UNION ALL
SELECT binding.entity_id, binding.projection_version, 'media_item', series.media_item_id
FROM bindings binding
JOIN tv_episodes episode ON binding.local_kind = 'tv_episode' AND episode.id = binding.local_id
JOIN tv_seasons season ON season.id = episode.season_id
JOIN tv_series series ON series.id = season.series_id
UNION ALL
SELECT binding.entity_id, binding.projection_version, 'media_item', book.media_item_id
FROM bindings binding
JOIN books book ON binding.local_kind = 'author' AND book.author_id = binding.local_id
ORDER BY entity_id, target_kind, target_id
`

type ListMetadataChangeTargetsByEntitiesRow struct {
	EntityID          uuid.UUID `json:"entity_id"`
	ProjectionVersion int64     `json:"projection_version"`
	TargetKind        string    `json:"target_kind"`
	TargetID          int64     `json:"target_id"`
}

// Resolve a complete change-feed page to refresh targets in one round trip.
// One canonical author may own multiple local books, hence UNION ALL rather
// than a scalar CASE. The worker deduplicates final target IDs across pages.
func (q *Queries) ListMetadataChangeTargetsByEntities(ctx context.Context, entityIds []uuid.UUID) ([]ListMetadataChangeTargetsByEntitiesRow, error) {
	rows, err := q.db.Query(ctx, listMetadataChangeTargetsByEntities, entityIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMetadataChangeTargetsByEntitiesRow{}
	for rows.Next() {
		var i ListMetadataChangeTargetsByEntitiesRow
		if err := rows.Scan(
			&i.EntityID,
			&i.ProjectionVersion,
			&i.TargetKind,
			&i.TargetID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markMetadataWorkflowDiscovery = `-- name: MarkMetadataWorkflowDiscovery :one
UPDATE metadata_resolution_workflows
SET discovery_id = $2,
    state = $3,
    last_error = '',
    updated_at = now()
WHERE request_key = $1
RETURNING id, request_key, identity_id, kind, query, hints, selected_resolution, discovery_id, job_id, entity_id, state, last_error, created_at, updated_at, completed_at
`

type MarkMetadataWorkflowDiscoveryParams struct {
	RequestKey  string      `json:"request_key"`
	DiscoveryID pgtype.UUID `json:"discovery_id"`
	State       string      `json:"state"`
}

func (q *Queries) MarkMetadataWorkflowDiscovery(ctx context.Context, arg MarkMetadataWorkflowDiscoveryParams) (MetadataResolutionWorkflow, error) {
	row := q.db.QueryRow(ctx, markMetadataWorkflowDiscovery, arg.RequestKey, arg.DiscoveryID, arg.State)
	var i MetadataResolutionWorkflow
	err := row.Scan(
		&i.ID,
		&i.RequestKey,
		&i.IdentityID,
		&i.Kind,
		&i.Query,
		&i.Hints,
		&i.SelectedResolution,
		&i.DiscoveryID,
		&i.JobID,
		&i.EntityID,
		&i.State,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const markMetadataWorkflowResolving = `-- name: MarkMetadataWorkflowResolving :one
UPDATE metadata_resolution_workflows
SET selected_resolution = $2,
    job_id = $3,
    state = 'resolving',
    last_error = '',
    updated_at = now()
WHERE request_key = $1
RETURNING id, request_key, identity_id, kind, query, hints, selected_resolution, discovery_id, job_id, entity_id, state, last_error, created_at, updated_at, completed_at
`

type MarkMetadataWorkflowResolvingParams struct {
	RequestKey         string      `json:"request_key"`
	SelectedResolution []byte      `json:"selected_resolution"`
	JobID              pgtype.Int8 `json:"job_id"`
}

func (q *Queries) MarkMetadataWorkflowResolving(ctx context.Context, arg MarkMetadataWorkflowResolvingParams) (MetadataResolutionWorkflow, error) {
	row := q.db.QueryRow(ctx, markMetadataWorkflowResolving, arg.RequestKey, arg.SelectedResolution, arg.JobID)
	var i MetadataResolutionWorkflow
	err := row.Scan(
		&i.ID,
		&i.RequestKey,
		&i.IdentityID,
		&i.Kind,
		&i.Query,
		&i.Hints,
		&i.SelectedResolution,
		&i.DiscoveryID,
		&i.JobID,
		&i.EntityID,
		&i.State,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const promoteCanonicalMetadataProviderID = `-- name: PromoteCanonicalMetadataProviderID :exec
UPDATE local_media_identities
SET metadata_provider_id = $2,
    updated_at = now()
WHERE media_item_id = $1
  AND metadata_provider_id IS DISTINCT FROM $2
`

type PromoteCanonicalMetadataProviderIDParams struct {
	MediaItemID        pgtype.Int8 `json:"media_item_id"`
	MetadataProviderID string      `json:"metadata_provider_id"`
}

func (q *Queries) PromoteCanonicalMetadataProviderID(ctx context.Context, arg PromoteCanonicalMetadataProviderIDParams) error {
	_, err := q.db.Exec(ctx, promoteCanonicalMetadataProviderID, arg.MediaItemID, arg.MetadataProviderID)
	return err
}

const resetMetadataChangeCursor = `-- name: ResetMetadataChangeCursor :exec
INSERT INTO metadata_change_consumers (consumer, next_cursor, stream_id)
VALUES ($1, 0, $2)
ON CONFLICT (consumer) DO UPDATE SET
  next_cursor = 0,
  stream_id = EXCLUDED.stream_id,
  updated_at = now()
`

type ResetMetadataChangeCursorParams struct {
	Consumer string      `json:"consumer"`
	StreamID pgtype.UUID `json:"stream_id"`
}

func (q *Queries) ResetMetadataChangeCursor(ctx context.Context, arg ResetMetadataChangeCursorParams) error {
	_, err := q.db.Exec(ctx, resetMetadataChangeCursor, arg.Consumer, arg.StreamID)
	return err
}

const upsertMetadataEntityBinding = `-- name: UpsertMetadataEntityBinding :one
INSERT INTO metadata_entity_bindings (
  local_kind, local_id, entity_id, entity_kind, schema_version, projection_version
) VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (local_kind, local_id) DO UPDATE SET
  entity_id = EXCLUDED.entity_id,
  entity_kind = EXCLUDED.entity_kind,
  schema_version = EXCLUDED.schema_version,
  projection_version = CASE
    WHEN metadata_entity_bindings.entity_id = EXCLUDED.entity_id
      THEN GREATEST(metadata_entity_bindings.projection_version, EXCLUDED.projection_version)
    ELSE EXCLUDED.projection_version
  END,
  updated_at = now()
RETURNING local_kind, local_id, entity_id, entity_kind, schema_version, projection_version, bound_at, updated_at
`

type UpsertMetadataEntityBindingParams struct {
	LocalKind         string    `json:"local_kind"`
	LocalID           int64     `json:"local_id"`
	EntityID          uuid.UUID `json:"entity_id"`
	EntityKind        string    `json:"entity_kind"`
	SchemaVersion     int32     `json:"schema_version"`
	ProjectionVersion int64     `json:"projection_version"`
}

func (q *Queries) UpsertMetadataEntityBinding(ctx context.Context, arg UpsertMetadataEntityBindingParams) (MetadataEntityBinding, error) {
	row := q.db.QueryRow(ctx, upsertMetadataEntityBinding,
		arg.LocalKind,
		arg.LocalID,
		arg.EntityID,
		arg.EntityKind,
		arg.SchemaVersion,
		arg.ProjectionVersion,
	)
	var i MetadataEntityBinding
	err := row.Scan(
		&i.LocalKind,
		&i.LocalID,
		&i.EntityID,
		&i.EntityKind,
		&i.SchemaVersion,
		&i.ProjectionVersion,
		&i.BoundAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertMetadataEntityBindings = `-- name: UpsertMetadataEntityBindings :exec
WITH input AS MATERIALIZED (
  SELECT COALESCE(value->>'local_kind', '') AS local_kind,
         (value->>'local_id')::bigint AS local_id,
         (value->>'entity_id')::uuid AS entity_id,
         COALESCE(value->>'entity_kind', '') AS entity_kind,
         COALESCE((value->>'schema_version')::integer, 1) AS schema_version,
         COALESCE((value->>'projection_version')::bigint, 0) AS projection_version
  FROM jsonb_array_elements($1::jsonb) AS value
)
INSERT INTO metadata_entity_bindings (
  local_kind, local_id, entity_id, entity_kind, schema_version, projection_version
)
SELECT local_kind, local_id, entity_id, entity_kind, schema_version, projection_version
FROM input
ON CONFLICT (local_kind, local_id) DO UPDATE SET
  entity_id = EXCLUDED.entity_id,
  entity_kind = EXCLUDED.entity_kind,
  schema_version = EXCLUDED.schema_version,
  projection_version = CASE
    WHEN metadata_entity_bindings.entity_id = EXCLUDED.entity_id
      THEN GREATEST(metadata_entity_bindings.projection_version, EXCLUDED.projection_version)
    ELSE EXCLUDED.projection_version
  END,
  updated_at = now()
`

// Batch canonical bindings created while materializing rich metadata. One
// local row can only bind to one canonical entity; a changed entity resets the
// projection version while a refresh of the same entity advances it.
func (q *Queries) UpsertMetadataEntityBindings(ctx context.Context, bindings []byte) error {
	_, err := q.db.Exec(ctx, upsertMetadataEntityBindings, bindings)
	return err
}

const upsertMetadataWorkflow = `-- name: UpsertMetadataWorkflow :one
INSERT INTO metadata_resolution_workflows (
  request_key, identity_id, kind, query, hints, selected_resolution, state
) VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (request_key) DO UPDATE SET
  identity_id = COALESCE(EXCLUDED.identity_id, metadata_resolution_workflows.identity_id),
  query = CASE WHEN EXCLUDED.query <> '' THEN EXCLUDED.query ELSE metadata_resolution_workflows.query END,
  hints = CASE WHEN EXCLUDED.hints <> '{}'::jsonb THEN EXCLUDED.hints ELSE metadata_resolution_workflows.hints END,
  selected_resolution = CASE WHEN EXCLUDED.selected_resolution <> '{}'::jsonb THEN EXCLUDED.selected_resolution ELSE metadata_resolution_workflows.selected_resolution END,
  updated_at = now()
RETURNING id, request_key, identity_id, kind, query, hints, selected_resolution, discovery_id, job_id, entity_id, state, last_error, created_at, updated_at, completed_at
`

type UpsertMetadataWorkflowParams struct {
	RequestKey         string      `json:"request_key"`
	IdentityID         pgtype.Int8 `json:"identity_id"`
	Kind               string      `json:"kind"`
	Query              string      `json:"query"`
	Hints              []byte      `json:"hints"`
	SelectedResolution []byte      `json:"selected_resolution"`
	State              string      `json:"state"`
}

func (q *Queries) UpsertMetadataWorkflow(ctx context.Context, arg UpsertMetadataWorkflowParams) (MetadataResolutionWorkflow, error) {
	row := q.db.QueryRow(ctx, upsertMetadataWorkflow,
		arg.RequestKey,
		arg.IdentityID,
		arg.Kind,
		arg.Query,
		arg.Hints,
		arg.SelectedResolution,
		arg.State,
	)
	var i MetadataResolutionWorkflow
	err := row.Scan(
		&i.ID,
		&i.RequestKey,
		&i.IdentityID,
		&i.Kind,
		&i.Query,
		&i.Hints,
		&i.SelectedResolution,
		&i.DiscoveryID,
		&i.JobID,
		&i.EntityID,
		&i.State,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return i, err
}
