// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: manager.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countMediaItemsByQualityProfile = `-- name: CountMediaItemsByQualityProfile :one
SELECT count(*) FROM media_items WHERE quality_profile_id = $1
`

func (q *Queries) CountMediaItemsByQualityProfile(ctx context.Context, qualityProfileID pgtype.Int8) (int64, error) {
	row := q.db.QueryRow(ctx, countMediaItemsByQualityProfile, qualityProfileID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createManagerDownloadClient = `-- name: CreateManagerDownloadClient :one
INSERT INTO manager_download_clients (name, kind, enabled, protocol, base_url, api_key, username, password, category, priority, path_mappings, settings)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
RETURNING id, name, kind, enabled, protocol, base_url, api_key, username, password, category, priority, path_mappings, settings, last_test_at, last_test_ok, last_test_error, created_at, updated_at
`

type CreateManagerDownloadClientParams struct {
	Name         string `json:"name"`
	Kind         string `json:"kind"`
	Enabled      bool   `json:"enabled"`
	Protocol     string `json:"protocol"`
	BaseUrl      string `json:"base_url"`
	ApiKey       string `json:"api_key"`
	Username     string `json:"username"`
	Password     string `json:"password"`
	Category     string `json:"category"`
	Priority     int32  `json:"priority"`
	PathMappings []byte `json:"path_mappings"`
	Settings     []byte `json:"settings"`
}

func (q *Queries) CreateManagerDownloadClient(ctx context.Context, arg CreateManagerDownloadClientParams) (ManagerDownloadClient, error) {
	row := q.db.QueryRow(ctx, createManagerDownloadClient,
		arg.Name,
		arg.Kind,
		arg.Enabled,
		arg.Protocol,
		arg.BaseUrl,
		arg.ApiKey,
		arg.Username,
		arg.Password,
		arg.Category,
		arg.Priority,
		arg.PathMappings,
		arg.Settings,
	)
	var i ManagerDownloadClient
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Kind,
		&i.Enabled,
		&i.Protocol,
		&i.BaseUrl,
		&i.ApiKey,
		&i.Username,
		&i.Password,
		&i.Category,
		&i.Priority,
		&i.PathMappings,
		&i.Settings,
		&i.LastTestAt,
		&i.LastTestOk,
		&i.LastTestError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createManagerIndexer = `-- name: CreateManagerIndexer :one
INSERT INTO manager_indexers (name, kind, enabled, base_url, api_key, protocol, priority, categories, source, source_ref, parent_id, settings)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
RETURNING id, name, kind, enabled, base_url, api_key, protocol, priority, categories, source, source_ref, parent_id, settings, last_test_at, last_test_ok, last_test_error, created_at, updated_at
`

type CreateManagerIndexerParams struct {
	Name       string      `json:"name"`
	Kind       string      `json:"kind"`
	Enabled    bool        `json:"enabled"`
	BaseUrl    string      `json:"base_url"`
	ApiKey     string      `json:"api_key"`
	Protocol   string      `json:"protocol"`
	Priority   int32       `json:"priority"`
	Categories []int32     `json:"categories"`
	Source     string      `json:"source"`
	SourceRef  string      `json:"source_ref"`
	ParentID   pgtype.Int8 `json:"parent_id"`
	Settings   []byte      `json:"settings"`
}

func (q *Queries) CreateManagerIndexer(ctx context.Context, arg CreateManagerIndexerParams) (ManagerIndexer, error) {
	row := q.db.QueryRow(ctx, createManagerIndexer,
		arg.Name,
		arg.Kind,
		arg.Enabled,
		arg.BaseUrl,
		arg.ApiKey,
		arg.Protocol,
		arg.Priority,
		arg.Categories,
		arg.Source,
		arg.SourceRef,
		arg.ParentID,
		arg.Settings,
	)
	var i ManagerIndexer
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Kind,
		&i.Enabled,
		&i.BaseUrl,
		&i.ApiKey,
		&i.Protocol,
		&i.Priority,
		&i.Categories,
		&i.Source,
		&i.SourceRef,
		&i.ParentID,
		&i.Settings,
		&i.LastTestAt,
		&i.LastTestOk,
		&i.LastTestError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createManagerQualityProfile = `-- name: CreateManagerQualityProfile :one
INSERT INTO manager_quality_profiles (name, domain, items, cutoff, upgrades_enabled)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, name, domain, items, cutoff, upgrades_enabled, created_at, updated_at
`

type CreateManagerQualityProfileParams struct {
	Name            string `json:"name"`
	Domain          string `json:"domain"`
	Items           []byte `json:"items"`
	Cutoff          string `json:"cutoff"`
	UpgradesEnabled bool   `json:"upgrades_enabled"`
}

func (q *Queries) CreateManagerQualityProfile(ctx context.Context, arg CreateManagerQualityProfileParams) (ManagerQualityProfile, error) {
	row := q.db.QueryRow(ctx, createManagerQualityProfile,
		arg.Name,
		arg.Domain,
		arg.Items,
		arg.Cutoff,
		arg.UpgradesEnabled,
	)
	var i ManagerQualityProfile
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Domain,
		&i.Items,
		&i.Cutoff,
		&i.UpgradesEnabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteManagerDownloadClient = `-- name: DeleteManagerDownloadClient :exec
DELETE FROM manager_download_clients WHERE id = $1
`

func (q *Queries) DeleteManagerDownloadClient(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteManagerDownloadClient, id)
	return err
}

const deleteManagerIndexer = `-- name: DeleteManagerIndexer :exec
DELETE FROM manager_indexers WHERE id = $1
`

func (q *Queries) DeleteManagerIndexer(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteManagerIndexer, id)
	return err
}

const deleteManagerQualityProfile = `-- name: DeleteManagerQualityProfile :exec
DELETE FROM manager_quality_profiles WHERE id = $1
`

func (q *Queries) DeleteManagerQualityProfile(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteManagerQualityProfile, id)
	return err
}

const deleteStaleManagerIndexerChildren = `-- name: DeleteStaleManagerIndexerChildren :exec
DELETE FROM manager_indexers
WHERE parent_id = $1 AND NOT (source_ref = ANY($2::text[]))
`

type DeleteStaleManagerIndexerChildrenParams struct {
	ParentID pgtype.Int8 `json:"parent_id"`
	KeepRefs []string    `json:"keep_refs"`
}

func (q *Queries) DeleteStaleManagerIndexerChildren(ctx context.Context, arg DeleteStaleManagerIndexerChildrenParams) error {
	_, err := q.db.Exec(ctx, deleteStaleManagerIndexerChildren, arg.ParentID, arg.KeepRefs)
	return err
}

const getManagerDownloadClient = `-- name: GetManagerDownloadClient :one
SELECT id, name, kind, enabled, protocol, base_url, api_key, username, password, category, priority, path_mappings, settings, last_test_at, last_test_ok, last_test_error, created_at, updated_at FROM manager_download_clients WHERE id = $1
`

func (q *Queries) GetManagerDownloadClient(ctx context.Context, id int64) (ManagerDownloadClient, error) {
	row := q.db.QueryRow(ctx, getManagerDownloadClient, id)
	var i ManagerDownloadClient
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Kind,
		&i.Enabled,
		&i.Protocol,
		&i.BaseUrl,
		&i.ApiKey,
		&i.Username,
		&i.Password,
		&i.Category,
		&i.Priority,
		&i.PathMappings,
		&i.Settings,
		&i.LastTestAt,
		&i.LastTestOk,
		&i.LastTestError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getManagerIndexer = `-- name: GetManagerIndexer :one
SELECT id, name, kind, enabled, base_url, api_key, protocol, priority, categories, source, source_ref, parent_id, settings, last_test_at, last_test_ok, last_test_error, created_at, updated_at FROM manager_indexers WHERE id = $1
`

func (q *Queries) GetManagerIndexer(ctx context.Context, id int64) (ManagerIndexer, error) {
	row := q.db.QueryRow(ctx, getManagerIndexer, id)
	var i ManagerIndexer
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Kind,
		&i.Enabled,
		&i.BaseUrl,
		&i.ApiKey,
		&i.Protocol,
		&i.Priority,
		&i.Categories,
		&i.Source,
		&i.SourceRef,
		&i.ParentID,
		&i.Settings,
		&i.LastTestAt,
		&i.LastTestOk,
		&i.LastTestError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getManagerQualityProfile = `-- name: GetManagerQualityProfile :one
SELECT id, name, domain, items, cutoff, upgrades_enabled, created_at, updated_at FROM manager_quality_profiles WHERE id = $1
`

func (q *Queries) GetManagerQualityProfile(ctx context.Context, id int64) (ManagerQualityProfile, error) {
	row := q.db.QueryRow(ctx, getManagerQualityProfile, id)
	var i ManagerQualityProfile
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Domain,
		&i.Items,
		&i.Cutoff,
		&i.UpgradesEnabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listManagerDownloadClients = `-- name: ListManagerDownloadClients :many
SELECT id, name, kind, enabled, protocol, base_url, api_key, username, password, category, priority, path_mappings, settings, last_test_at, last_test_ok, last_test_error, created_at, updated_at FROM manager_download_clients ORDER BY priority ASC, name ASC
`

func (q *Queries) ListManagerDownloadClients(ctx context.Context) ([]ManagerDownloadClient, error) {
	rows, err := q.db.Query(ctx, listManagerDownloadClients)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ManagerDownloadClient{}
	for rows.Next() {
		var i ManagerDownloadClient
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Kind,
			&i.Enabled,
			&i.Protocol,
			&i.BaseUrl,
			&i.ApiKey,
			&i.Username,
			&i.Password,
			&i.Category,
			&i.Priority,
			&i.PathMappings,
			&i.Settings,
			&i.LastTestAt,
			&i.LastTestOk,
			&i.LastTestError,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listManagerIndexers = `-- name: ListManagerIndexers :many

SELECT id, name, kind, enabled, base_url, api_key, protocol, priority, categories, source, source_ref, parent_id, settings, last_test_at, last_test_ok, last_test_error, created_at, updated_at FROM manager_indexers ORDER BY parent_id NULLS FIRST, priority ASC, name ASC
`

// Heya Media Manager: indexers, download clients, quality profiles.
func (q *Queries) ListManagerIndexers(ctx context.Context) ([]ManagerIndexer, error) {
	rows, err := q.db.Query(ctx, listManagerIndexers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ManagerIndexer{}
	for rows.Next() {
		var i ManagerIndexer
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Kind,
			&i.Enabled,
			&i.BaseUrl,
			&i.ApiKey,
			&i.Protocol,
			&i.Priority,
			&i.Categories,
			&i.Source,
			&i.SourceRef,
			&i.ParentID,
			&i.Settings,
			&i.LastTestAt,
			&i.LastTestOk,
			&i.LastTestError,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listManagerQualityProfiles = `-- name: ListManagerQualityProfiles :many
SELECT id, name, domain, items, cutoff, upgrades_enabled, created_at, updated_at FROM manager_quality_profiles ORDER BY domain ASC, name ASC
`

func (q *Queries) ListManagerQualityProfiles(ctx context.Context) ([]ManagerQualityProfile, error) {
	rows, err := q.db.Query(ctx, listManagerQualityProfiles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ManagerQualityProfile{}
	for rows.Next() {
		var i ManagerQualityProfile
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Domain,
			&i.Items,
			&i.Cutoff,
			&i.UpgradesEnabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setManagerDownloadClientTestResult = `-- name: SetManagerDownloadClientTestResult :exec
UPDATE manager_download_clients
SET last_test_at = now(), last_test_ok = $2, last_test_error = $3, updated_at = now()
WHERE id = $1
`

type SetManagerDownloadClientTestResultParams struct {
	ID            int64  `json:"id"`
	LastTestOk    bool   `json:"last_test_ok"`
	LastTestError string `json:"last_test_error"`
}

func (q *Queries) SetManagerDownloadClientTestResult(ctx context.Context, arg SetManagerDownloadClientTestResultParams) error {
	_, err := q.db.Exec(ctx, setManagerDownloadClientTestResult, arg.ID, arg.LastTestOk, arg.LastTestError)
	return err
}

const setManagerIndexerTestResult = `-- name: SetManagerIndexerTestResult :exec
UPDATE manager_indexers
SET last_test_at = now(), last_test_ok = $2, last_test_error = $3, updated_at = now()
WHERE id = $1
`

type SetManagerIndexerTestResultParams struct {
	ID            int64  `json:"id"`
	LastTestOk    bool   `json:"last_test_ok"`
	LastTestError string `json:"last_test_error"`
}

func (q *Queries) SetManagerIndexerTestResult(ctx context.Context, arg SetManagerIndexerTestResultParams) error {
	_, err := q.db.Exec(ctx, setManagerIndexerTestResult, arg.ID, arg.LastTestOk, arg.LastTestError)
	return err
}

const updateManagerDownloadClient = `-- name: UpdateManagerDownloadClient :one
UPDATE manager_download_clients
SET name = $2, enabled = $3, base_url = $4, api_key = $5, username = $6,
    password = $7, category = $8, priority = $9, path_mappings = $10, updated_at = now()
WHERE id = $1
RETURNING id, name, kind, enabled, protocol, base_url, api_key, username, password, category, priority, path_mappings, settings, last_test_at, last_test_ok, last_test_error, created_at, updated_at
`

type UpdateManagerDownloadClientParams struct {
	ID           int64  `json:"id"`
	Name         string `json:"name"`
	Enabled      bool   `json:"enabled"`
	BaseUrl      string `json:"base_url"`
	ApiKey       string `json:"api_key"`
	Username     string `json:"username"`
	Password     string `json:"password"`
	Category     string `json:"category"`
	Priority     int32  `json:"priority"`
	PathMappings []byte `json:"path_mappings"`
}

func (q *Queries) UpdateManagerDownloadClient(ctx context.Context, arg UpdateManagerDownloadClientParams) (ManagerDownloadClient, error) {
	row := q.db.QueryRow(ctx, updateManagerDownloadClient,
		arg.ID,
		arg.Name,
		arg.Enabled,
		arg.BaseUrl,
		arg.ApiKey,
		arg.Username,
		arg.Password,
		arg.Category,
		arg.Priority,
		arg.PathMappings,
	)
	var i ManagerDownloadClient
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Kind,
		&i.Enabled,
		&i.Protocol,
		&i.BaseUrl,
		&i.ApiKey,
		&i.Username,
		&i.Password,
		&i.Category,
		&i.Priority,
		&i.PathMappings,
		&i.Settings,
		&i.LastTestAt,
		&i.LastTestOk,
		&i.LastTestError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateManagerIndexer = `-- name: UpdateManagerIndexer :one
UPDATE manager_indexers
SET name = $2, enabled = $3, base_url = $4, api_key = $5, protocol = $6,
    priority = $7, categories = $8, updated_at = now()
WHERE id = $1
RETURNING id, name, kind, enabled, base_url, api_key, protocol, priority, categories, source, source_ref, parent_id, settings, last_test_at, last_test_ok, last_test_error, created_at, updated_at
`

type UpdateManagerIndexerParams struct {
	ID         int64   `json:"id"`
	Name       string  `json:"name"`
	Enabled    bool    `json:"enabled"`
	BaseUrl    string  `json:"base_url"`
	ApiKey     string  `json:"api_key"`
	Protocol   string  `json:"protocol"`
	Priority   int32   `json:"priority"`
	Categories []int32 `json:"categories"`
}

func (q *Queries) UpdateManagerIndexer(ctx context.Context, arg UpdateManagerIndexerParams) (ManagerIndexer, error) {
	row := q.db.QueryRow(ctx, updateManagerIndexer,
		arg.ID,
		arg.Name,
		arg.Enabled,
		arg.BaseUrl,
		arg.ApiKey,
		arg.Protocol,
		arg.Priority,
		arg.Categories,
	)
	var i ManagerIndexer
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Kind,
		&i.Enabled,
		&i.BaseUrl,
		&i.ApiKey,
		&i.Protocol,
		&i.Priority,
		&i.Categories,
		&i.Source,
		&i.SourceRef,
		&i.ParentID,
		&i.Settings,
		&i.LastTestAt,
		&i.LastTestOk,
		&i.LastTestError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateManagerQualityProfile = `-- name: UpdateManagerQualityProfile :one
UPDATE manager_quality_profiles
SET name = $2, items = $3, cutoff = $4, upgrades_enabled = $5, updated_at = now()
WHERE id = $1
RETURNING id, name, domain, items, cutoff, upgrades_enabled, created_at, updated_at
`

type UpdateManagerQualityProfileParams struct {
	ID              int64  `json:"id"`
	Name            string `json:"name"`
	Items           []byte `json:"items"`
	Cutoff          string `json:"cutoff"`
	UpgradesEnabled bool   `json:"upgrades_enabled"`
}

func (q *Queries) UpdateManagerQualityProfile(ctx context.Context, arg UpdateManagerQualityProfileParams) (ManagerQualityProfile, error) {
	row := q.db.QueryRow(ctx, updateManagerQualityProfile,
		arg.ID,
		arg.Name,
		arg.Items,
		arg.Cutoff,
		arg.UpgradesEnabled,
	)
	var i ManagerQualityProfile
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Domain,
		&i.Items,
		&i.Cutoff,
		&i.UpgradesEnabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertManagerIndexerChild = `-- name: UpsertManagerIndexerChild :one
INSERT INTO manager_indexers (name, kind, enabled, base_url, api_key, protocol, priority, categories, source, source_ref, parent_id)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
ON CONFLICT (parent_id, source_ref) WHERE parent_id IS NOT NULL
DO UPDATE SET name = EXCLUDED.name, base_url = EXCLUDED.base_url,
    api_key = EXCLUDED.api_key, protocol = EXCLUDED.protocol,
    updated_at = now()
RETURNING id, name, kind, enabled, base_url, api_key, protocol, priority, categories, source, source_ref, parent_id, settings, last_test_at, last_test_ok, last_test_error, created_at, updated_at
`

type UpsertManagerIndexerChildParams struct {
	Name       string      `json:"name"`
	Kind       string      `json:"kind"`
	Enabled    bool        `json:"enabled"`
	BaseUrl    string      `json:"base_url"`
	ApiKey     string      `json:"api_key"`
	Protocol   string      `json:"protocol"`
	Priority   int32       `json:"priority"`
	Categories []int32     `json:"categories"`
	Source     string      `json:"source"`
	SourceRef  string      `json:"source_ref"`
	ParentID   pgtype.Int8 `json:"parent_id"`
}

// Sync from a Prowlarr app row: children are keyed by (parent_id, source_ref).
func (q *Queries) UpsertManagerIndexerChild(ctx context.Context, arg UpsertManagerIndexerChildParams) (ManagerIndexer, error) {
	row := q.db.QueryRow(ctx, upsertManagerIndexerChild,
		arg.Name,
		arg.Kind,
		arg.Enabled,
		arg.BaseUrl,
		arg.ApiKey,
		arg.Protocol,
		arg.Priority,
		arg.Categories,
		arg.Source,
		arg.SourceRef,
		arg.ParentID,
	)
	var i ManagerIndexer
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Kind,
		&i.Enabled,
		&i.BaseUrl,
		&i.ApiKey,
		&i.Protocol,
		&i.Priority,
		&i.Categories,
		&i.Source,
		&i.SourceRef,
		&i.ParentID,
		&i.Settings,
		&i.LastTestAt,
		&i.LastTestOk,
		&i.LastTestError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
