// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: media_items.sql

package sqlc

import (
	"context"
)

const countMediaItemsByLibrary = `-- name: CountMediaItemsByLibrary :one
SELECT count(*) FROM media_items WHERE library_id = $1
`

func (q *Queries) CountMediaItemsByLibrary(ctx context.Context, libraryID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countMediaItemsByLibrary, libraryID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countMediaItemsByType = `-- name: CountMediaItemsByType :one
SELECT count(*) FROM media_items WHERE media_type = $1
`

func (q *Queries) CountMediaItemsByType(ctx context.Context, mediaType MediaType) (int64, error) {
	row := q.db.QueryRow(ctx, countMediaItemsByType, mediaType)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createMediaItem = `-- name: CreateMediaItem :one
INSERT INTO media_items (library_id, media_type, title, sort_title, year, description, poster_path, backdrop_path, external_ids)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, library_id, media_type, title, sort_title, year, description, poster_path, backdrop_path, external_ids, created_at, updated_at, search_vector, homepage, wikidata_id, facebook_id, instagram_id, twitter_id, slug, metadata_refreshed_at
`

type CreateMediaItemParams struct {
	LibraryID    int64     `json:"library_id"`
	MediaType    MediaType `json:"media_type"`
	Title        string    `json:"title"`
	SortTitle    string    `json:"sort_title"`
	Year         string    `json:"year"`
	Description  string    `json:"description"`
	PosterPath   string    `json:"poster_path"`
	BackdropPath string    `json:"backdrop_path"`
	ExternalIds  []byte    `json:"external_ids"`
}

func (q *Queries) CreateMediaItem(ctx context.Context, arg CreateMediaItemParams) (MediaItem, error) {
	row := q.db.QueryRow(ctx, createMediaItem,
		arg.LibraryID,
		arg.MediaType,
		arg.Title,
		arg.SortTitle,
		arg.Year,
		arg.Description,
		arg.PosterPath,
		arg.BackdropPath,
		arg.ExternalIds,
	)
	var i MediaItem
	err := row.Scan(
		&i.ID,
		&i.LibraryID,
		&i.MediaType,
		&i.Title,
		&i.SortTitle,
		&i.Year,
		&i.Description,
		&i.PosterPath,
		&i.BackdropPath,
		&i.ExternalIds,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SearchVector,
		&i.Homepage,
		&i.WikidataID,
		&i.FacebookID,
		&i.InstagramID,
		&i.TwitterID,
		&i.Slug,
		&i.MetadataRefreshedAt,
	)
	return i, err
}

const deleteMediaItem = `-- name: DeleteMediaItem :exec
DELETE FROM media_items WHERE id = $1
`

func (q *Queries) DeleteMediaItem(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteMediaItem, id)
	return err
}

const getMediaItemByID = `-- name: GetMediaItemByID :one
SELECT id, library_id, media_type, title, sort_title, year, description, poster_path, backdrop_path, external_ids, created_at, updated_at, search_vector, homepage, wikidata_id, facebook_id, instagram_id, twitter_id, slug, metadata_refreshed_at FROM media_items WHERE id = $1
`

func (q *Queries) GetMediaItemByID(ctx context.Context, id int64) (MediaItem, error) {
	row := q.db.QueryRow(ctx, getMediaItemByID, id)
	var i MediaItem
	err := row.Scan(
		&i.ID,
		&i.LibraryID,
		&i.MediaType,
		&i.Title,
		&i.SortTitle,
		&i.Year,
		&i.Description,
		&i.PosterPath,
		&i.BackdropPath,
		&i.ExternalIds,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SearchVector,
		&i.Homepage,
		&i.WikidataID,
		&i.FacebookID,
		&i.InstagramID,
		&i.TwitterID,
		&i.Slug,
		&i.MetadataRefreshedAt,
	)
	return i, err
}

const getMediaItemBySlug = `-- name: GetMediaItemBySlug :one
SELECT id, library_id, media_type, title, sort_title, year, description, poster_path, backdrop_path, external_ids, created_at, updated_at, search_vector, homepage, wikidata_id, facebook_id, instagram_id, twitter_id, slug, metadata_refreshed_at FROM media_items WHERE slug = $1
`

func (q *Queries) GetMediaItemBySlug(ctx context.Context, slug string) (MediaItem, error) {
	row := q.db.QueryRow(ctx, getMediaItemBySlug, slug)
	var i MediaItem
	err := row.Scan(
		&i.ID,
		&i.LibraryID,
		&i.MediaType,
		&i.Title,
		&i.SortTitle,
		&i.Year,
		&i.Description,
		&i.PosterPath,
		&i.BackdropPath,
		&i.ExternalIds,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SearchVector,
		&i.Homepage,
		&i.WikidataID,
		&i.FacebookID,
		&i.InstagramID,
		&i.TwitterID,
		&i.Slug,
		&i.MetadataRefreshedAt,
	)
	return i, err
}

const listMediaItemsByLibrary = `-- name: ListMediaItemsByLibrary :many
SELECT id, library_id, media_type, title, sort_title, year, description, poster_path, backdrop_path, external_ids, created_at, updated_at, search_vector, homepage, wikidata_id, facebook_id, instagram_id, twitter_id, slug, metadata_refreshed_at FROM media_items
WHERE library_id = $1
ORDER BY sort_title ASC, title ASC
LIMIT $2 OFFSET $3
`

type ListMediaItemsByLibraryParams struct {
	LibraryID int64 `json:"library_id"`
	Limit     int32 `json:"limit"`
	Offset    int32 `json:"offset"`
}

func (q *Queries) ListMediaItemsByLibrary(ctx context.Context, arg ListMediaItemsByLibraryParams) ([]MediaItem, error) {
	rows, err := q.db.Query(ctx, listMediaItemsByLibrary, arg.LibraryID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MediaItem{}
	for rows.Next() {
		var i MediaItem
		if err := rows.Scan(
			&i.ID,
			&i.LibraryID,
			&i.MediaType,
			&i.Title,
			&i.SortTitle,
			&i.Year,
			&i.Description,
			&i.PosterPath,
			&i.BackdropPath,
			&i.ExternalIds,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SearchVector,
			&i.Homepage,
			&i.WikidataID,
			&i.FacebookID,
			&i.InstagramID,
			&i.TwitterID,
			&i.Slug,
			&i.MetadataRefreshedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMediaItemsByType = `-- name: ListMediaItemsByType :many
SELECT id, library_id, media_type, title, sort_title, year, description, poster_path, backdrop_path, external_ids, created_at, updated_at, search_vector, homepage, wikidata_id, facebook_id, instagram_id, twitter_id, slug, metadata_refreshed_at FROM media_items
WHERE media_type = $1
ORDER BY sort_title ASC, title ASC
LIMIT $2 OFFSET $3
`

type ListMediaItemsByTypeParams struct {
	MediaType MediaType `json:"media_type"`
	Limit     int32     `json:"limit"`
	Offset    int32     `json:"offset"`
}

func (q *Queries) ListMediaItemsByType(ctx context.Context, arg ListMediaItemsByTypeParams) ([]MediaItem, error) {
	rows, err := q.db.Query(ctx, listMediaItemsByType, arg.MediaType, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MediaItem{}
	for rows.Next() {
		var i MediaItem
		if err := rows.Scan(
			&i.ID,
			&i.LibraryID,
			&i.MediaType,
			&i.Title,
			&i.SortTitle,
			&i.Year,
			&i.Description,
			&i.PosterPath,
			&i.BackdropPath,
			&i.ExternalIds,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SearchVector,
			&i.Homepage,
			&i.WikidataID,
			&i.FacebookID,
			&i.InstagramID,
			&i.TwitterID,
			&i.Slug,
			&i.MetadataRefreshedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnavailableMediaItemIDs = `-- name: ListUnavailableMediaItemIDs :many
SELECT DISTINCT mi.id
FROM media_items mi
WHERE mi.media_type = $1
  AND NOT EXISTS (
    SELECT 1 FROM library_files lf
    WHERE lf.media_item_id = mi.id AND lf.deleted_at IS NULL
  )
`

func (q *Queries) ListUnavailableMediaItemIDs(ctx context.Context, mediaType MediaType) ([]int64, error) {
	rows, err := q.db.Query(ctx, listUnavailableMediaItemIDs, mediaType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markMetadataRefreshed = `-- name: MarkMetadataRefreshed :exec
UPDATE media_items SET metadata_refreshed_at = now() WHERE id = $1
`

func (q *Queries) MarkMetadataRefreshed(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, markMetadataRefreshed, id)
	return err
}

const mediaItemSlugExists = `-- name: MediaItemSlugExists :one
SELECT EXISTS(SELECT 1 FROM media_items WHERE slug = $1 AND id != $2) as exists
`

type MediaItemSlugExistsParams struct {
	Slug string `json:"slug"`
	ID   int64  `json:"id"`
}

func (q *Queries) MediaItemSlugExists(ctx context.Context, arg MediaItemSlugExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, mediaItemSlugExists, arg.Slug, arg.ID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const updateMediaItem = `-- name: UpdateMediaItem :one
UPDATE media_items
SET title = $2, sort_title = $3, year = $4, description = $5,
    poster_path = $6, backdrop_path = $7, external_ids = $8, updated_at = now()
WHERE id = $1
RETURNING id, library_id, media_type, title, sort_title, year, description, poster_path, backdrop_path, external_ids, created_at, updated_at, search_vector, homepage, wikidata_id, facebook_id, instagram_id, twitter_id, slug, metadata_refreshed_at
`

type UpdateMediaItemParams struct {
	ID           int64  `json:"id"`
	Title        string `json:"title"`
	SortTitle    string `json:"sort_title"`
	Year         string `json:"year"`
	Description  string `json:"description"`
	PosterPath   string `json:"poster_path"`
	BackdropPath string `json:"backdrop_path"`
	ExternalIds  []byte `json:"external_ids"`
}

func (q *Queries) UpdateMediaItem(ctx context.Context, arg UpdateMediaItemParams) (MediaItem, error) {
	row := q.db.QueryRow(ctx, updateMediaItem,
		arg.ID,
		arg.Title,
		arg.SortTitle,
		arg.Year,
		arg.Description,
		arg.PosterPath,
		arg.BackdropPath,
		arg.ExternalIds,
	)
	var i MediaItem
	err := row.Scan(
		&i.ID,
		&i.LibraryID,
		&i.MediaType,
		&i.Title,
		&i.SortTitle,
		&i.Year,
		&i.Description,
		&i.PosterPath,
		&i.BackdropPath,
		&i.ExternalIds,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SearchVector,
		&i.Homepage,
		&i.WikidataID,
		&i.FacebookID,
		&i.InstagramID,
		&i.TwitterID,
		&i.Slug,
		&i.MetadataRefreshedAt,
	)
	return i, err
}

const updateMediaItemSlug = `-- name: UpdateMediaItemSlug :exec
UPDATE media_items SET slug = $2 WHERE id = $1
`

type UpdateMediaItemSlugParams struct {
	ID   int64  `json:"id"`
	Slug string `json:"slug"`
}

func (q *Queries) UpdateMediaItemSlug(ctx context.Context, arg UpdateMediaItemSlugParams) error {
	_, err := q.db.Exec(ctx, updateMediaItemSlug, arg.ID, arg.Slug)
	return err
}
