// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: media_assets.sql

package sqlc

import (
	"context"
)

const countMediaAssetsByType = `-- name: CountMediaAssetsByType :many
SELECT asset_type, count(*) as count
FROM media_assets
WHERE media_item_id = $1
GROUP BY asset_type
`

type CountMediaAssetsByTypeRow struct {
	AssetType AssetType `json:"asset_type"`
	Count     int64     `json:"count"`
}

func (q *Queries) CountMediaAssetsByType(ctx context.Context, mediaItemID int64) ([]CountMediaAssetsByTypeRow, error) {
	rows, err := q.db.Query(ctx, countMediaAssetsByType, mediaItemID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountMediaAssetsByTypeRow{}
	for rows.Next() {
		var i CountMediaAssetsByTypeRow
		if err := rows.Scan(&i.AssetType, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createMediaAsset = `-- name: CreateMediaAsset :one
INSERT INTO media_assets (media_item_id, asset_type, source, local_path, remote_url, language, label, sort_order, width, height, file_size)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
ON CONFLICT DO NOTHING
RETURNING id, media_item_id, asset_type, source, local_path, remote_url, language, label, sort_order, width, height, file_size, score, likes, aspect, created_at
`

type CreateMediaAssetParams struct {
	MediaItemID int64     `json:"media_item_id"`
	AssetType   AssetType `json:"asset_type"`
	Source      string    `json:"source"`
	LocalPath   string    `json:"local_path"`
	RemoteUrl   string    `json:"remote_url"`
	Language    string    `json:"language"`
	Label       string    `json:"label"`
	SortOrder   int32     `json:"sort_order"`
	Width       int32     `json:"width"`
	Height      int32     `json:"height"`
	FileSize    int64     `json:"file_size"`
}

func (q *Queries) CreateMediaAsset(ctx context.Context, arg CreateMediaAssetParams) (MediaAsset, error) {
	row := q.db.QueryRow(ctx, createMediaAsset,
		arg.MediaItemID,
		arg.AssetType,
		arg.Source,
		arg.LocalPath,
		arg.RemoteUrl,
		arg.Language,
		arg.Label,
		arg.SortOrder,
		arg.Width,
		arg.Height,
		arg.FileSize,
	)
	var i MediaAsset
	err := row.Scan(
		&i.ID,
		&i.MediaItemID,
		&i.AssetType,
		&i.Source,
		&i.LocalPath,
		&i.RemoteUrl,
		&i.Language,
		&i.Label,
		&i.SortOrder,
		&i.Width,
		&i.Height,
		&i.FileSize,
		&i.Score,
		&i.Likes,
		&i.Aspect,
		&i.CreatedAt,
	)
	return i, err
}

const deleteMediaAsset = `-- name: DeleteMediaAsset :exec
DELETE FROM media_assets WHERE id = $1
`

func (q *Queries) DeleteMediaAsset(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteMediaAsset, id)
	return err
}

const deleteMediaAssetsByItem = `-- name: DeleteMediaAssetsByItem :exec
DELETE FROM media_assets WHERE media_item_id = $1
`

func (q *Queries) DeleteMediaAssetsByItem(ctx context.Context, mediaItemID int64) error {
	_, err := q.db.Exec(ctx, deleteMediaAssetsByItem, mediaItemID)
	return err
}

const deleteMediaAssetsByTypeLabel = `-- name: DeleteMediaAssetsByTypeLabel :exec
DELETE FROM media_assets
WHERE media_item_id = $1 AND asset_type = $2 AND label = $3
`

type DeleteMediaAssetsByTypeLabelParams struct {
	MediaItemID int64     `json:"media_item_id"`
	AssetType   AssetType `json:"asset_type"`
	Label       string    `json:"label"`
}

func (q *Queries) DeleteMediaAssetsByTypeLabel(ctx context.Context, arg DeleteMediaAssetsByTypeLabelParams) error {
	_, err := q.db.Exec(ctx, deleteMediaAssetsByTypeLabel, arg.MediaItemID, arg.AssetType, arg.Label)
	return err
}

const getMediaAssetByID = `-- name: GetMediaAssetByID :one
SELECT id, media_item_id, asset_type, source, local_path, remote_url, language, label, sort_order, width, height, file_size, score, likes, aspect, created_at FROM media_assets WHERE id = $1
`

func (q *Queries) GetMediaAssetByID(ctx context.Context, id int64) (MediaAsset, error) {
	row := q.db.QueryRow(ctx, getMediaAssetByID, id)
	var i MediaAsset
	err := row.Scan(
		&i.ID,
		&i.MediaItemID,
		&i.AssetType,
		&i.Source,
		&i.LocalPath,
		&i.RemoteUrl,
		&i.Language,
		&i.Label,
		&i.SortOrder,
		&i.Width,
		&i.Height,
		&i.FileSize,
		&i.Score,
		&i.Likes,
		&i.Aspect,
		&i.CreatedAt,
	)
	return i, err
}

const listMediaAssets = `-- name: ListMediaAssets :many
SELECT id, media_item_id, asset_type, source, local_path, remote_url, language, label, sort_order, width, height, file_size, score, likes, aspect, created_at FROM media_assets
WHERE media_item_id = $1
ORDER BY asset_type, sort_order, id
`

func (q *Queries) ListMediaAssets(ctx context.Context, mediaItemID int64) ([]MediaAsset, error) {
	rows, err := q.db.Query(ctx, listMediaAssets, mediaItemID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MediaAsset{}
	for rows.Next() {
		var i MediaAsset
		if err := rows.Scan(
			&i.ID,
			&i.MediaItemID,
			&i.AssetType,
			&i.Source,
			&i.LocalPath,
			&i.RemoteUrl,
			&i.Language,
			&i.Label,
			&i.SortOrder,
			&i.Width,
			&i.Height,
			&i.FileSize,
			&i.Score,
			&i.Likes,
			&i.Aspect,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMediaAssetsByType = `-- name: ListMediaAssetsByType :many
SELECT id, media_item_id, asset_type, source, local_path, remote_url, language, label, sort_order, width, height, file_size, score, likes, aspect, created_at FROM media_assets
WHERE media_item_id = $1 AND asset_type = $2
ORDER BY sort_order, id
`

type ListMediaAssetsByTypeParams struct {
	MediaItemID int64     `json:"media_item_id"`
	AssetType   AssetType `json:"asset_type"`
}

func (q *Queries) ListMediaAssetsByType(ctx context.Context, arg ListMediaAssetsByTypeParams) ([]MediaAsset, error) {
	rows, err := q.db.Query(ctx, listMediaAssetsByType, arg.MediaItemID, arg.AssetType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MediaAsset{}
	for rows.Next() {
		var i MediaAsset
		if err := rows.Scan(
			&i.ID,
			&i.MediaItemID,
			&i.AssetType,
			&i.Source,
			&i.LocalPath,
			&i.RemoteUrl,
			&i.Language,
			&i.Label,
			&i.SortOrder,
			&i.Width,
			&i.Height,
			&i.FileSize,
			&i.Score,
			&i.Likes,
			&i.Aspect,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const promoteOrderedMediaAsset = `-- name: PromoteOrderedMediaAsset :exec
WITH ranked AS (
    SELECT media_assets.id,
           row_number() OVER (
               ORDER BY CASE WHEN media_assets.id = $3 THEN 0 ELSE 1 END,
                        media_assets.sort_order, media_assets.id
           ) - 1 AS wanted_order
    FROM media_assets
    WHERE media_assets.media_item_id = $1
      AND media_assets.asset_type = $2::asset_type
)
UPDATE media_assets AS asset
SET sort_order = ranked.wanted_order
FROM ranked
WHERE asset.id = ranked.id
`

type PromoteOrderedMediaAssetParams struct {
	MediaItemID int64     `json:"media_item_id"`
	Column2     AssetType `json:"column_2"`
	ID          int64     `json:"id"`
}

func (q *Queries) PromoteOrderedMediaAsset(ctx context.Context, arg PromoteOrderedMediaAssetParams) error {
	_, err := q.db.Exec(ctx, promoteOrderedMediaAsset, arg.MediaItemID, arg.Column2, arg.ID)
	return err
}

const replacePrimaryMediaAsset = `-- name: ReplacePrimaryMediaAsset :one
INSERT INTO media_assets (media_item_id, asset_type, source, local_path, remote_url, language, label, sort_order, width, height, file_size)
VALUES ($1, $2, $3, $4, $5, $6, '', 0, $7, $8, $9)
ON CONFLICT (media_item_id, asset_type)
    WHERE label = '' AND asset_type IN ('poster', 'logo', 'art', 'banner', 'thumb', 'disc', 'clearart')
DO UPDATE SET
    source = EXCLUDED.source,
    local_path = EXCLUDED.local_path,
    remote_url = EXCLUDED.remote_url,
    language = EXCLUDED.language,
    sort_order = 0,
    width = EXCLUDED.width,
    height = EXCLUDED.height,
    file_size = EXCLUDED.file_size
RETURNING id, media_item_id, asset_type, source, local_path, remote_url, language, label, sort_order, width, height, file_size, score, likes, aspect, created_at
`

type ReplacePrimaryMediaAssetParams struct {
	MediaItemID int64     `json:"media_item_id"`
	AssetType   AssetType `json:"asset_type"`
	Source      string    `json:"source"`
	LocalPath   string    `json:"local_path"`
	RemoteUrl   string    `json:"remote_url"`
	Language    string    `json:"language"`
	Width       int32     `json:"width"`
	Height      int32     `json:"height"`
	FileSize    int64     `json:"file_size"`
}

// An explicit metadata-editor choice is authoritative. Unlike the scanner's
// local-first upsert above, this always replaces the singular visual slot.
func (q *Queries) ReplacePrimaryMediaAsset(ctx context.Context, arg ReplacePrimaryMediaAssetParams) (MediaAsset, error) {
	row := q.db.QueryRow(ctx, replacePrimaryMediaAsset,
		arg.MediaItemID,
		arg.AssetType,
		arg.Source,
		arg.LocalPath,
		arg.RemoteUrl,
		arg.Language,
		arg.Width,
		arg.Height,
		arg.FileSize,
	)
	var i MediaAsset
	err := row.Scan(
		&i.ID,
		&i.MediaItemID,
		&i.AssetType,
		&i.Source,
		&i.LocalPath,
		&i.RemoteUrl,
		&i.Language,
		&i.Label,
		&i.SortOrder,
		&i.Width,
		&i.Height,
		&i.FileSize,
		&i.Score,
		&i.Likes,
		&i.Aspect,
		&i.CreatedAt,
	)
	return i, err
}

const setAssetSortOrder = `-- name: SetAssetSortOrder :exec
UPDATE media_assets SET sort_order = $2 WHERE id = $1
`

type SetAssetSortOrderParams struct {
	ID        int64 `json:"id"`
	SortOrder int32 `json:"sort_order"`
}

func (q *Queries) SetAssetSortOrder(ctx context.Context, arg SetAssetSortOrderParams) error {
	_, err := q.db.Exec(ctx, setAssetSortOrder, arg.ID, arg.SortOrder)
	return err
}

const stageOrderedMediaAssets = `-- name: StageOrderedMediaAssets :exec
WITH ranked AS (
    SELECT media_assets.id,
           row_number() OVER (ORDER BY media_assets.sort_order, media_assets.id) - 1 AS old_order
    FROM media_assets
    WHERE media_assets.media_item_id = $1
      AND media_assets.asset_type = $2::asset_type
)
UPDATE media_assets AS asset
SET sort_order = (-1000000000 + ranked.old_order)::integer
FROM ranked
WHERE asset.id = ranked.id
`

type StageOrderedMediaAssetsParams struct {
	MediaItemID int64     `json:"media_item_id"`
	Column2     AssetType `json:"column_2"`
}

// Move the collection into a collision-free negative range before assigning
// its final 0..N order. This is necessary because older remote rows may all
// have an empty local_path, which makes in-place swaps trip the legacy unique
// index on (media_item_id, asset_type, sort_order, local_path).
func (q *Queries) StageOrderedMediaAssets(ctx context.Context, arg StageOrderedMediaAssetsParams) error {
	_, err := q.db.Exec(ctx, stageOrderedMediaAssets, arg.MediaItemID, arg.Column2)
	return err
}

const updateMediaAssetLocalPath = `-- name: UpdateMediaAssetLocalPath :exec
UPDATE media_assets
SET local_path = $2
WHERE id = $1
`

type UpdateMediaAssetLocalPathParams struct {
	ID        int64  `json:"id"`
	LocalPath string `json:"local_path"`
}

func (q *Queries) UpdateMediaAssetLocalPath(ctx context.Context, arg UpdateMediaAssetLocalPathParams) error {
	_, err := q.db.Exec(ctx, updateMediaAssetLocalPath, arg.ID, arg.LocalPath)
	return err
}

const upsertPrimaryMediaAsset = `-- name: UpsertPrimaryMediaAsset :one
INSERT INTO media_assets (media_item_id, asset_type, source, local_path, remote_url, language, label, sort_order, width, height, file_size)
VALUES ($1, $2, $3, $4, $5, $6, '', 0, $7, $8, $9)
ON CONFLICT (media_item_id, asset_type)
    WHERE label = '' AND asset_type IN ('poster', 'logo', 'art', 'banner', 'thumb', 'disc', 'clearart')
DO UPDATE SET
    source = EXCLUDED.source,
    local_path = EXCLUDED.local_path,
    remote_url = EXCLUDED.remote_url,
    language = EXCLUDED.language,
    sort_order = 0,
    width = EXCLUDED.width,
    height = EXCLUDED.height,
    file_size = EXCLUDED.file_size
WHERE media_assets.source <> 'local'
   OR EXCLUDED.source = 'local'
   OR NOT EXISTS (
        SELECT 1
        FROM media_items
        JOIN libraries ON libraries.id = media_items.library_id
        WHERE media_items.id = media_assets.media_item_id
          AND COALESCE((libraries.settings->>'use_local_data')::boolean, true)
   )
RETURNING id, media_item_id, asset_type, source, local_path, remote_url, language, label, sort_order, width, height, file_size, score, likes, aspect, created_at
`

type UpsertPrimaryMediaAssetParams struct {
	MediaItemID int64     `json:"media_item_id"`
	AssetType   AssetType `json:"asset_type"`
	Source      string    `json:"source"`
	LocalPath   string    `json:"local_path"`
	RemoteUrl   string    `json:"remote_url"`
	Language    string    `json:"language"`
	Width       int32     `json:"width"`
	Height      int32     `json:"height"`
	FileSize    int64     `json:"file_size"`
}

// Primary visual slots are singular. A newly discovered local sidecar replaces
// the remote value, while a later remote refresh must not displace local data.
func (q *Queries) UpsertPrimaryMediaAsset(ctx context.Context, arg UpsertPrimaryMediaAssetParams) (MediaAsset, error) {
	row := q.db.QueryRow(ctx, upsertPrimaryMediaAsset,
		arg.MediaItemID,
		arg.AssetType,
		arg.Source,
		arg.LocalPath,
		arg.RemoteUrl,
		arg.Language,
		arg.Width,
		arg.Height,
		arg.FileSize,
	)
	var i MediaAsset
	err := row.Scan(
		&i.ID,
		&i.MediaItemID,
		&i.AssetType,
		&i.Source,
		&i.LocalPath,
		&i.RemoteUrl,
		&i.Language,
		&i.Label,
		&i.SortOrder,
		&i.Width,
		&i.Height,
		&i.FileSize,
		&i.Score,
		&i.Likes,
		&i.Aspect,
		&i.CreatedAt,
	)
	return i, err
}
