// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: media_assets.sql

package sqlc

import (
	"context"
)

const countMediaAssetsByType = `-- name: CountMediaAssetsByType :many
SELECT asset_type, count(*) as count
FROM media_assets
WHERE media_item_id = $1
GROUP BY asset_type
`

type CountMediaAssetsByTypeRow struct {
	AssetType AssetType `json:"asset_type"`
	Count     int64     `json:"count"`
}

func (q *Queries) CountMediaAssetsByType(ctx context.Context, mediaItemID int64) ([]CountMediaAssetsByTypeRow, error) {
	rows, err := q.db.Query(ctx, countMediaAssetsByType, mediaItemID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountMediaAssetsByTypeRow{}
	for rows.Next() {
		var i CountMediaAssetsByTypeRow
		if err := rows.Scan(&i.AssetType, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createMediaAsset = `-- name: CreateMediaAsset :one
INSERT INTO media_assets (media_item_id, asset_type, source, local_path, remote_url, language, label, sort_order, width, height, file_size)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
ON CONFLICT DO NOTHING
RETURNING id, media_item_id, asset_type, source, local_path, remote_url, language, label, sort_order, width, height, file_size, score, likes, aspect, created_at, content_hash, visual_hash
`

type CreateMediaAssetParams struct {
	MediaItemID int64     `json:"media_item_id"`
	AssetType   AssetType `json:"asset_type"`
	Source      string    `json:"source"`
	LocalPath   string    `json:"local_path"`
	RemoteUrl   string    `json:"remote_url"`
	Language    string    `json:"language"`
	Label       string    `json:"label"`
	SortOrder   int32     `json:"sort_order"`
	Width       int32     `json:"width"`
	Height      int32     `json:"height"`
	FileSize    int64     `json:"file_size"`
}

func (q *Queries) CreateMediaAsset(ctx context.Context, arg CreateMediaAssetParams) (MediaAsset, error) {
	row := q.db.QueryRow(ctx, createMediaAsset,
		arg.MediaItemID,
		arg.AssetType,
		arg.Source,
		arg.LocalPath,
		arg.RemoteUrl,
		arg.Language,
		arg.Label,
		arg.SortOrder,
		arg.Width,
		arg.Height,
		arg.FileSize,
	)
	var i MediaAsset
	err := row.Scan(
		&i.ID,
		&i.MediaItemID,
		&i.AssetType,
		&i.Source,
		&i.LocalPath,
		&i.RemoteUrl,
		&i.Language,
		&i.Label,
		&i.SortOrder,
		&i.Width,
		&i.Height,
		&i.FileSize,
		&i.Score,
		&i.Likes,
		&i.Aspect,
		&i.CreatedAt,
		&i.ContentHash,
		&i.VisualHash,
	)
	return i, err
}

const deleteMediaAsset = `-- name: DeleteMediaAsset :exec
DELETE FROM media_assets WHERE id = $1
`

func (q *Queries) DeleteMediaAsset(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteMediaAsset, id)
	return err
}

const deleteMediaAssetsByItem = `-- name: DeleteMediaAssetsByItem :exec
DELETE FROM media_assets WHERE media_item_id = $1
`

func (q *Queries) DeleteMediaAssetsByItem(ctx context.Context, mediaItemID int64) error {
	_, err := q.db.Exec(ctx, deleteMediaAssetsByItem, mediaItemID)
	return err
}

const deleteMediaAssetsByTypeLabel = `-- name: DeleteMediaAssetsByTypeLabel :exec
DELETE FROM media_assets
WHERE media_item_id = $1 AND asset_type = $2 AND label = $3
`

type DeleteMediaAssetsByTypeLabelParams struct {
	MediaItemID int64     `json:"media_item_id"`
	AssetType   AssetType `json:"asset_type"`
	Label       string    `json:"label"`
}

func (q *Queries) DeleteMediaAssetsByTypeLabel(ctx context.Context, arg DeleteMediaAssetsByTypeLabelParams) error {
	_, err := q.db.Exec(ctx, deleteMediaAssetsByTypeLabel, arg.MediaItemID, arg.AssetType, arg.Label)
	return err
}

const finalizeStagedMediaAssetOrder = `-- name: FinalizeStagedMediaAssetOrder :exec
UPDATE media_assets
SET sort_order = sort_order + 1000000000
WHERE media_item_id = $1
  AND asset_type = $2::asset_type
  AND sort_order < 0
`

type FinalizeStagedMediaAssetOrderParams struct {
	MediaItemID int64     `json:"media_item_id"`
	AssetType   AssetType `json:"asset_type"`
}

func (q *Queries) FinalizeStagedMediaAssetOrder(ctx context.Context, arg FinalizeStagedMediaAssetOrderParams) error {
	_, err := q.db.Exec(ctx, finalizeStagedMediaAssetOrder, arg.MediaItemID, arg.AssetType)
	return err
}

const getMediaAssetByID = `-- name: GetMediaAssetByID :one
SELECT id, media_item_id, asset_type, source, local_path, remote_url, language, label, sort_order, width, height, file_size, score, likes, aspect, created_at, content_hash, visual_hash FROM media_assets WHERE id = $1
`

func (q *Queries) GetMediaAssetByID(ctx context.Context, id int64) (MediaAsset, error) {
	row := q.db.QueryRow(ctx, getMediaAssetByID, id)
	var i MediaAsset
	err := row.Scan(
		&i.ID,
		&i.MediaItemID,
		&i.AssetType,
		&i.Source,
		&i.LocalPath,
		&i.RemoteUrl,
		&i.Language,
		&i.Label,
		&i.SortOrder,
		&i.Width,
		&i.Height,
		&i.FileSize,
		&i.Score,
		&i.Likes,
		&i.Aspect,
		&i.CreatedAt,
		&i.ContentHash,
		&i.VisualHash,
	)
	return i, err
}

const listMediaAssets = `-- name: ListMediaAssets :many
SELECT id, media_item_id, asset_type, source, local_path, remote_url, language, label, sort_order, width, height, file_size, score, likes, aspect, created_at, content_hash, visual_hash FROM media_assets
WHERE media_item_id = $1
ORDER BY asset_type, sort_order, id
`

func (q *Queries) ListMediaAssets(ctx context.Context, mediaItemID int64) ([]MediaAsset, error) {
	rows, err := q.db.Query(ctx, listMediaAssets, mediaItemID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MediaAsset{}
	for rows.Next() {
		var i MediaAsset
		if err := rows.Scan(
			&i.ID,
			&i.MediaItemID,
			&i.AssetType,
			&i.Source,
			&i.LocalPath,
			&i.RemoteUrl,
			&i.Language,
			&i.Label,
			&i.SortOrder,
			&i.Width,
			&i.Height,
			&i.FileSize,
			&i.Score,
			&i.Likes,
			&i.Aspect,
			&i.CreatedAt,
			&i.ContentHash,
			&i.VisualHash,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMediaAssetsByType = `-- name: ListMediaAssetsByType :many
SELECT id, media_item_id, asset_type, source, local_path, remote_url, language, label, sort_order, width, height, file_size, score, likes, aspect, created_at, content_hash, visual_hash FROM media_assets
WHERE media_item_id = $1 AND asset_type = $2
ORDER BY sort_order, id
`

type ListMediaAssetsByTypeParams struct {
	MediaItemID int64     `json:"media_item_id"`
	AssetType   AssetType `json:"asset_type"`
}

func (q *Queries) ListMediaAssetsByType(ctx context.Context, arg ListMediaAssetsByTypeParams) ([]MediaAsset, error) {
	rows, err := q.db.Query(ctx, listMediaAssetsByType, arg.MediaItemID, arg.AssetType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MediaAsset{}
	for rows.Next() {
		var i MediaAsset
		if err := rows.Scan(
			&i.ID,
			&i.MediaItemID,
			&i.AssetType,
			&i.Source,
			&i.LocalPath,
			&i.RemoteUrl,
			&i.Language,
			&i.Label,
			&i.SortOrder,
			&i.Width,
			&i.Height,
			&i.FileSize,
			&i.Score,
			&i.Likes,
			&i.Aspect,
			&i.CreatedAt,
			&i.ContentHash,
			&i.VisualHash,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingRemoteMediaAssets = `-- name: ListPendingRemoteMediaAssets :many
SELECT media_assets.id, media_assets.media_item_id, media_assets.asset_type,
       media_assets.remote_url, media_assets.label, media_assets.sort_order,
       media_items.media_type
FROM media_assets
JOIN media_items ON media_items.id = media_assets.media_item_id
WHERE media_assets.local_path = ''
  AND media_assets.remote_url <> ''
  AND media_assets.asset_type IN ('poster', 'backdrop', 'logo', 'art', 'banner', 'thumb', 'disc', 'clearart', 'still')
  AND media_assets.id > $1
ORDER BY media_assets.id
LIMIT $2
`

type ListPendingRemoteMediaAssetsParams struct {
	ID    int64 `json:"id"`
	Limit int32 `json:"limit"`
}

type ListPendingRemoteMediaAssetsRow struct {
	ID          int64     `json:"id"`
	MediaItemID int64     `json:"media_item_id"`
	AssetType   AssetType `json:"asset_type"`
	RemoteUrl   string    `json:"remote_url"`
	Label       string    `json:"label"`
	SortOrder   int32     `json:"sort_order"`
	MediaType   MediaType `json:"media_type"`
}

// Visual asset rows whose bytes were never materialized locally — the warm
// sweep pages these by id and enqueues downloads. Non-visual sidecar types
// (subtitle/lyrics/nfo) never have remote bytes to warm.
func (q *Queries) ListPendingRemoteMediaAssets(ctx context.Context, arg ListPendingRemoteMediaAssetsParams) ([]ListPendingRemoteMediaAssetsRow, error) {
	rows, err := q.db.Query(ctx, listPendingRemoteMediaAssets, arg.ID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPendingRemoteMediaAssetsRow{}
	for rows.Next() {
		var i ListPendingRemoteMediaAssetsRow
		if err := rows.Scan(
			&i.ID,
			&i.MediaItemID,
			&i.AssetType,
			&i.RemoteUrl,
			&i.Label,
			&i.SortOrder,
			&i.MediaType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnfingerprintedMediaAssets = `-- name: ListUnfingerprintedMediaAssets :many
SELECT media_assets.id, media_assets.media_item_id, media_assets.asset_type, media_assets.source, media_assets.local_path, media_assets.remote_url, media_assets.language, media_assets.label, media_assets.sort_order, media_assets.width, media_assets.height, media_assets.file_size, media_assets.score, media_assets.likes, media_assets.aspect, media_assets.created_at, media_assets.content_hash, media_assets.visual_hash
FROM media_assets
WHERE media_assets.local_path <> ''
  AND media_assets.content_hash = ''
  AND media_assets.asset_type IN ('poster', 'backdrop', 'logo', 'art', 'banner', 'thumb', 'disc', 'clearart', 'still')
  AND media_assets.id > $1
ORDER BY media_assets.id
LIMIT $2
`

type ListUnfingerprintedMediaAssetsParams struct {
	ID    int64 `json:"id"`
	Limit int32 `json:"limit"`
}

// Materialized artwork from older releases and scanner-discovered local
// sidecars may predate image fingerprinting. The daily artwork reconciliation
// pages these rows by id, computes their exact/perceptual hashes, and collapses
// duplicates through the same path used by fresh downloads.
func (q *Queries) ListUnfingerprintedMediaAssets(ctx context.Context, arg ListUnfingerprintedMediaAssetsParams) ([]MediaAsset, error) {
	rows, err := q.db.Query(ctx, listUnfingerprintedMediaAssets, arg.ID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MediaAsset{}
	for rows.Next() {
		var i MediaAsset
		if err := rows.Scan(
			&i.ID,
			&i.MediaItemID,
			&i.AssetType,
			&i.Source,
			&i.LocalPath,
			&i.RemoteUrl,
			&i.Language,
			&i.Label,
			&i.SortOrder,
			&i.Width,
			&i.Height,
			&i.FileSize,
			&i.Score,
			&i.Likes,
			&i.Aspect,
			&i.CreatedAt,
			&i.ContentHash,
			&i.VisualHash,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const promoteOrderedMediaAsset = `-- name: PromoteOrderedMediaAsset :exec
WITH ranked AS (
    SELECT media_assets.id,
           row_number() OVER (
               ORDER BY CASE WHEN media_assets.id = $3 THEN 0 ELSE 1 END,
                        media_assets.sort_order, media_assets.id
           ) - 1 AS wanted_order
    FROM media_assets
    WHERE media_assets.media_item_id = $1
      AND media_assets.asset_type = $2::asset_type
)
UPDATE media_assets AS asset
SET sort_order = ranked.wanted_order
FROM ranked
WHERE asset.id = ranked.id
`

type PromoteOrderedMediaAssetParams struct {
	MediaItemID int64     `json:"media_item_id"`
	Column2     AssetType `json:"column_2"`
	ID          int64     `json:"id"`
}

func (q *Queries) PromoteOrderedMediaAsset(ctx context.Context, arg PromoteOrderedMediaAssetParams) error {
	_, err := q.db.Exec(ctx, promoteOrderedMediaAsset, arg.MediaItemID, arg.Column2, arg.ID)
	return err
}

const replacePrimaryMediaAsset = `-- name: ReplacePrimaryMediaAsset :one
INSERT INTO media_assets (media_item_id, asset_type, source, local_path, remote_url, language, label, sort_order, width, height, file_size)
VALUES ($1, $2, $3, $4, $5, $6, '', 0, $7, $8, $9)
ON CONFLICT (media_item_id, asset_type)
    WHERE label = '' AND asset_type IN ('poster', 'logo', 'art', 'banner', 'thumb', 'disc', 'clearart')
DO UPDATE SET
    source = EXCLUDED.source,
    local_path = EXCLUDED.local_path,
    remote_url = EXCLUDED.remote_url,
    language = EXCLUDED.language,
    sort_order = 0,
    width = EXCLUDED.width,
    height = EXCLUDED.height,
    file_size = EXCLUDED.file_size
RETURNING id, media_item_id, asset_type, source, local_path, remote_url, language, label, sort_order, width, height, file_size, score, likes, aspect, created_at, content_hash, visual_hash
`

type ReplacePrimaryMediaAssetParams struct {
	MediaItemID int64     `json:"media_item_id"`
	AssetType   AssetType `json:"asset_type"`
	Source      string    `json:"source"`
	LocalPath   string    `json:"local_path"`
	RemoteUrl   string    `json:"remote_url"`
	Language    string    `json:"language"`
	Width       int32     `json:"width"`
	Height      int32     `json:"height"`
	FileSize    int64     `json:"file_size"`
}

// An explicit metadata-editor choice is authoritative. Unlike the scanner's
// local-first upsert above, this always replaces the singular visual slot.
func (q *Queries) ReplacePrimaryMediaAsset(ctx context.Context, arg ReplacePrimaryMediaAssetParams) (MediaAsset, error) {
	row := q.db.QueryRow(ctx, replacePrimaryMediaAsset,
		arg.MediaItemID,
		arg.AssetType,
		arg.Source,
		arg.LocalPath,
		arg.RemoteUrl,
		arg.Language,
		arg.Width,
		arg.Height,
		arg.FileSize,
	)
	var i MediaAsset
	err := row.Scan(
		&i.ID,
		&i.MediaItemID,
		&i.AssetType,
		&i.Source,
		&i.LocalPath,
		&i.RemoteUrl,
		&i.Language,
		&i.Label,
		&i.SortOrder,
		&i.Width,
		&i.Height,
		&i.FileSize,
		&i.Score,
		&i.Likes,
		&i.Aspect,
		&i.CreatedAt,
		&i.ContentHash,
		&i.VisualHash,
	)
	return i, err
}

const setAssetSortOrder = `-- name: SetAssetSortOrder :exec
UPDATE media_assets SET sort_order = $2 WHERE id = $1
`

type SetAssetSortOrderParams struct {
	ID        int64 `json:"id"`
	SortOrder int32 `json:"sort_order"`
}

func (q *Queries) SetAssetSortOrder(ctx context.Context, arg SetAssetSortOrderParams) error {
	_, err := q.db.Exec(ctx, setAssetSortOrder, arg.ID, arg.SortOrder)
	return err
}

const stageMediaAssetsAfterDedup = `-- name: StageMediaAssetsAfterDedup :exec
WITH ranked AS (
    SELECT media_assets.id,
           row_number() OVER (
               ORDER BY CASE
                            WHEN media_assets.id = $1 THEN $2::bigint * 2
                            ELSE media_assets.sort_order::bigint * 2 + 1
                        END,
                        media_assets.id
           ) - 1 AS wanted_order
    FROM media_assets
    WHERE media_assets.media_item_id = $3
      AND media_assets.asset_type = $4::asset_type
)
UPDATE media_assets AS asset
SET sort_order = (-1000000000 + ranked.wanted_order)::integer
FROM ranked
WHERE asset.id = ranked.id
`

type StageMediaAssetsAfterDedupParams struct {
	WinnerID     int64     `json:"winner_id"`
	DesiredOrder int64     `json:"desired_order"`
	MediaItemID  int64     `json:"media_item_id"`
	AssetType    AssetType `json:"asset_type"`
}

// Preserve the best duplicate at the earliest position occupied by its group,
// then close all ordering gaps. The doubled keys place the winner before an
// unrelated row that happened to share that historical sort_order.
func (q *Queries) StageMediaAssetsAfterDedup(ctx context.Context, arg StageMediaAssetsAfterDedupParams) error {
	_, err := q.db.Exec(ctx, stageMediaAssetsAfterDedup,
		arg.WinnerID,
		arg.DesiredOrder,
		arg.MediaItemID,
		arg.AssetType,
	)
	return err
}

const stageOrderedMediaAssets = `-- name: StageOrderedMediaAssets :exec
WITH ranked AS (
    SELECT media_assets.id,
           row_number() OVER (ORDER BY media_assets.sort_order, media_assets.id) - 1 AS old_order
    FROM media_assets
    WHERE media_assets.media_item_id = $1
      AND media_assets.asset_type = $2::asset_type
)
UPDATE media_assets AS asset
SET sort_order = (-1000000000 + ranked.old_order)::integer
FROM ranked
WHERE asset.id = ranked.id
`

type StageOrderedMediaAssetsParams struct {
	MediaItemID int64     `json:"media_item_id"`
	Column2     AssetType `json:"column_2"`
}

// Move the collection into a collision-free negative range before assigning
// its final 0..N order. This is necessary because older remote rows may all
// have an empty local_path, which makes in-place swaps trip the legacy unique
// index on (media_item_id, asset_type, sort_order, local_path).
func (q *Queries) StageOrderedMediaAssets(ctx context.Context, arg StageOrderedMediaAssetsParams) error {
	_, err := q.db.Exec(ctx, stageOrderedMediaAssets, arg.MediaItemID, arg.Column2)
	return err
}

const updateMediaAssetLocalPath = `-- name: UpdateMediaAssetLocalPath :exec
UPDATE media_assets
SET local_path = $2
WHERE id = $1
`

type UpdateMediaAssetLocalPathParams struct {
	ID        int64  `json:"id"`
	LocalPath string `json:"local_path"`
}

func (q *Queries) UpdateMediaAssetLocalPath(ctx context.Context, arg UpdateMediaAssetLocalPathParams) error {
	_, err := q.db.Exec(ctx, updateMediaAssetLocalPath, arg.ID, arg.LocalPath)
	return err
}

const updateMediaAssetMaterialization = `-- name: UpdateMediaAssetMaterialization :one
UPDATE media_assets
SET local_path = $1,
    content_hash = $2,
    visual_hash = $3,
    width = CASE WHEN $4::integer > 0 THEN $4 ELSE width END,
    height = CASE WHEN $5::integer > 0 THEN $5 ELSE height END,
    file_size = CASE WHEN $6::bigint > 0 THEN $6 ELSE file_size END
WHERE id = $7
RETURNING id, media_item_id, asset_type, source, local_path, remote_url, language, label, sort_order, width, height, file_size, score, likes, aspect, created_at, content_hash, visual_hash
`

type UpdateMediaAssetMaterializationParams struct {
	LocalPath   string `json:"local_path"`
	ContentHash string `json:"content_hash"`
	VisualHash  string `json:"visual_hash"`
	Width       int32  `json:"width"`
	Height      int32  `json:"height"`
	FileSize    int64  `json:"file_size"`
	ID          int64  `json:"id"`
}

func (q *Queries) UpdateMediaAssetMaterialization(ctx context.Context, arg UpdateMediaAssetMaterializationParams) (MediaAsset, error) {
	row := q.db.QueryRow(ctx, updateMediaAssetMaterialization,
		arg.LocalPath,
		arg.ContentHash,
		arg.VisualHash,
		arg.Width,
		arg.Height,
		arg.FileSize,
		arg.ID,
	)
	var i MediaAsset
	err := row.Scan(
		&i.ID,
		&i.MediaItemID,
		&i.AssetType,
		&i.Source,
		&i.LocalPath,
		&i.RemoteUrl,
		&i.Language,
		&i.Label,
		&i.SortOrder,
		&i.Width,
		&i.Height,
		&i.FileSize,
		&i.Score,
		&i.Likes,
		&i.Aspect,
		&i.CreatedAt,
		&i.ContentHash,
		&i.VisualHash,
	)
	return i, err
}

const upsertPrimaryMediaAsset = `-- name: UpsertPrimaryMediaAsset :one
WITH current_primary AS MATERIALIZED (
    SELECT media_assets.id, media_assets.media_item_id, media_assets.asset_type, media_assets.source, media_assets.local_path, media_assets.remote_url, media_assets.language, media_assets.label, media_assets.sort_order, media_assets.width, media_assets.height, media_assets.file_size, media_assets.score, media_assets.likes, media_assets.aspect, media_assets.created_at, media_assets.content_hash, media_assets.visual_hash
    FROM media_assets
    WHERE media_assets.media_item_id = $1
      AND media_assets.asset_type = $2::asset_type
      AND media_assets.label = ''
      AND media_assets.asset_type IN ('poster', 'logo', 'art', 'banner', 'thumb', 'disc', 'clearart')
    FOR UPDATE
),
replacement_allowed AS MATERIALIZED (
    SELECT NOT EXISTS (SELECT 1 FROM current_primary)
        OR EXISTS (
            SELECT 1
            FROM current_primary
            WHERE current_primary.source <> 'local'
               OR $3::text = 'local'
               OR NOT EXISTS (
                    SELECT 1
                    FROM media_items
                    JOIN libraries ON libraries.id = media_items.library_id
                    WHERE media_items.id = current_primary.media_item_id
                      AND COALESCE((libraries.settings->>'use_local_data')::boolean, true)
               )
        ) AS allowed
),
preserved_remote AS MATERIALIZED (
    SELECT media_assets.id, media_assets.media_item_id, media_assets.asset_type, media_assets.source, media_assets.local_path, media_assets.remote_url, media_assets.language, media_assets.label, media_assets.sort_order, media_assets.width, media_assets.height, media_assets.file_size, media_assets.score, media_assets.likes, media_assets.aspect, media_assets.created_at, media_assets.content_hash, media_assets.visual_hash
    FROM media_assets
    CROSS JOIN replacement_allowed
    WHERE replacement_allowed.allowed
      AND $4::text = ''
      AND $5::text <> ''
      AND media_assets.media_item_id = $1
      AND media_assets.asset_type = $2::asset_type
      AND media_assets.remote_url = $5
      AND CASE
            WHEN media_assets.asset_type = 'still'
              OR media_assets.label ~ '^season-[0-9]+$'
              OR media_assets.label ~ '^s[0-9]+e[0-9]+$'
                THEN media_assets.label
            ELSE ''
          END = ''
    ORDER BY (media_assets.local_path <> '') DESC, media_assets.id
    LIMIT 1
    FOR UPDATE OF media_assets
),
removed_conflicts AS (
    DELETE FROM media_assets
    USING replacement_allowed,
          (SELECT count(*) FROM preserved_remote) AS preservation_barrier
    WHERE replacement_allowed.allowed
      AND media_assets.media_item_id = $1
      AND media_assets.asset_type = $2::asset_type
      AND media_assets.id <> COALESCE((SELECT id FROM current_primary), 0)
      AND CASE
            WHEN media_assets.asset_type = 'still'
              OR media_assets.label ~ '^season-[0-9]+$'
              OR media_assets.label ~ '^s[0-9]+e[0-9]+$'
                THEN media_assets.label
            ELSE ''
          END = ''
      AND (
          ($4::text <> '' AND media_assets.local_path = $4)
          OR ($5::text <> '' AND media_assets.remote_url = $5)
      )
    RETURNING media_assets.id
)
INSERT INTO media_assets (
    media_item_id, asset_type, source, local_path, remote_url, language, label,
    sort_order, width, height, file_size, score, likes, aspect, content_hash, visual_hash
)
SELECT
    $1,
    $2::asset_type,
    $3,
    CASE
        WHEN $4::text <> '' THEN $4
        ELSE COALESCE((SELECT local_path FROM preserved_remote), '')
    END,
    $5,
    CASE
        WHEN $6::text <> '' THEN $6
        ELSE COALESCE((SELECT language FROM preserved_remote), '')
    END,
    '',
    0,
    CASE WHEN $7::integer > 0 THEN $7 ELSE COALESCE((SELECT width FROM preserved_remote), 0) END,
    CASE WHEN $8::integer > 0 THEN $8 ELSE COALESCE((SELECT height FROM preserved_remote), 0) END,
    CASE WHEN $9::bigint > 0 THEN $9 ELSE COALESCE((SELECT file_size FROM preserved_remote), 0) END,
    COALESCE((SELECT score FROM preserved_remote), 0),
    COALESCE((SELECT likes FROM preserved_remote), 0),
    COALESCE((SELECT aspect FROM preserved_remote), ''),
    COALESCE((SELECT content_hash FROM preserved_remote), ''),
    COALESCE((SELECT visual_hash FROM preserved_remote), '')
FROM replacement_allowed
CROSS JOIN (SELECT count(*) FROM removed_conflicts) AS conflict_removal_barrier
WHERE replacement_allowed.allowed
ON CONFLICT (media_item_id, asset_type)
    WHERE label = '' AND asset_type IN ('poster', 'logo', 'art', 'banner', 'thumb', 'disc', 'clearart')
DO UPDATE SET
    source = EXCLUDED.source,
    local_path = EXCLUDED.local_path,
    remote_url = EXCLUDED.remote_url,
    language = EXCLUDED.language,
    sort_order = 0,
    width = EXCLUDED.width,
    height = EXCLUDED.height,
    file_size = EXCLUDED.file_size,
    score = EXCLUDED.score,
    likes = EXCLUDED.likes,
    aspect = EXCLUDED.aspect,
    content_hash = EXCLUDED.content_hash,
    visual_hash = EXCLUDED.visual_hash
RETURNING id, media_item_id, asset_type, source, local_path, remote_url, language, label, sort_order, width, height, file_size, score, likes, aspect, created_at, content_hash, visual_hash
`

type UpsertPrimaryMediaAssetParams struct {
	MediaItemID int64     `json:"media_item_id"`
	AssetType   AssetType `json:"asset_type"`
	Source      string    `json:"source"`
	LocalPath   string    `json:"local_path"`
	RemoteUrl   string    `json:"remote_url"`
	Language    string    `json:"language"`
	Width       int32     `json:"width"`
	Height      int32     `json:"height"`
	FileSize    int64     `json:"file_size"`
}

// Primary visual slots are singular. A newly discovered local sidecar replaces
// the remote value, while a later remote refresh must not displace local data.
//
// A selected remote identity may already exist in a labeled legacy/alternate
// row. Remove that row before moving the identity into the primary slot, and
// carry over its materialized bytes so the cache file does not become
// orphaned. The delete is gated by the same local-data precedence rule as the
// upsert: a rejected remote refresh must leave both the local primary and its
// alternate candidate untouched.
func (q *Queries) UpsertPrimaryMediaAsset(ctx context.Context, arg UpsertPrimaryMediaAssetParams) (MediaAsset, error) {
	row := q.db.QueryRow(ctx, upsertPrimaryMediaAsset,
		arg.MediaItemID,
		arg.AssetType,
		arg.Source,
		arg.LocalPath,
		arg.RemoteUrl,
		arg.Language,
		arg.Width,
		arg.Height,
		arg.FileSize,
	)
	var i MediaAsset
	err := row.Scan(
		&i.ID,
		&i.MediaItemID,
		&i.AssetType,
		&i.Source,
		&i.LocalPath,
		&i.RemoteUrl,
		&i.Language,
		&i.Label,
		&i.SortOrder,
		&i.Width,
		&i.Height,
		&i.FileSize,
		&i.Score,
		&i.Likes,
		&i.Aspect,
		&i.CreatedAt,
		&i.ContentHash,
		&i.VisualHash,
	)
	return i, err
}
