// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: music.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAlbum = `-- name: CreateAlbum :one
INSERT INTO albums (artist_id, title, year, musicbrainz_id, album_type, genres, cover_path, release_date,
    label, country, barcode, total_tracks, total_discs, tags)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14)
RETURNING id, artist_id, title, year, musicbrainz_id, album_type, genres, cover_path, release_date, label, country, barcode, total_tracks, total_discs, tags, search_vector
`

type CreateAlbumParams struct {
	ArtistID      int64       `json:"artist_id"`
	Title         string      `json:"title"`
	Year          string      `json:"year"`
	MusicbrainzID string      `json:"musicbrainz_id"`
	AlbumType     string      `json:"album_type"`
	Genres        []string    `json:"genres"`
	CoverPath     string      `json:"cover_path"`
	ReleaseDate   pgtype.Date `json:"release_date"`
	Label         string      `json:"label"`
	Country       string      `json:"country"`
	Barcode       string      `json:"barcode"`
	TotalTracks   int32       `json:"total_tracks"`
	TotalDiscs    int32       `json:"total_discs"`
	Tags          []string    `json:"tags"`
}

func (q *Queries) CreateAlbum(ctx context.Context, arg CreateAlbumParams) (Album, error) {
	row := q.db.QueryRow(ctx, createAlbum,
		arg.ArtistID,
		arg.Title,
		arg.Year,
		arg.MusicbrainzID,
		arg.AlbumType,
		arg.Genres,
		arg.CoverPath,
		arg.ReleaseDate,
		arg.Label,
		arg.Country,
		arg.Barcode,
		arg.TotalTracks,
		arg.TotalDiscs,
		arg.Tags,
	)
	var i Album
	err := row.Scan(
		&i.ID,
		&i.ArtistID,
		&i.Title,
		&i.Year,
		&i.MusicbrainzID,
		&i.AlbumType,
		&i.Genres,
		&i.CoverPath,
		&i.ReleaseDate,
		&i.Label,
		&i.Country,
		&i.Barcode,
		&i.TotalTracks,
		&i.TotalDiscs,
		&i.Tags,
		&i.SearchVector,
	)
	return i, err
}

const createArtist = `-- name: CreateArtist :one
INSERT INTO artists (media_item_id, musicbrainz_id, sort_name, biography)
VALUES ($1, $2, $3, $4)
RETURNING id, media_item_id, musicbrainz_id, sort_name, biography, search_vector
`

type CreateArtistParams struct {
	MediaItemID   int64  `json:"media_item_id"`
	MusicbrainzID string `json:"musicbrainz_id"`
	SortName      string `json:"sort_name"`
	Biography     string `json:"biography"`
}

func (q *Queries) CreateArtist(ctx context.Context, arg CreateArtistParams) (Artist, error) {
	row := q.db.QueryRow(ctx, createArtist,
		arg.MediaItemID,
		arg.MusicbrainzID,
		arg.SortName,
		arg.Biography,
	)
	var i Artist
	err := row.Scan(
		&i.ID,
		&i.MediaItemID,
		&i.MusicbrainzID,
		&i.SortName,
		&i.Biography,
		&i.SearchVector,
	)
	return i, err
}

const createTrack = `-- name: CreateTrack :one
INSERT INTO tracks (album_id, disc_number, track_number, title, duration_ms, file_path)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, album_id, disc_number, track_number, title, duration_ms, file_path, search_vector
`

type CreateTrackParams struct {
	AlbumID     int64  `json:"album_id"`
	DiscNumber  int32  `json:"disc_number"`
	TrackNumber int32  `json:"track_number"`
	Title       string `json:"title"`
	DurationMs  int32  `json:"duration_ms"`
	FilePath    string `json:"file_path"`
}

func (q *Queries) CreateTrack(ctx context.Context, arg CreateTrackParams) (Track, error) {
	row := q.db.QueryRow(ctx, createTrack,
		arg.AlbumID,
		arg.DiscNumber,
		arg.TrackNumber,
		arg.Title,
		arg.DurationMs,
		arg.FilePath,
	)
	var i Track
	err := row.Scan(
		&i.ID,
		&i.AlbumID,
		&i.DiscNumber,
		&i.TrackNumber,
		&i.Title,
		&i.DurationMs,
		&i.FilePath,
		&i.SearchVector,
	)
	return i, err
}

const getAlbumByID = `-- name: GetAlbumByID :one
SELECT id, artist_id, title, year, musicbrainz_id, album_type, genres, cover_path, release_date, label, country, barcode, total_tracks, total_discs, tags, search_vector FROM albums WHERE id = $1
`

func (q *Queries) GetAlbumByID(ctx context.Context, id int64) (Album, error) {
	row := q.db.QueryRow(ctx, getAlbumByID, id)
	var i Album
	err := row.Scan(
		&i.ID,
		&i.ArtistID,
		&i.Title,
		&i.Year,
		&i.MusicbrainzID,
		&i.AlbumType,
		&i.Genres,
		&i.CoverPath,
		&i.ReleaseDate,
		&i.Label,
		&i.Country,
		&i.Barcode,
		&i.TotalTracks,
		&i.TotalDiscs,
		&i.Tags,
		&i.SearchVector,
	)
	return i, err
}

const getAlbumByMusicBrainzID = `-- name: GetAlbumByMusicBrainzID :one
SELECT id, artist_id, title, year, musicbrainz_id, album_type, genres, cover_path, release_date, label, country, barcode, total_tracks, total_discs, tags, search_vector FROM albums WHERE musicbrainz_id = $1
`

func (q *Queries) GetAlbumByMusicBrainzID(ctx context.Context, musicbrainzID string) (Album, error) {
	row := q.db.QueryRow(ctx, getAlbumByMusicBrainzID, musicbrainzID)
	var i Album
	err := row.Scan(
		&i.ID,
		&i.ArtistID,
		&i.Title,
		&i.Year,
		&i.MusicbrainzID,
		&i.AlbumType,
		&i.Genres,
		&i.CoverPath,
		&i.ReleaseDate,
		&i.Label,
		&i.Country,
		&i.Barcode,
		&i.TotalTracks,
		&i.TotalDiscs,
		&i.Tags,
		&i.SearchVector,
	)
	return i, err
}

const getArtistByMediaItemID = `-- name: GetArtistByMediaItemID :one
SELECT id, media_item_id, musicbrainz_id, sort_name, biography, search_vector FROM artists WHERE media_item_id = $1
`

func (q *Queries) GetArtistByMediaItemID(ctx context.Context, mediaItemID int64) (Artist, error) {
	row := q.db.QueryRow(ctx, getArtistByMediaItemID, mediaItemID)
	var i Artist
	err := row.Scan(
		&i.ID,
		&i.MediaItemID,
		&i.MusicbrainzID,
		&i.SortName,
		&i.Biography,
		&i.SearchVector,
	)
	return i, err
}

const getArtistByMusicBrainzID = `-- name: GetArtistByMusicBrainzID :one
SELECT id, media_item_id, musicbrainz_id, sort_name, biography, search_vector FROM artists WHERE musicbrainz_id = $1
`

func (q *Queries) GetArtistByMusicBrainzID(ctx context.Context, musicbrainzID string) (Artist, error) {
	row := q.db.QueryRow(ctx, getArtistByMusicBrainzID, musicbrainzID)
	var i Artist
	err := row.Scan(
		&i.ID,
		&i.MediaItemID,
		&i.MusicbrainzID,
		&i.SortName,
		&i.Biography,
		&i.SearchVector,
	)
	return i, err
}

const getTrackByID = `-- name: GetTrackByID :one
SELECT id, album_id, disc_number, track_number, title, duration_ms, file_path, search_vector FROM tracks WHERE id = $1
`

func (q *Queries) GetTrackByID(ctx context.Context, id int64) (Track, error) {
	row := q.db.QueryRow(ctx, getTrackByID, id)
	var i Track
	err := row.Scan(
		&i.ID,
		&i.AlbumID,
		&i.DiscNumber,
		&i.TrackNumber,
		&i.Title,
		&i.DurationMs,
		&i.FilePath,
		&i.SearchVector,
	)
	return i, err
}

const listAlbumsByArtist = `-- name: ListAlbumsByArtist :many
SELECT id, artist_id, title, year, musicbrainz_id, album_type, genres, cover_path, release_date, label, country, barcode, total_tracks, total_discs, tags, search_vector FROM albums WHERE artist_id = $1 ORDER BY year ASC, title ASC
`

func (q *Queries) ListAlbumsByArtist(ctx context.Context, artistID int64) ([]Album, error) {
	rows, err := q.db.Query(ctx, listAlbumsByArtist, artistID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Album{}
	for rows.Next() {
		var i Album
		if err := rows.Scan(
			&i.ID,
			&i.ArtistID,
			&i.Title,
			&i.Year,
			&i.MusicbrainzID,
			&i.AlbumType,
			&i.Genres,
			&i.CoverPath,
			&i.ReleaseDate,
			&i.Label,
			&i.Country,
			&i.Barcode,
			&i.TotalTracks,
			&i.TotalDiscs,
			&i.Tags,
			&i.SearchVector,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTracksByAlbum = `-- name: ListTracksByAlbum :many
SELECT id, album_id, disc_number, track_number, title, duration_ms, file_path, search_vector FROM tracks WHERE album_id = $1 ORDER BY disc_number ASC, track_number ASC
`

func (q *Queries) ListTracksByAlbum(ctx context.Context, albumID int64) ([]Track, error) {
	rows, err := q.db.Query(ctx, listTracksByAlbum, albumID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Track{}
	for rows.Next() {
		var i Track
		if err := rows.Scan(
			&i.ID,
			&i.AlbumID,
			&i.DiscNumber,
			&i.TrackNumber,
			&i.Title,
			&i.DurationMs,
			&i.FilePath,
			&i.SearchVector,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAlbum = `-- name: UpdateAlbum :one
UPDATE albums
SET title = $2, year = $3, musicbrainz_id = $4, album_type = $5,
    genres = $6, cover_path = $7, release_date = $8,
    label = $9, country = $10, barcode = $11, total_tracks = $12, total_discs = $13, tags = $14
WHERE id = $1
RETURNING id, artist_id, title, year, musicbrainz_id, album_type, genres, cover_path, release_date, label, country, barcode, total_tracks, total_discs, tags, search_vector
`

type UpdateAlbumParams struct {
	ID            int64       `json:"id"`
	Title         string      `json:"title"`
	Year          string      `json:"year"`
	MusicbrainzID string      `json:"musicbrainz_id"`
	AlbumType     string      `json:"album_type"`
	Genres        []string    `json:"genres"`
	CoverPath     string      `json:"cover_path"`
	ReleaseDate   pgtype.Date `json:"release_date"`
	Label         string      `json:"label"`
	Country       string      `json:"country"`
	Barcode       string      `json:"barcode"`
	TotalTracks   int32       `json:"total_tracks"`
	TotalDiscs    int32       `json:"total_discs"`
	Tags          []string    `json:"tags"`
}

func (q *Queries) UpdateAlbum(ctx context.Context, arg UpdateAlbumParams) (Album, error) {
	row := q.db.QueryRow(ctx, updateAlbum,
		arg.ID,
		arg.Title,
		arg.Year,
		arg.MusicbrainzID,
		arg.AlbumType,
		arg.Genres,
		arg.CoverPath,
		arg.ReleaseDate,
		arg.Label,
		arg.Country,
		arg.Barcode,
		arg.TotalTracks,
		arg.TotalDiscs,
		arg.Tags,
	)
	var i Album
	err := row.Scan(
		&i.ID,
		&i.ArtistID,
		&i.Title,
		&i.Year,
		&i.MusicbrainzID,
		&i.AlbumType,
		&i.Genres,
		&i.CoverPath,
		&i.ReleaseDate,
		&i.Label,
		&i.Country,
		&i.Barcode,
		&i.TotalTracks,
		&i.TotalDiscs,
		&i.Tags,
		&i.SearchVector,
	)
	return i, err
}

const updateArtist = `-- name: UpdateArtist :one
UPDATE artists
SET musicbrainz_id = $2, sort_name = $3, biography = $4
WHERE id = $1
RETURNING id, media_item_id, musicbrainz_id, sort_name, biography, search_vector
`

type UpdateArtistParams struct {
	ID            int64  `json:"id"`
	MusicbrainzID string `json:"musicbrainz_id"`
	SortName      string `json:"sort_name"`
	Biography     string `json:"biography"`
}

func (q *Queries) UpdateArtist(ctx context.Context, arg UpdateArtistParams) (Artist, error) {
	row := q.db.QueryRow(ctx, updateArtist,
		arg.ID,
		arg.MusicbrainzID,
		arg.SortName,
		arg.Biography,
	)
	var i Artist
	err := row.Scan(
		&i.ID,
		&i.MediaItemID,
		&i.MusicbrainzID,
		&i.SortName,
		&i.Biography,
		&i.SearchVector,
	)
	return i, err
}
