// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: music_semantic.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countEmbeddedMusicCatalogRecordings = `-- name: CountEmbeddedMusicCatalogRecordings :one
SELECT count(*)::int
FROM music_recording_facets facet
JOIN music_catalog_recordings recording USING (recording_entity_id)
WHERE facet.text_embedding IS NOT NULL
  AND facet.embedder_version >= $1
  AND cardinality(recording.genres) + cardinality(recording.tags) + cardinality(recording.moods) +
      cardinality(recording.instrumentation) + cardinality(recording.vocal_characteristics) +
      cardinality(recording.recording_attributes) > 0
`

func (q *Queries) CountEmbeddedMusicCatalogRecordings(ctx context.Context, embedderVersion int32) (int32, error) {
	row := q.db.QueryRow(ctx, countEmbeddedMusicCatalogRecordings, embedderVersion)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const countMusicCatalogRecordings = `-- name: CountMusicCatalogRecordings :one
SELECT count(*)::int FROM music_catalog_recordings
WHERE cardinality(genres) + cardinality(tags) + cardinality(moods) +
      cardinality(instrumentation) + cardinality(vocal_characteristics) +
      cardinality(recording_attributes) > 0
`

func (q *Queries) CountMusicCatalogRecordings(ctx context.Context) (int32, error) {
	row := q.db.QueryRow(ctx, countMusicCatalogRecordings)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const listMusicCatalogArtistExpansionCandidates = `-- name: ListMusicCatalogArtistExpansionCandidates :many
WITH ranked AS (
    SELECT DISTINCT ON (relation.artist_id, relation.mbid)
           relation.artist_id AS source_artist_id,
           relation.mbid AS related_artist_mbid,
           relation.name AS related_artist_name,
           relation.rank
    FROM artist_similar_artists relation
    WHERE relation.mbid <> '' AND relation.local_artist_id IS NULL
    ORDER BY relation.artist_id, relation.mbid, relation.rank
)
SELECT ranked.source_artist_id, ranked.related_artist_mbid,
       ranked.related_artist_name
FROM ranked
LEFT JOIN music_catalog_artist_expansions expansion
  ON expansion.source_artist_id = ranked.source_artist_id
 AND expansion.related_artist_mbid = ranked.related_artist_mbid
WHERE expansion.source_artist_id IS NULL
   OR expansion.hydrated_at < now() - interval '30 days'
ORDER BY (expansion.source_artist_id IS NULL) DESC, ranked.rank, ranked.source_artist_id
LIMIT $1
`

type ListMusicCatalogArtistExpansionCandidatesRow struct {
	SourceArtistID    int64  `json:"source_artist_id"`
	RelatedArtistMbid string `json:"related_artist_mbid"`
	RelatedArtistName string `json:"related_artist_name"`
}

func (q *Queries) ListMusicCatalogArtistExpansionCandidates(ctx context.Context, limit int32) ([]ListMusicCatalogArtistExpansionCandidatesRow, error) {
	rows, err := q.db.Query(ctx, listMusicCatalogArtistExpansionCandidates, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMusicCatalogArtistExpansionCandidatesRow{}
	for rows.Next() {
		var i ListMusicCatalogArtistExpansionCandidatesRow
		if err := rows.Scan(&i.SourceArtistID, &i.RelatedArtistMbid, &i.RelatedArtistName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMusicCatalogEmbeddingRows = `-- name: ListMusicCatalogEmbeddingRows :many
SELECT recording_entity_id, genres, tags, moods, instrumentation,
       vocal_characteristics, recording_attributes
FROM music_catalog_recordings
ORDER BY recording_entity_id
`

type ListMusicCatalogEmbeddingRowsRow struct {
	RecordingEntityID    uuid.UUID `json:"recording_entity_id"`
	Genres               []string  `json:"genres"`
	Tags                 []string  `json:"tags"`
	Moods                []string  `json:"moods"`
	Instrumentation      []string  `json:"instrumentation"`
	VocalCharacteristics []string  `json:"vocal_characteristics"`
	RecordingAttributes  []string  `json:"recording_attributes"`
}

func (q *Queries) ListMusicCatalogEmbeddingRows(ctx context.Context) ([]ListMusicCatalogEmbeddingRowsRow, error) {
	rows, err := q.db.Query(ctx, listMusicCatalogEmbeddingRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMusicCatalogEmbeddingRowsRow{}
	for rows.Next() {
		var i ListMusicCatalogEmbeddingRowsRow
		if err := rows.Scan(
			&i.RecordingEntityID,
			&i.Genres,
			&i.Tags,
			&i.Moods,
			&i.Instrumentation,
			&i.VocalCharacteristics,
			&i.RecordingAttributes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMusicCatalogHydrationCandidates = `-- name: ListMusicCatalogHydrationCandidates :many
WITH candidates AS (
    SELECT top_track.recording_entity_id,
           top_track.artist_id AS source_artist_id,
           top_track.rank, top_track.provider, top_track.title,
           top_track.mbid, top_track.playcount, top_track.listeners,
           top_track.url
    FROM artist_top_tracks top_track
    WHERE top_track.recording_entity_id IS NOT NULL
    UNION ALL
    SELECT binding.entity_id,
           album.artist_id,
           0, 'library', track.title, track.recording_mbid, 0, 0, ''
    FROM metadata_entity_bindings binding
    JOIN tracks track ON binding.local_kind = 'track' AND binding.local_id = track.id
    JOIN albums album ON album.id = track.album_id
    WHERE binding.entity_kind = 'recording'
)
SELECT DISTINCT ON (candidate.recording_entity_id)
       candidate.recording_entity_id, candidate.source_artist_id,
       candidate.rank, candidate.provider, candidate.title, candidate.mbid,
       candidate.playcount, candidate.listeners, candidate.url
FROM candidates candidate
LEFT JOIN music_catalog_recordings catalog
  ON catalog.recording_entity_id = candidate.recording_entity_id
WHERE catalog.recording_entity_id IS NULL
ORDER BY candidate.recording_entity_id, candidate.rank ASC
LIMIT $1
`

type ListMusicCatalogHydrationCandidatesRow struct {
	RecordingEntityID pgtype.UUID `json:"recording_entity_id"`
	SourceArtistID    int64       `json:"source_artist_id"`
	Rank              int32       `json:"rank"`
	Provider          string      `json:"provider"`
	Title             string      `json:"title"`
	Mbid              string      `json:"mbid"`
	Playcount         int64       `json:"playcount"`
	Listeners         int64       `json:"listeners"`
	Url               string      `json:"url"`
}

func (q *Queries) ListMusicCatalogHydrationCandidates(ctx context.Context, limit int32) ([]ListMusicCatalogHydrationCandidatesRow, error) {
	rows, err := q.db.Query(ctx, listMusicCatalogHydrationCandidates, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMusicCatalogHydrationCandidatesRow{}
	for rows.Next() {
		var i ListMusicCatalogHydrationCandidatesRow
		if err := rows.Scan(
			&i.RecordingEntityID,
			&i.SourceArtistID,
			&i.Rank,
			&i.Provider,
			&i.Title,
			&i.Mbid,
			&i.Playcount,
			&i.Listeners,
			&i.Url,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markMusicCatalogArtistExpansion = `-- name: MarkMusicCatalogArtistExpansion :exec
INSERT INTO music_catalog_artist_expansions
  (source_artist_id, related_artist_mbid, related_artist_name, hydrated_at)
VALUES ($1, $2, $3, now())
ON CONFLICT (source_artist_id, related_artist_mbid) DO UPDATE SET
  related_artist_name = EXCLUDED.related_artist_name,
  hydrated_at = now()
`

type MarkMusicCatalogArtistExpansionParams struct {
	SourceArtistID    int64  `json:"source_artist_id"`
	RelatedArtistMbid string `json:"related_artist_mbid"`
	RelatedArtistName string `json:"related_artist_name"`
}

func (q *Queries) MarkMusicCatalogArtistExpansion(ctx context.Context, arg MarkMusicCatalogArtistExpansionParams) error {
	_, err := q.db.Exec(ctx, markMusicCatalogArtistExpansion, arg.SourceArtistID, arg.RelatedArtistMbid, arg.RelatedArtistName)
	return err
}

const upsertMusicCatalogRecording = `-- name: UpsertMusicCatalogRecording :exec
INSERT INTO music_catalog_recordings (
    recording_entity_id, recording_mbid, title, artist_name, source_artist_id,
    provider, provider_rank, provider_url, playcount, listeners,
    genres, tags, moods, instrumentation, vocal_characteristics,
    recording_attributes, refreshed_at
) VALUES (
    $1, $2, $3, $4, $5,
    $6, $7, $8, $9, $10,
    $11, $12, $13, $14, $15,
    $16, now()
)
ON CONFLICT (recording_entity_id) DO UPDATE SET
    recording_mbid = CASE WHEN EXCLUDED.recording_mbid <> '' THEN EXCLUDED.recording_mbid ELSE music_catalog_recordings.recording_mbid END,
    title = CASE WHEN EXCLUDED.title <> '' THEN EXCLUDED.title ELSE music_catalog_recordings.title END,
    artist_name = CASE WHEN EXCLUDED.artist_name <> '' THEN EXCLUDED.artist_name ELSE music_catalog_recordings.artist_name END,
    source_artist_id = COALESCE(EXCLUDED.source_artist_id, music_catalog_recordings.source_artist_id),
    provider = CASE WHEN EXCLUDED.provider <> '' THEN EXCLUDED.provider ELSE music_catalog_recordings.provider END,
    provider_rank = CASE WHEN EXCLUDED.provider_rank > 0 THEN EXCLUDED.provider_rank ELSE music_catalog_recordings.provider_rank END,
    provider_url = CASE WHEN EXCLUDED.provider_url <> '' THEN EXCLUDED.provider_url ELSE music_catalog_recordings.provider_url END,
    playcount = GREATEST(EXCLUDED.playcount, music_catalog_recordings.playcount),
    listeners = GREATEST(EXCLUDED.listeners, music_catalog_recordings.listeners),
    genres = EXCLUDED.genres,
    tags = EXCLUDED.tags,
    moods = EXCLUDED.moods,
    instrumentation = EXCLUDED.instrumentation,
    vocal_characteristics = EXCLUDED.vocal_characteristics,
    recording_attributes = EXCLUDED.recording_attributes,
    refreshed_at = now()
`

type UpsertMusicCatalogRecordingParams struct {
	RecordingEntityID    uuid.UUID   `json:"recording_entity_id"`
	RecordingMbid        string      `json:"recording_mbid"`
	Title                string      `json:"title"`
	ArtistName           string      `json:"artist_name"`
	SourceArtistID       pgtype.Int8 `json:"source_artist_id"`
	Provider             string      `json:"provider"`
	ProviderRank         int32       `json:"provider_rank"`
	ProviderUrl          string      `json:"provider_url"`
	Playcount            int64       `json:"playcount"`
	Listeners            int64       `json:"listeners"`
	Genres               []string    `json:"genres"`
	Tags                 []string    `json:"tags"`
	Moods                []string    `json:"moods"`
	Instrumentation      []string    `json:"instrumentation"`
	VocalCharacteristics []string    `json:"vocal_characteristics"`
	RecordingAttributes  []string    `json:"recording_attributes"`
}

func (q *Queries) UpsertMusicCatalogRecording(ctx context.Context, arg UpsertMusicCatalogRecordingParams) error {
	_, err := q.db.Exec(ctx, upsertMusicCatalogRecording,
		arg.RecordingEntityID,
		arg.RecordingMbid,
		arg.Title,
		arg.ArtistName,
		arg.SourceArtistID,
		arg.Provider,
		arg.ProviderRank,
		arg.ProviderUrl,
		arg.Playcount,
		arg.Listeners,
		arg.Genres,
		arg.Tags,
		arg.Moods,
		arg.Instrumentation,
		arg.VocalCharacteristics,
		arg.RecordingAttributes,
	)
	return err
}
