// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: music_home.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listAlbumsByArtistIDForShelf = `-- name: ListAlbumsByArtistIDForShelf :many
SELECT al.id, al.artist_id, al.title, al.slug, al.year, al.musicbrainz_id, al.album_type, al.genres, al.cover_path, al.release_date, al.label, al.country, al.barcode, al.total_tracks, al.total_discs, al.tags, al.integrated_lufs, al.true_peak_db, al.loudness_range_db, al.loudness_analyzed_at, al.search_vector, al.catalog_no, al.explicit, al.original_title, al.secondary_types, al.styles, al.language, al.duration_seconds, al.isrcs, al.rating, al.popularity, al.listeners, al.playcount, al.external_ids, al.artist_credits,
       a.name                                                   AS artist_name,
       mi.slug                                                  AS artist_slug,
       (SELECT count(*) FROM tracks t WHERE t.album_id = al.id) AS track_count
FROM albums al
JOIN artists     a  ON a.id  = al.artist_id
JOIN media_items mi ON mi.id = a.media_item_id
WHERE al.artist_id = $1
ORDER BY al.year DESC NULLS LAST, lower(al.title) ASC
LIMIT $2
`

type ListAlbumsByArtistIDForShelfParams struct {
	ArtistID int64 `json:"artist_id"`
	Limit    int32 `json:"limit"`
}

type ListAlbumsByArtistIDForShelfRow struct {
	ID                 int64              `json:"id"`
	ArtistID           int64              `json:"artist_id"`
	Title              string             `json:"title"`
	Slug               string             `json:"slug"`
	Year               string             `json:"year"`
	MusicbrainzID      string             `json:"musicbrainz_id"`
	AlbumType          string             `json:"album_type"`
	Genres             []string           `json:"genres"`
	CoverPath          string             `json:"cover_path"`
	ReleaseDate        pgtype.Date        `json:"release_date"`
	Label              string             `json:"label"`
	Country            string             `json:"country"`
	Barcode            string             `json:"barcode"`
	TotalTracks        int32              `json:"total_tracks"`
	TotalDiscs         int32              `json:"total_discs"`
	Tags               []string           `json:"tags"`
	IntegratedLufs     pgtype.Numeric     `json:"integrated_lufs"`
	TruePeakDb         pgtype.Numeric     `json:"true_peak_db"`
	LoudnessRangeDb    pgtype.Numeric     `json:"loudness_range_db"`
	LoudnessAnalyzedAt pgtype.Timestamptz `json:"loudness_analyzed_at"`
	SearchVector       interface{}        `json:"search_vector"`
	CatalogNo          string             `json:"catalog_no"`
	Explicit           bool               `json:"explicit"`
	OriginalTitle      string             `json:"original_title"`
	SecondaryTypes     []string           `json:"secondary_types"`
	Styles             []string           `json:"styles"`
	Language           string             `json:"language"`
	DurationSeconds    int32              `json:"duration_seconds"`
	Isrcs              []string           `json:"isrcs"`
	Rating             pgtype.Numeric     `json:"rating"`
	Popularity         int32              `json:"popularity"`
	Listeners          int64              `json:"listeners"`
	Playcount          int64              `json:"playcount"`
	ExternalIds        []byte             `json:"external_ids"`
	ArtistCredits      []byte             `json:"artist_credits"`
	ArtistName         string             `json:"artist_name"`
	ArtistSlug         string             `json:"artist_slug"`
	TrackCount         int64              `json:"track_count"`
}

// Helper for "More By Artist" — small per-artist album lists. Carries the
// shape the album-row component already speaks.
func (q *Queries) ListAlbumsByArtistIDForShelf(ctx context.Context, arg ListAlbumsByArtistIDForShelfParams) ([]ListAlbumsByArtistIDForShelfRow, error) {
	rows, err := q.db.Query(ctx, listAlbumsByArtistIDForShelf, arg.ArtistID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAlbumsByArtistIDForShelfRow{}
	for rows.Next() {
		var i ListAlbumsByArtistIDForShelfRow
		if err := rows.Scan(
			&i.ID,
			&i.ArtistID,
			&i.Title,
			&i.Slug,
			&i.Year,
			&i.MusicbrainzID,
			&i.AlbumType,
			&i.Genres,
			&i.CoverPath,
			&i.ReleaseDate,
			&i.Label,
			&i.Country,
			&i.Barcode,
			&i.TotalTracks,
			&i.TotalDiscs,
			&i.Tags,
			&i.IntegratedLufs,
			&i.TruePeakDb,
			&i.LoudnessRangeDb,
			&i.LoudnessAnalyzedAt,
			&i.SearchVector,
			&i.CatalogNo,
			&i.Explicit,
			&i.OriginalTitle,
			&i.SecondaryTypes,
			&i.Styles,
			&i.Language,
			&i.DurationSeconds,
			&i.Isrcs,
			&i.Rating,
			&i.Popularity,
			&i.Listeners,
			&i.Playcount,
			&i.ExternalIds,
			&i.ArtistCredits,
			&i.ArtistName,
			&i.ArtistSlug,
			&i.TrackCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAlbumsByLabel = `-- name: ListAlbumsByLabel :many
SELECT al.id              AS album_id,
       al.title           AS album_title,
       al.slug            AS album_slug,
       al.cover_path      AS album_cover_path,
       al.year            AS album_year,
       al.label           AS album_label,
       a.id               AS artist_id,
       a.name             AS artist_name,
       mi.slug            AS artist_slug
FROM albums al
JOIN artists     a  ON a.id  = al.artist_id
JOIN media_items mi ON mi.id = a.media_item_id
JOIN libraries   l  ON l.id  = mi.library_id
WHERE l.media_type = 'music'
  AND lower(al.label) = lower($2::text)
ORDER BY al.year DESC NULLS LAST, lower(al.title) ASC
LIMIT $1
`

type ListAlbumsByLabelParams struct {
	Limit int32  `json:"limit"`
	Label string `json:"label"`
}

type ListAlbumsByLabelRow struct {
	AlbumID        int64  `json:"album_id"`
	AlbumTitle     string `json:"album_title"`
	AlbumSlug      string `json:"album_slug"`
	AlbumCoverPath string `json:"album_cover_path"`
	AlbumYear      string `json:"album_year"`
	AlbumLabel     string `json:"album_label"`
	ArtistID       int64  `json:"artist_id"`
	ArtistName     string `json:"artist_name"`
	ArtistSlug     string `json:"artist_slug"`
}

// "More from <label>" — every album on the label. Carries artist context so
// one row can render "<album> — <artist>". Library-scoped to music so we
// don't accidentally cross-link from a soundtracks label into film items.
func (q *Queries) ListAlbumsByLabel(ctx context.Context, arg ListAlbumsByLabelParams) ([]ListAlbumsByLabelRow, error) {
	rows, err := q.db.Query(ctx, listAlbumsByLabel, arg.Limit, arg.Label)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAlbumsByLabelRow{}
	for rows.Next() {
		var i ListAlbumsByLabelRow
		if err := rows.Scan(
			&i.AlbumID,
			&i.AlbumTitle,
			&i.AlbumSlug,
			&i.AlbumCoverPath,
			&i.AlbumYear,
			&i.AlbumLabel,
			&i.ArtistID,
			&i.ArtistName,
			&i.ArtistSlug,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listArtistTopTracksForMix = `-- name: ListArtistTopTracksForMix :many
WITH ranked AS (
    SELECT t.id              AS track_id,
           t.title           AS track_title,
           t.duration        AS duration,
           t.disc_number     AS disc_number,
           t.track_number    AS track_number,
           al.id             AS album_id,
           al.title          AS album_title,
           al.slug           AS album_slug,
           al.cover_path     AS album_cover_path,
           al.year           AS album_year,
           a.id              AS artist_id,
           a.name            AS artist_name,
           mi.slug           AS artist_slug,
           (SELECT count(*) FROM play_events pe WHERE pe.track_id = t.id) AS play_count,
           row_number() OVER (PARTITION BY a.id ORDER BY (SELECT count(*) FROM play_events pe WHERE pe.track_id = t.id) DESC, t.id ASC) AS rn
    FROM tracks t
    JOIN albums      al ON al.id = t.album_id
    JOIN artists     a  ON a.id  = al.artist_id
    JOIN media_items mi ON mi.id = a.media_item_id
    WHERE a.id = ANY($2::bigint[])
)
SELECT track_id, track_title, duration, disc_number, track_number,
       album_id, album_title, album_slug, album_cover_path, album_year,
       artist_id, artist_name, artist_slug, play_count
FROM ranked
WHERE rn <= $1::int
`

type ListArtistTopTracksForMixParams struct {
	TracksPerArtist int32   `json:"tracks_per_artist"`
	ArtistIds       []int64 `json:"artist_ids"`
}

type ListArtistTopTracksForMixRow struct {
	TrackID        int64  `json:"track_id"`
	TrackTitle     string `json:"track_title"`
	Duration       int32  `json:"duration"`
	DiscNumber     int32  `json:"disc_number"`
	TrackNumber    int32  `json:"track_number"`
	AlbumID        int64  `json:"album_id"`
	AlbumTitle     string `json:"album_title"`
	AlbumSlug      string `json:"album_slug"`
	AlbumCoverPath string `json:"album_cover_path"`
	AlbumYear      string `json:"album_year"`
	ArtistID       int64  `json:"artist_id"`
	ArtistName     string `json:"artist_name"`
	ArtistSlug     string `json:"artist_slug"`
	PlayCount      int64  `json:"play_count"`
}

// Pulls the tracks that go into a mix for one seed artist's "neighborhood".
// Given a slice of artist_ids (the seed + its sonic neighbors), returns up
// to `tracks_per_artist` tracks per artist ordered by play_count desc.
// diversifyByArtist in the service shuffles them inter-artist so the mix
// doesn't run six tracks of the same artist back-to-back.
func (q *Queries) ListArtistTopTracksForMix(ctx context.Context, arg ListArtistTopTracksForMixParams) ([]ListArtistTopTracksForMixRow, error) {
	rows, err := q.db.Query(ctx, listArtistTopTracksForMix, arg.TracksPerArtist, arg.ArtistIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListArtistTopTracksForMixRow{}
	for rows.Next() {
		var i ListArtistTopTracksForMixRow
		if err := rows.Scan(
			&i.TrackID,
			&i.TrackTitle,
			&i.Duration,
			&i.DiscNumber,
			&i.TrackNumber,
			&i.AlbumID,
			&i.AlbumTitle,
			&i.AlbumSlug,
			&i.AlbumCoverPath,
			&i.AlbumYear,
			&i.ArtistID,
			&i.ArtistName,
			&i.ArtistSlug,
			&i.PlayCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listArtistTracksTopPlayedFirst = `-- name: ListArtistTracksTopPlayedFirst :many
SELECT t.id              AS track_id,
       t.title           AS track_title,
       t.duration        AS duration,
       t.disc_number     AS disc_number,
       t.track_number    AS track_number,
       al.id             AS album_id,
       al.title          AS album_title,
       al.slug           AS album_slug,
       al.cover_path     AS album_cover_path,
       al.year           AS album_year,
       a.id              AS artist_id,
       a.name            AS artist_name,
       mi.slug           AS artist_slug,
       (SELECT count(*) FROM play_events pe WHERE pe.track_id = t.id AND pe.user_id = $1)::bigint AS user_play_count
FROM tracks t
JOIN albums      al ON al.id = t.album_id
JOIN artists     a  ON a.id  = al.artist_id
JOIN media_items mi ON mi.id = a.media_item_id
WHERE mi.slug = $2
ORDER BY user_play_count DESC, al.year DESC NULLS LAST,
         t.disc_number ASC, t.track_number ASC
LIMIT $3
`

type ListArtistTracksTopPlayedFirstParams struct {
	UserID     int64  `json:"user_id"`
	Slug       string `json:"slug"`
	TrackLimit int32  `json:"track_limit"`
}

type ListArtistTracksTopPlayedFirstRow struct {
	TrackID        int64  `json:"track_id"`
	TrackTitle     string `json:"track_title"`
	Duration       int32  `json:"duration"`
	DiscNumber     int32  `json:"disc_number"`
	TrackNumber    int32  `json:"track_number"`
	AlbumID        int64  `json:"album_id"`
	AlbumTitle     string `json:"album_title"`
	AlbumSlug      string `json:"album_slug"`
	AlbumCoverPath string `json:"album_cover_path"`
	AlbumYear      string `json:"album_year"`
	ArtistID       int64  `json:"artist_id"`
	ArtistName     string `json:"artist_name"`
	ArtistSlug     string `json:"artist_slug"`
	UserPlayCount  int64  `json:"user_play_count"`
}

// Drives the "play this artist" button on home tiles. Returns every track the
// artist has, ordered by the user's play count desc (top hits first), then
// album year desc, then disc/track number — so the queue plays "best of" up
// front but still contains the full catalog for endless play-through.
func (q *Queries) ListArtistTracksTopPlayedFirst(ctx context.Context, arg ListArtistTracksTopPlayedFirstParams) ([]ListArtistTracksTopPlayedFirstRow, error) {
	rows, err := q.db.Query(ctx, listArtistTracksTopPlayedFirst, arg.UserID, arg.Slug, arg.TrackLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListArtistTracksTopPlayedFirstRow{}
	for rows.Next() {
		var i ListArtistTracksTopPlayedFirstRow
		if err := rows.Scan(
			&i.TrackID,
			&i.TrackTitle,
			&i.Duration,
			&i.DiscNumber,
			&i.TrackNumber,
			&i.AlbumID,
			&i.AlbumTitle,
			&i.AlbumSlug,
			&i.AlbumCoverPath,
			&i.AlbumYear,
			&i.ArtistID,
			&i.ArtistName,
			&i.ArtistSlug,
			&i.UserPlayCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listArtistsByGenre = `-- name: ListArtistsByGenre :many
SELECT DISTINCT a.id                                                                   AS artist_id,
                a.name                                                                  AS artist_name,
                mi.id                                                                   AS media_item_id,
                mi.slug                                                                 AS artist_slug,
                mi.poster_path                                                          AS poster_path,
                (SELECT count(*) FROM albums al2 WHERE al2.artist_id = a.id)            AS album_count,
                (SELECT count(*) FROM tracks t   JOIN albums al3 ON al3.id = t.album_id
                                                  WHERE al3.artist_id = a.id)           AS track_count
FROM artists a
JOIN albums       al ON al.artist_id = a.id
JOIN media_items  mi ON mi.id = a.media_item_id
JOIN libraries    l  ON l.id  = mi.library_id
WHERE l.media_type = 'music'
  AND $2::text = ANY(al.genres)
ORDER BY a.name ASC
LIMIT $1
`

type ListArtistsByGenreParams struct {
	Limit int32  `json:"limit"`
	Genre string `json:"genre"`
}

type ListArtistsByGenreRow struct {
	ArtistID    int64  `json:"artist_id"`
	ArtistName  string `json:"artist_name"`
	MediaItemID int64  `json:"media_item_id"`
	ArtistSlug  string `json:"artist_slug"`
	PosterPath  string `json:"poster_path"`
	AlbumCount  int64  `json:"album_count"`
	TrackCount  int64  `json:"track_count"`
}

// Artists whose albums include the given genre, library scoped to music.
// This drives the "More in <genre>" no-images list — the FE renders it as
// an artist-name list with album/track counts. The DISTINCT lift keeps one
// row per artist even when several of their albums share the genre.
func (q *Queries) ListArtistsByGenre(ctx context.Context, arg ListArtistsByGenreParams) ([]ListArtistsByGenreRow, error) {
	rows, err := q.db.Query(ctx, listArtistsByGenre, arg.Limit, arg.Genre)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListArtistsByGenreRow{}
	for rows.Next() {
		var i ListArtistsByGenreRow
		if err := rows.Scan(
			&i.ArtistID,
			&i.ArtistName,
			&i.MediaItemID,
			&i.ArtistSlug,
			&i.PosterPath,
			&i.AlbumCount,
			&i.TrackCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLapsedArtists = `-- name: ListLapsedArtists :many
WITH artist_last_played AS (
    SELECT a.id                                  AS artist_id,
           a.name                                AS artist_name,
           mi.id                                 AS media_item_id,
           mi.slug                               AS artist_slug,
           max(pe.played_at)::timestamptz        AS last_played_at,
           count(*)::bigint                      AS play_count
    FROM play_events pe
    JOIN tracks      t  ON t.id  = pe.track_id
    JOIN albums      al ON al.id = t.album_id
    JOIN artists     a  ON a.id  = al.artist_id
    JOIN media_items mi ON mi.id = a.media_item_id
    WHERE pe.user_id = $3
    GROUP BY a.id, a.name, mi.id, mi.slug
    HAVING max(pe.played_at) < $4
       AND count(*) >= $5
)
SELECT artist_id, artist_name, media_item_id, artist_slug, last_played_at, play_count
FROM artist_last_played
ORDER BY md5(artist_id::text || $1::text) ASC
LIMIT $2
`

type ListLapsedArtistsParams struct {
	Seed     string             `json:"seed"`
	Picks    int32              `json:"picks"`
	UserID   int64              `json:"user_id"`
	CutoffAt pgtype.Timestamptz `json:"cutoff_at"`
	MinPlays interface{}        `json:"min_plays"`
}

type ListLapsedArtistsRow struct {
	ArtistID     int64              `json:"artist_id"`
	ArtistName   string             `json:"artist_name"`
	MediaItemID  int64              `json:"media_item_id"`
	ArtistSlug   string             `json:"artist_slug"`
	LastPlayedAt pgtype.Timestamptz `json:"last_played_at"`
	PlayCount    int64              `json:"play_count"`
}

// Artists the user used to listen to but hasn't in `since_days`. The HAVING
// max(played_at) < cutoff is the lapsed-flag; we also require a minimum play
// count so a one-off play 6 months ago doesn't surface as "you used to love
// them". Stable randomization by md5(seed) for the 5-min rotation.
func (q *Queries) ListLapsedArtists(ctx context.Context, arg ListLapsedArtistsParams) ([]ListLapsedArtistsRow, error) {
	rows, err := q.db.Query(ctx, listLapsedArtists,
		arg.Seed,
		arg.Picks,
		arg.UserID,
		arg.CutoffAt,
		arg.MinPlays,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListLapsedArtistsRow{}
	for rows.Next() {
		var i ListLapsedArtistsRow
		if err := rows.Scan(
			&i.ArtistID,
			&i.ArtistName,
			&i.MediaItemID,
			&i.ArtistSlug,
			&i.LastPlayedAt,
			&i.PlayCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOnThisDayAlbums = `-- name: ListOnThisDayAlbums :many
SELECT al.id, al.artist_id, al.title, al.slug, al.year, al.musicbrainz_id, al.album_type, al.genres, al.cover_path, al.release_date, al.label, al.country, al.barcode, al.total_tracks, al.total_discs, al.tags, al.integrated_lufs, al.true_peak_db, al.loudness_range_db, al.loudness_analyzed_at, al.search_vector, al.catalog_no, al.explicit, al.original_title, al.secondary_types, al.styles, al.language, al.duration_seconds, al.isrcs, al.rating, al.popularity, al.listeners, al.playcount, al.external_ids, al.artist_credits,
       a.name                                                       AS artist_name,
       mi.slug                                                      AS artist_slug,
       (SELECT count(*) FROM tracks t WHERE t.album_id = al.id)     AS track_count,
       (EXTRACT(YEAR FROM al.release_date))::int                    AS release_year
FROM albums al
JOIN artists     a  ON a.id  = al.artist_id
JOIN media_items mi ON mi.id = a.media_item_id
JOIN libraries   l  ON l.id  = mi.library_id
WHERE l.media_type = 'music'
  AND al.release_date IS NOT NULL
  AND EXTRACT(MONTH FROM al.release_date) = EXTRACT(MONTH FROM CURRENT_DATE)
  AND EXTRACT(DAY   FROM al.release_date) = EXTRACT(DAY   FROM CURRENT_DATE)
ORDER BY al.release_date DESC
LIMIT $1
`

type ListOnThisDayAlbumsRow struct {
	ID                 int64              `json:"id"`
	ArtistID           int64              `json:"artist_id"`
	Title              string             `json:"title"`
	Slug               string             `json:"slug"`
	Year               string             `json:"year"`
	MusicbrainzID      string             `json:"musicbrainz_id"`
	AlbumType          string             `json:"album_type"`
	Genres             []string           `json:"genres"`
	CoverPath          string             `json:"cover_path"`
	ReleaseDate        pgtype.Date        `json:"release_date"`
	Label              string             `json:"label"`
	Country            string             `json:"country"`
	Barcode            string             `json:"barcode"`
	TotalTracks        int32              `json:"total_tracks"`
	TotalDiscs         int32              `json:"total_discs"`
	Tags               []string           `json:"tags"`
	IntegratedLufs     pgtype.Numeric     `json:"integrated_lufs"`
	TruePeakDb         pgtype.Numeric     `json:"true_peak_db"`
	LoudnessRangeDb    pgtype.Numeric     `json:"loudness_range_db"`
	LoudnessAnalyzedAt pgtype.Timestamptz `json:"loudness_analyzed_at"`
	SearchVector       interface{}        `json:"search_vector"`
	CatalogNo          string             `json:"catalog_no"`
	Explicit           bool               `json:"explicit"`
	OriginalTitle      string             `json:"original_title"`
	SecondaryTypes     []string           `json:"secondary_types"`
	Styles             []string           `json:"styles"`
	Language           string             `json:"language"`
	DurationSeconds    int32              `json:"duration_seconds"`
	Isrcs              []string           `json:"isrcs"`
	Rating             pgtype.Numeric     `json:"rating"`
	Popularity         int32              `json:"popularity"`
	Listeners          int64              `json:"listeners"`
	Playcount          int64              `json:"playcount"`
	ExternalIds        []byte             `json:"external_ids"`
	ArtistCredits      []byte             `json:"artist_credits"`
	ArtistName         string             `json:"artist_name"`
	ArtistSlug         string             `json:"artist_slug"`
	TrackCount         int64              `json:"track_count"`
	ReleaseYear        int32              `json:"release_year"`
}

// Anniversary releases — albums whose release_date month+day matches today.
// Ordered newest-year first so the user sees this-year-vs-decades-back at a
// glance. Falls back to nothing when albums lack release_date — that's
// expected for stub items not yet fully enriched.
func (q *Queries) ListOnThisDayAlbums(ctx context.Context, limit int32) ([]ListOnThisDayAlbumsRow, error) {
	rows, err := q.db.Query(ctx, listOnThisDayAlbums, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOnThisDayAlbumsRow{}
	for rows.Next() {
		var i ListOnThisDayAlbumsRow
		if err := rows.Scan(
			&i.ID,
			&i.ArtistID,
			&i.Title,
			&i.Slug,
			&i.Year,
			&i.MusicbrainzID,
			&i.AlbumType,
			&i.Genres,
			&i.CoverPath,
			&i.ReleaseDate,
			&i.Label,
			&i.Country,
			&i.Barcode,
			&i.TotalTracks,
			&i.TotalDiscs,
			&i.Tags,
			&i.IntegratedLufs,
			&i.TruePeakDb,
			&i.LoudnessRangeDb,
			&i.LoudnessAnalyzedAt,
			&i.SearchVector,
			&i.CatalogNo,
			&i.Explicit,
			&i.OriginalTitle,
			&i.SecondaryTypes,
			&i.Styles,
			&i.Language,
			&i.DurationSeconds,
			&i.Isrcs,
			&i.Rating,
			&i.Popularity,
			&i.Listeners,
			&i.Playcount,
			&i.ExternalIds,
			&i.ArtistCredits,
			&i.ArtistName,
			&i.ArtistSlug,
			&i.TrackCount,
			&i.ReleaseYear,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentUserPlaylists = `-- name: ListRecentUserPlaylists :many
WITH last_per_playlist AS (
    SELECT upt.playlist_id, max(pe.played_at) AS last_played_at
    FROM user_playlist_tracks upt
    LEFT JOIN play_events pe ON pe.track_id = upt.track_id AND pe.user_id = $1
    GROUP BY upt.playlist_id
)
SELECT up.id,
       up.name,
       up.description,
       up.cover_path,
       up.created_at,
       up.updated_at,
       coalesce(lpp.last_played_at, up.updated_at)                 AS last_activity_at,
       lpp.last_played_at                                          AS last_played_at,
       (SELECT count(*) FROM user_playlist_tracks WHERE playlist_id = up.id)::bigint AS track_count
FROM user_playlists up
LEFT JOIN last_per_playlist lpp ON lpp.playlist_id = up.id
WHERE up.user_id = $1
ORDER BY last_activity_at DESC, up.id DESC
LIMIT $2
`

type ListRecentUserPlaylistsParams struct {
	UserID int64 `json:"user_id"`
	Limit  int32 `json:"limit"`
}

type ListRecentUserPlaylistsRow struct {
	ID             int64              `json:"id"`
	Name           string             `json:"name"`
	Description    string             `json:"description"`
	CoverPath      string             `json:"cover_path"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	LastActivityAt interface{}        `json:"last_activity_at"`
	LastPlayedAt   interface{}        `json:"last_played_at"`
	TrackCount     int64              `json:"track_count"`
}

// Playlists ordered by the most recent play of any of their tracks (derived
// — there's no last_played_at column on user_playlists). Nulls land last,
// so freshly-created playlists show up below ones the user actually plays.
func (q *Queries) ListRecentUserPlaylists(ctx context.Context, arg ListRecentUserPlaylistsParams) ([]ListRecentUserPlaylistsRow, error) {
	rows, err := q.db.Query(ctx, listRecentUserPlaylists, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRecentUserPlaylistsRow{}
	for rows.Next() {
		var i ListRecentUserPlaylistsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.CoverPath,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LastActivityAt,
			&i.LastPlayedAt,
			&i.TrackCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentlyPlayedArtists = `-- name: ListRecentlyPlayedArtists :many

WITH artist_plays AS (
    SELECT DISTINCT ON (a.id)
           a.id                 AS artist_id,
           a.name               AS artist_name,
           mi.id                AS media_item_id,
           mi.slug              AS artist_slug,
           mi.poster_path       AS poster_path,
           pe.played_at         AS last_played_at,
           (SELECT count(*) FROM albums al WHERE al.artist_id = a.id) AS album_count,
           (SELECT count(*) FROM tracks t JOIN albums al ON al.id = t.album_id WHERE al.artist_id = a.id) AS track_count
    FROM play_events pe
    JOIN tracks      t  ON t.id  = pe.track_id
    JOIN albums      al ON al.id = t.album_id
    JOIN artists     a  ON a.id  = al.artist_id
    JOIN media_items mi ON mi.id = a.media_item_id
    WHERE pe.user_id = $1
    ORDER BY a.id, pe.played_at DESC
)
SELECT artist_id, artist_name, media_item_id, artist_slug, poster_path, last_played_at, album_count, track_count FROM artist_plays
ORDER BY last_played_at DESC
LIMIT $2
`

type ListRecentlyPlayedArtistsParams struct {
	UserID int64 `json:"user_id"`
	Limit  int32 `json:"limit"`
}

type ListRecentlyPlayedArtistsRow struct {
	ArtistID     int64              `json:"artist_id"`
	ArtistName   string             `json:"artist_name"`
	MediaItemID  int64              `json:"media_item_id"`
	ArtistSlug   string             `json:"artist_slug"`
	PosterPath   string             `json:"poster_path"`
	LastPlayedAt pgtype.Timestamptz `json:"last_played_at"`
	AlbumCount   int64              `json:"album_count"`
	TrackCount   int64              `json:"track_count"`
}

// Smart-home shelves powering the music landing page. The 10 sections each
// have their own query so the FE can refetch any one in isolation (the
// rotating shelves rotate themselves every 5 minutes; the others honor the
// standard cache TTL).
//
// All artist/album/track row shapes mirror ListMusicAlbums / ListMusicArtists
// so the FE can keep one row component per kind across the page.
// DISTINCT ON collapses repeats so a user who looped one artist's whole
// discography still sees diversity. last_played_at is the max(played_at)
// over any of that artist's tracks.
func (q *Queries) ListRecentlyPlayedArtists(ctx context.Context, arg ListRecentlyPlayedArtistsParams) ([]ListRecentlyPlayedArtistsRow, error) {
	rows, err := q.db.Query(ctx, listRecentlyPlayedArtists, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRecentlyPlayedArtistsRow{}
	for rows.Next() {
		var i ListRecentlyPlayedArtistsRow
		if err := rows.Scan(
			&i.ArtistID,
			&i.ArtistName,
			&i.MediaItemID,
			&i.ArtistSlug,
			&i.PosterPath,
			&i.LastPlayedAt,
			&i.AlbumCount,
			&i.TrackCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserSeedArtistsForMixes = `-- name: ListUserSeedArtistsForMixes :many
WITH ranked AS (
    SELECT a.id                AS artist_id,
           a.name              AS artist_name,
           mi.id               AS media_item_id,
           mi.slug             AS artist_slug,
           count(*)            AS play_count,
           max(pe.played_at)   AS last_played_at
    FROM play_events pe
    JOIN tracks      t  ON t.id  = pe.track_id
    JOIN albums      al ON al.id = t.album_id
    JOIN artists     a  ON a.id  = al.artist_id
    JOIN media_items mi ON mi.id = a.media_item_id
    WHERE pe.user_id = $2
      AND pe.played_at >= $3
    GROUP BY a.id, a.name, mi.id, mi.slug
)
SELECT artist_id, artist_name, media_item_id, artist_slug, play_count, last_played_at
FROM ranked
ORDER BY play_count DESC, last_played_at DESC
LIMIT $1
`

type ListUserSeedArtistsForMixesParams struct {
	Picks   int32              `json:"picks"`
	UserID  int64              `json:"user_id"`
	SinceAt pgtype.Timestamptz `json:"since_at"`
}

type ListUserSeedArtistsForMixesRow struct {
	ArtistID     int64       `json:"artist_id"`
	ArtistName   string      `json:"artist_name"`
	MediaItemID  int64       `json:"media_item_id"`
	ArtistSlug   string      `json:"artist_slug"`
	PlayCount    int64       `json:"play_count"`
	LastPlayedAt interface{} `json:"last_played_at"`
}

// "Mixes for You" seeds — top-N artists by play volume in the last `since_days`.
// Each row becomes one mix; the service then runs SimilarArtists against the
// artist_centroids index to flesh out the mix from sonic-similar artists.
func (q *Queries) ListUserSeedArtistsForMixes(ctx context.Context, arg ListUserSeedArtistsForMixesParams) ([]ListUserSeedArtistsForMixesRow, error) {
	rows, err := q.db.Query(ctx, listUserSeedArtistsForMixes, arg.Picks, arg.UserID, arg.SinceAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUserSeedArtistsForMixesRow{}
	for rows.Next() {
		var i ListUserSeedArtistsForMixesRow
		if err := rows.Scan(
			&i.ArtistID,
			&i.ArtistName,
			&i.MediaItemID,
			&i.ArtistSlug,
			&i.PlayCount,
			&i.LastPlayedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const mostPlayedAlbumsInRange = `-- name: MostPlayedAlbumsInRange :many
SELECT al.id              AS album_id,
       al.title           AS album_title,
       al.slug            AS album_slug,
       al.cover_path      AS album_cover_path,
       al.year            AS album_year,
       a.id               AS artist_id,
       a.name             AS artist_name,
       mi.slug            AS artist_slug,
       count(*)::bigint   AS play_count
FROM play_events pe
JOIN tracks      t  ON t.id  = pe.track_id
JOIN albums      al ON al.id = t.album_id
JOIN artists     a  ON a.id  = al.artist_id
JOIN media_items mi ON mi.id = a.media_item_id
WHERE pe.user_id = $1
  AND pe.played_at >= $3
  AND pe.played_at <  $4
GROUP BY al.id, al.title, al.slug, al.cover_path, al.year,
         a.id, a.name, mi.slug
ORDER BY play_count DESC, al.id DESC
LIMIT $2
`

type MostPlayedAlbumsInRangeParams struct {
	UserID  int64              `json:"user_id"`
	Limit   int32              `json:"limit"`
	StartAt pgtype.Timestamptz `json:"start_at"`
	EndAt   pgtype.Timestamptz `json:"end_at"`
}

type MostPlayedAlbumsInRangeRow struct {
	AlbumID        int64  `json:"album_id"`
	AlbumTitle     string `json:"album_title"`
	AlbumSlug      string `json:"album_slug"`
	AlbumCoverPath string `json:"album_cover_path"`
	AlbumYear      string `json:"album_year"`
	ArtistID       int64  `json:"artist_id"`
	ArtistName     string `json:"artist_name"`
	ArtistSlug     string `json:"artist_slug"`
	PlayCount      int64  `json:"play_count"`
}

// "Most Played in <month>" — albums ordered by # of play_events landing on
// their tracks in the given window. play_count is the per-album play volume
// in that window so the FE can render "Played 42×" as a subtitle.
func (q *Queries) MostPlayedAlbumsInRange(ctx context.Context, arg MostPlayedAlbumsInRangeParams) ([]MostPlayedAlbumsInRangeRow, error) {
	rows, err := q.db.Query(ctx, mostPlayedAlbumsInRange,
		arg.UserID,
		arg.Limit,
		arg.StartAt,
		arg.EndAt,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MostPlayedAlbumsInRangeRow{}
	for rows.Next() {
		var i MostPlayedAlbumsInRangeRow
		if err := rows.Scan(
			&i.AlbumID,
			&i.AlbumTitle,
			&i.AlbumSlug,
			&i.AlbumCoverPath,
			&i.AlbumYear,
			&i.ArtistID,
			&i.ArtistName,
			&i.ArtistSlug,
			&i.PlayCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pickLabelForUser = `-- name: PickLabelForUser :many
WITH user_labels AS (
    SELECT al.label, count(*) AS play_count
    FROM play_events pe
    JOIN tracks t   ON t.id  = pe.track_id
    JOIN albums al  ON al.id = t.album_id
    WHERE pe.user_id = $3
      AND al.label IS NOT NULL AND al.label != ''
    GROUP BY al.label
)
SELECT label, play_count
FROM user_labels
ORDER BY md5(label || $1::text) ASC
LIMIT $2
`

type PickLabelForUserParams struct {
	Seed   string `json:"seed"`
	Picks  int32  `json:"picks"`
	UserID int64  `json:"user_id"`
}

type PickLabelForUserRow struct {
	Label     string `json:"label"`
	PlayCount int64  `json:"play_count"`
}

// Sample N labels that the user actually listens to. Returns ordered by md5
// of (label, seed) so the rotation is stable within a window but varies
// across windows. Filters empty labels — many albums never get a label tag.
func (q *Queries) PickLabelForUser(ctx context.Context, arg PickLabelForUserParams) ([]PickLabelForUserRow, error) {
	rows, err := q.db.Query(ctx, pickLabelForUser, arg.Seed, arg.Picks, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PickLabelForUserRow{}
	for rows.Next() {
		var i PickLabelForUserRow
		if err := rows.Scan(&i.Label, &i.PlayCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pickRandomPlayedArtists = `-- name: PickRandomPlayedArtists :many
WITH artist_play_counts AS (
    SELECT a.id              AS artist_id,
           a.name            AS artist_name,
           mi.id             AS media_item_id,
           mi.slug           AS artist_slug,
           count(*)          AS play_count
    FROM play_events pe
    JOIN tracks  t  ON t.id  = pe.track_id
    JOIN albums  al ON al.id = t.album_id
    JOIN artists a  ON a.id  = al.artist_id
    JOIN media_items mi ON mi.id = a.media_item_id
    WHERE pe.user_id = $3
    GROUP BY a.id, a.name, mi.id, mi.slug
)
SELECT artist_id, artist_name, media_item_id, artist_slug, play_count
FROM artist_play_counts
ORDER BY md5(artist_id::text || $1::text) ASC
LIMIT $2
`

type PickRandomPlayedArtistsParams struct {
	Seed   string `json:"seed"`
	Picks  int32  `json:"picks"`
	UserID int64  `json:"user_id"`
}

type PickRandomPlayedArtistsRow struct {
	ArtistID    int64  `json:"artist_id"`
	ArtistName  string `json:"artist_name"`
	MediaItemID int64  `json:"media_item_id"`
	ArtistSlug  string `json:"artist_slug"`
	PlayCount   int64  `json:"play_count"`
}

// "More By" seeds — sample N artists from the user's play history with a
// stable seed so the same shelf survives a re-fetch within the 5-min window.
// md5() over the seed keeps the order deterministic per (user, time-bucket).
func (q *Queries) PickRandomPlayedArtists(ctx context.Context, arg PickRandomPlayedArtistsParams) ([]PickRandomPlayedArtistsRow, error) {
	rows, err := q.db.Query(ctx, pickRandomPlayedArtists, arg.Seed, arg.Picks, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PickRandomPlayedArtistsRow{}
	for rows.Next() {
		var i PickRandomPlayedArtistsRow
		if err := rows.Scan(
			&i.ArtistID,
			&i.ArtistName,
			&i.MediaItemID,
			&i.ArtistSlug,
			&i.PlayCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pickTopGenresForUser = `-- name: PickTopGenresForUser :many
SELECT (unnested_genre)::text AS genre,
       count(*)::bigint        AS play_count
FROM (
    SELECT unnest(al.genres) AS unnested_genre
    FROM play_events pe
    JOIN tracks  t  ON t.id  = pe.track_id
    JOIN albums  al ON al.id = t.album_id
    WHERE pe.user_id = $1
) sub
WHERE unnested_genre IS NOT NULL AND unnested_genre != ''
GROUP BY unnested_genre
ORDER BY play_count DESC
LIMIT $2
`

type PickTopGenresForUserParams struct {
	UserID int64 `json:"user_id"`
	Limit  int32 `json:"limit"`
}

type PickTopGenresForUserRow struct {
	Genre     string `json:"genre"`
	PlayCount int64  `json:"play_count"`
}

// Top genres derived from albums in user's play history (album.genres TEXT[]).
// Counts each play once per genre on the album so "metal" wins out over
// happens-to-be-tagged genres. UNNEST flattens the array; the seed in the
// service controls which one is picked for the rotating shelf.
func (q *Queries) PickTopGenresForUser(ctx context.Context, arg PickTopGenresForUserParams) ([]PickTopGenresForUserRow, error) {
	rows, err := q.db.Query(ctx, pickTopGenresForUser, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PickTopGenresForUserRow{}
	for rows.Next() {
		var i PickTopGenresForUserRow
		if err := rows.Scan(&i.Genre, &i.PlayCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
