// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: people.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createMediaCast = `-- name: CreateMediaCast :exec
INSERT INTO media_cast (media_item_id, person_id, character, display_order)
VALUES ($1, $2, $3, $4)
ON CONFLICT (media_item_id, person_id, character) DO NOTHING
`

type CreateMediaCastParams struct {
	MediaItemID  int64  `json:"media_item_id"`
	PersonID     int64  `json:"person_id"`
	Character    string `json:"character"`
	DisplayOrder int32  `json:"display_order"`
}

func (q *Queries) CreateMediaCast(ctx context.Context, arg CreateMediaCastParams) error {
	_, err := q.db.Exec(ctx, createMediaCast,
		arg.MediaItemID,
		arg.PersonID,
		arg.Character,
		arg.DisplayOrder,
	)
	return err
}

const createMediaCrew = `-- name: CreateMediaCrew :exec
INSERT INTO media_crew (media_item_id, person_id, job, department)
VALUES ($1, $2, $3, $4)
ON CONFLICT (media_item_id, person_id, job) DO NOTHING
`

type CreateMediaCrewParams struct {
	MediaItemID int64  `json:"media_item_id"`
	PersonID    int64  `json:"person_id"`
	Job         string `json:"job"`
	Department  string `json:"department"`
}

func (q *Queries) CreateMediaCrew(ctx context.Context, arg CreateMediaCrewParams) error {
	_, err := q.db.Exec(ctx, createMediaCrew,
		arg.MediaItemID,
		arg.PersonID,
		arg.Job,
		arg.Department,
	)
	return err
}

const createPerson = `-- name: CreatePerson :one
INSERT INTO people (tmdb_id, name, also_known_as, biography, birthday, deathday, place_of_birth, gender, profile_path, homepage, imdb_id, popularity)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
ON CONFLICT (tmdb_id) DO UPDATE SET
  name = EXCLUDED.name,
  also_known_as = EXCLUDED.also_known_as,
  biography = EXCLUDED.biography,
  birthday = EXCLUDED.birthday,
  deathday = EXCLUDED.deathday,
  place_of_birth = EXCLUDED.place_of_birth,
  gender = EXCLUDED.gender,
  profile_path = EXCLUDED.profile_path,
  homepage = EXCLUDED.homepage,
  imdb_id = EXCLUDED.imdb_id,
  popularity = EXCLUDED.popularity,
  updated_at = now()
RETURNING id, tmdb_id, name, also_known_as, biography, birthday, deathday, place_of_birth, gender, profile_path, homepage, imdb_id, popularity, created_at, updated_at
`

type CreatePersonParams struct {
	TmdbID       pgtype.Int4    `json:"tmdb_id"`
	Name         string         `json:"name"`
	AlsoKnownAs  []string       `json:"also_known_as"`
	Biography    string         `json:"biography"`
	Birthday     string         `json:"birthday"`
	Deathday     string         `json:"deathday"`
	PlaceOfBirth string         `json:"place_of_birth"`
	Gender       int32          `json:"gender"`
	ProfilePath  string         `json:"profile_path"`
	Homepage     string         `json:"homepage"`
	ImdbID       string         `json:"imdb_id"`
	Popularity   pgtype.Numeric `json:"popularity"`
}

func (q *Queries) CreatePerson(ctx context.Context, arg CreatePersonParams) (Person, error) {
	row := q.db.QueryRow(ctx, createPerson,
		arg.TmdbID,
		arg.Name,
		arg.AlsoKnownAs,
		arg.Biography,
		arg.Birthday,
		arg.Deathday,
		arg.PlaceOfBirth,
		arg.Gender,
		arg.ProfilePath,
		arg.Homepage,
		arg.ImdbID,
		arg.Popularity,
	)
	var i Person
	err := row.Scan(
		&i.ID,
		&i.TmdbID,
		&i.Name,
		&i.AlsoKnownAs,
		&i.Biography,
		&i.Birthday,
		&i.Deathday,
		&i.PlaceOfBirth,
		&i.Gender,
		&i.ProfilePath,
		&i.Homepage,
		&i.ImdbID,
		&i.Popularity,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPersonByTmdbID = `-- name: GetPersonByTmdbID :one
SELECT id, tmdb_id, name, also_known_as, biography, birthday, deathday, place_of_birth, gender, profile_path, homepage, imdb_id, popularity, created_at, updated_at FROM people WHERE tmdb_id = $1
`

func (q *Queries) GetPersonByTmdbID(ctx context.Context, tmdbID pgtype.Int4) (Person, error) {
	row := q.db.QueryRow(ctx, getPersonByTmdbID, tmdbID)
	var i Person
	err := row.Scan(
		&i.ID,
		&i.TmdbID,
		&i.Name,
		&i.AlsoKnownAs,
		&i.Biography,
		&i.Birthday,
		&i.Deathday,
		&i.PlaceOfBirth,
		&i.Gender,
		&i.ProfilePath,
		&i.Homepage,
		&i.ImdbID,
		&i.Popularity,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listMediaCast = `-- name: ListMediaCast :many
SELECT mc.character, mc.display_order, p.id, p.tmdb_id, p.name, p.also_known_as, p.biography, p.birthday, p.deathday, p.place_of_birth, p.gender, p.profile_path, p.homepage, p.imdb_id, p.popularity, p.created_at, p.updated_at
FROM media_cast mc
JOIN people p ON p.id = mc.person_id
WHERE mc.media_item_id = $1
ORDER BY mc.display_order
`

type ListMediaCastRow struct {
	Character    string             `json:"character"`
	DisplayOrder int32              `json:"display_order"`
	ID           int64              `json:"id"`
	TmdbID       pgtype.Int4        `json:"tmdb_id"`
	Name         string             `json:"name"`
	AlsoKnownAs  []string           `json:"also_known_as"`
	Biography    string             `json:"biography"`
	Birthday     string             `json:"birthday"`
	Deathday     string             `json:"deathday"`
	PlaceOfBirth string             `json:"place_of_birth"`
	Gender       int32              `json:"gender"`
	ProfilePath  string             `json:"profile_path"`
	Homepage     string             `json:"homepage"`
	ImdbID       string             `json:"imdb_id"`
	Popularity   pgtype.Numeric     `json:"popularity"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListMediaCast(ctx context.Context, mediaItemID int64) ([]ListMediaCastRow, error) {
	rows, err := q.db.Query(ctx, listMediaCast, mediaItemID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMediaCastRow{}
	for rows.Next() {
		var i ListMediaCastRow
		if err := rows.Scan(
			&i.Character,
			&i.DisplayOrder,
			&i.ID,
			&i.TmdbID,
			&i.Name,
			&i.AlsoKnownAs,
			&i.Biography,
			&i.Birthday,
			&i.Deathday,
			&i.PlaceOfBirth,
			&i.Gender,
			&i.ProfilePath,
			&i.Homepage,
			&i.ImdbID,
			&i.Popularity,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMediaCrew = `-- name: ListMediaCrew :many
SELECT mc.job, mc.department, p.id, p.tmdb_id, p.name, p.also_known_as, p.biography, p.birthday, p.deathday, p.place_of_birth, p.gender, p.profile_path, p.homepage, p.imdb_id, p.popularity, p.created_at, p.updated_at
FROM media_crew mc
JOIN people p ON p.id = mc.person_id
WHERE mc.media_item_id = $1
ORDER BY mc.department, mc.job
`

type ListMediaCrewRow struct {
	Job          string             `json:"job"`
	Department   string             `json:"department"`
	ID           int64              `json:"id"`
	TmdbID       pgtype.Int4        `json:"tmdb_id"`
	Name         string             `json:"name"`
	AlsoKnownAs  []string           `json:"also_known_as"`
	Biography    string             `json:"biography"`
	Birthday     string             `json:"birthday"`
	Deathday     string             `json:"deathday"`
	PlaceOfBirth string             `json:"place_of_birth"`
	Gender       int32              `json:"gender"`
	ProfilePath  string             `json:"profile_path"`
	Homepage     string             `json:"homepage"`
	ImdbID       string             `json:"imdb_id"`
	Popularity   pgtype.Numeric     `json:"popularity"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListMediaCrew(ctx context.Context, mediaItemID int64) ([]ListMediaCrewRow, error) {
	rows, err := q.db.Query(ctx, listMediaCrew, mediaItemID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMediaCrewRow{}
	for rows.Next() {
		var i ListMediaCrewRow
		if err := rows.Scan(
			&i.Job,
			&i.Department,
			&i.ID,
			&i.TmdbID,
			&i.Name,
			&i.AlsoKnownAs,
			&i.Biography,
			&i.Birthday,
			&i.Deathday,
			&i.PlaceOfBirth,
			&i.Gender,
			&i.ProfilePath,
			&i.Homepage,
			&i.ImdbID,
			&i.Popularity,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
