// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: playlists.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addTrackToPlaylist = `-- name: AddTrackToPlaylist :exec
INSERT INTO user_playlist_tracks (playlist_id, track_id, position)
VALUES (
    $1, $2,
    COALESCE((SELECT max(position) + 1 FROM user_playlist_tracks WHERE playlist_id = $1), 1)
)
ON CONFLICT (playlist_id, track_id) DO NOTHING
`

type AddTrackToPlaylistParams struct {
	PlaylistID int64 `json:"playlist_id"`
	TrackID    int64 `json:"track_id"`
}

func (q *Queries) AddTrackToPlaylist(ctx context.Context, arg AddTrackToPlaylistParams) error {
	_, err := q.db.Exec(ctx, addTrackToPlaylist, arg.PlaylistID, arg.TrackID)
	return err
}

const createUserPlaylist = `-- name: CreateUserPlaylist :one
INSERT INTO user_playlists (user_id, name, description, cover_path)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, name, description, cover_path, created_at, updated_at
`

type CreateUserPlaylistParams struct {
	UserID      int64  `json:"user_id"`
	Name        string `json:"name"`
	Description string `json:"description"`
	CoverPath   string `json:"cover_path"`
}

func (q *Queries) CreateUserPlaylist(ctx context.Context, arg CreateUserPlaylistParams) (UserPlaylist, error) {
	row := q.db.QueryRow(ctx, createUserPlaylist,
		arg.UserID,
		arg.Name,
		arg.Description,
		arg.CoverPath,
	)
	var i UserPlaylist
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Description,
		&i.CoverPath,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteUserPlaylist = `-- name: DeleteUserPlaylist :exec
DELETE FROM user_playlists WHERE id = $1 AND user_id = $2
`

type DeleteUserPlaylistParams struct {
	ID     int64 `json:"id"`
	UserID int64 `json:"user_id"`
}

func (q *Queries) DeleteUserPlaylist(ctx context.Context, arg DeleteUserPlaylistParams) error {
	_, err := q.db.Exec(ctx, deleteUserPlaylist, arg.ID, arg.UserID)
	return err
}

const getUserPlaylist = `-- name: GetUserPlaylist :one
SELECT id, user_id, name, description, cover_path, created_at, updated_at FROM user_playlists WHERE id = $1 AND user_id = $2
`

type GetUserPlaylistParams struct {
	ID     int64 `json:"id"`
	UserID int64 `json:"user_id"`
}

func (q *Queries) GetUserPlaylist(ctx context.Context, arg GetUserPlaylistParams) (UserPlaylist, error) {
	row := q.db.QueryRow(ctx, getUserPlaylist, arg.ID, arg.UserID)
	var i UserPlaylist
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Description,
		&i.CoverPath,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPlaylistTracks = `-- name: ListPlaylistTracks :many
SELECT t.id            AS track_id,
       t.title         AS track_title,
       t.duration      AS duration,
       t.disc_number   AS disc_number,
       t.track_number  AS track_number,
       al.id           AS album_id,
       al.title        AS album_title,
       al.cover_path   AS album_cover_path,
       al.year         AS album_year,
       al.slug         AS album_slug,
       a.id            AS artist_id,
       a.name          AS artist_name,
       mi.slug         AS artist_slug,
       upt.position    AS position,
       upt.added_at    AS added_at
FROM user_playlist_tracks upt
JOIN tracks      t  ON t.id  = upt.track_id
JOIN albums      al ON al.id = t.album_id
JOIN artists     a  ON a.id  = al.artist_id
JOIN media_items mi ON mi.id = a.media_item_id
WHERE upt.playlist_id = $1
ORDER BY upt.position ASC
`

type ListPlaylistTracksRow struct {
	TrackID        int64              `json:"track_id"`
	TrackTitle     string             `json:"track_title"`
	Duration       int32              `json:"duration"`
	DiscNumber     int32              `json:"disc_number"`
	TrackNumber    int32              `json:"track_number"`
	AlbumID        int64              `json:"album_id"`
	AlbumTitle     string             `json:"album_title"`
	AlbumCoverPath string             `json:"album_cover_path"`
	AlbumYear      string             `json:"album_year"`
	AlbumSlug      string             `json:"album_slug"`
	ArtistID       int64              `json:"artist_id"`
	ArtistName     string             `json:"artist_name"`
	ArtistSlug     string             `json:"artist_slug"`
	Position       int32              `json:"position"`
	AddedAt        pgtype.Timestamptz `json:"added_at"`
}

// Tracks in the playlist with full album + artist join so the playlist page
// renders in a single round trip.
func (q *Queries) ListPlaylistTracks(ctx context.Context, playlistID int64) ([]ListPlaylistTracksRow, error) {
	rows, err := q.db.Query(ctx, listPlaylistTracks, playlistID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPlaylistTracksRow{}
	for rows.Next() {
		var i ListPlaylistTracksRow
		if err := rows.Scan(
			&i.TrackID,
			&i.TrackTitle,
			&i.Duration,
			&i.DiscNumber,
			&i.TrackNumber,
			&i.AlbumID,
			&i.AlbumTitle,
			&i.AlbumCoverPath,
			&i.AlbumYear,
			&i.AlbumSlug,
			&i.ArtistID,
			&i.ArtistName,
			&i.ArtistSlug,
			&i.Position,
			&i.AddedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserPlaylists = `-- name: ListUserPlaylists :many
SELECT p.id, p.user_id, p.name, p.description, p.cover_path, p.created_at, p.updated_at,
       (SELECT count(*) FROM user_playlist_tracks WHERE playlist_id = p.id) AS track_count,
       COALESCE(
           (SELECT al.cover_path
            FROM user_playlist_tracks upt
            JOIN tracks t ON t.id = upt.track_id
            JOIN albums al ON al.id = t.album_id
            WHERE upt.playlist_id = p.id AND al.cover_path != ''
            ORDER BY upt.position ASC LIMIT 1),
           ''
       ) AS auto_cover
FROM user_playlists p
WHERE p.user_id = $1
ORDER BY p.created_at DESC
`

type ListUserPlaylistsRow struct {
	ID          int64              `json:"id"`
	UserID      int64              `json:"user_id"`
	Name        string             `json:"name"`
	Description string             `json:"description"`
	CoverPath   string             `json:"cover_path"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	TrackCount  int64              `json:"track_count"`
	AutoCover   interface{}        `json:"auto_cover"`
}

// Used by the sidebar — small payload, includes a synthesized cover (first
// track's album cover) and track count so the UI doesn't need follow-up calls.
func (q *Queries) ListUserPlaylists(ctx context.Context, userID int64) ([]ListUserPlaylistsRow, error) {
	rows, err := q.db.Query(ctx, listUserPlaylists, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUserPlaylistsRow{}
	for rows.Next() {
		var i ListUserPlaylistsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Description,
			&i.CoverPath,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TrackCount,
			&i.AutoCover,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeTrackFromPlaylist = `-- name: RemoveTrackFromPlaylist :exec
DELETE FROM user_playlist_tracks WHERE playlist_id = $1 AND track_id = $2
`

type RemoveTrackFromPlaylistParams struct {
	PlaylistID int64 `json:"playlist_id"`
	TrackID    int64 `json:"track_id"`
}

func (q *Queries) RemoveTrackFromPlaylist(ctx context.Context, arg RemoveTrackFromPlaylistParams) error {
	_, err := q.db.Exec(ctx, removeTrackFromPlaylist, arg.PlaylistID, arg.TrackID)
	return err
}

const reorderPlaylistTrack = `-- name: ReorderPlaylistTrack :exec
UPDATE user_playlist_tracks SET position = $3
WHERE playlist_id = $1 AND track_id = $2
`

type ReorderPlaylistTrackParams struct {
	PlaylistID int64 `json:"playlist_id"`
	TrackID    int64 `json:"track_id"`
	Position   int32 `json:"position"`
}

func (q *Queries) ReorderPlaylistTrack(ctx context.Context, arg ReorderPlaylistTrackParams) error {
	_, err := q.db.Exec(ctx, reorderPlaylistTrack, arg.PlaylistID, arg.TrackID, arg.Position)
	return err
}

const updateUserPlaylist = `-- name: UpdateUserPlaylist :exec
UPDATE user_playlists
SET name = $3, description = $4, cover_path = $5, updated_at = now()
WHERE id = $1 AND user_id = $2
`

type UpdateUserPlaylistParams struct {
	ID          int64  `json:"id"`
	UserID      int64  `json:"user_id"`
	Name        string `json:"name"`
	Description string `json:"description"`
	CoverPath   string `json:"cover_path"`
}

func (q *Queries) UpdateUserPlaylist(ctx context.Context, arg UpdateUserPlaylistParams) error {
	_, err := q.db.Exec(ctx, updateUserPlaylist,
		arg.ID,
		arg.UserID,
		arg.Name,
		arg.Description,
		arg.CoverPath,
	)
	return err
}
