// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: podcasts.sql

package sqlc

import (
	"context"
)

const addPodcastSubscription = `-- name: AddPodcastSubscription :one
INSERT INTO user_podcast_subscriptions (
    user_id, feed_url, title, author, artwork_url
) VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (user_id, feed_url) DO UPDATE SET
    title       = EXCLUDED.title,
    author      = EXCLUDED.author,
    artwork_url = EXCLUDED.artwork_url
RETURNING id, user_id, feed_url, title, author, artwork_url, last_episode_at, created_at
`

type AddPodcastSubscriptionParams struct {
	UserID     int64  `json:"user_id"`
	FeedUrl    string `json:"feed_url"`
	Title      string `json:"title"`
	Author     string `json:"author"`
	ArtworkUrl string `json:"artwork_url"`
}

// Upsert: re-subscribing refreshes the cached title/author/artwork rather
// than failing on the unique constraint.
func (q *Queries) AddPodcastSubscription(ctx context.Context, arg AddPodcastSubscriptionParams) (UserPodcastSubscription, error) {
	row := q.db.QueryRow(ctx, addPodcastSubscription,
		arg.UserID,
		arg.FeedUrl,
		arg.Title,
		arg.Author,
		arg.ArtworkUrl,
	)
	var i UserPodcastSubscription
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FeedUrl,
		&i.Title,
		&i.Author,
		&i.ArtworkUrl,
		&i.LastEpisodeAt,
		&i.CreatedAt,
	)
	return i, err
}

const getPodcastEpisodeProgress = `-- name: GetPodcastEpisodeProgress :one
SELECT id, user_id, feed_url, episode_guid, title, artwork_url, audio_url, progress_seconds, total_seconds, completed, updated_at FROM user_podcast_progress
WHERE user_id = $1 AND feed_url = $2 AND episode_guid = $3
`

type GetPodcastEpisodeProgressParams struct {
	UserID      int64  `json:"user_id"`
	FeedUrl     string `json:"feed_url"`
	EpisodeGuid string `json:"episode_guid"`
}

func (q *Queries) GetPodcastEpisodeProgress(ctx context.Context, arg GetPodcastEpisodeProgressParams) (UserPodcastProgress, error) {
	row := q.db.QueryRow(ctx, getPodcastEpisodeProgress, arg.UserID, arg.FeedUrl, arg.EpisodeGuid)
	var i UserPodcastProgress
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FeedUrl,
		&i.EpisodeGuid,
		&i.Title,
		&i.ArtworkUrl,
		&i.AudioUrl,
		&i.ProgressSeconds,
		&i.TotalSeconds,
		&i.Completed,
		&i.UpdatedAt,
	)
	return i, err
}

const isPodcastSubscribed = `-- name: IsPodcastSubscribed :one
SELECT EXISTS(
    SELECT 1 FROM user_podcast_subscriptions
    WHERE user_id = $1 AND feed_url = $2
)::bool AS subscribed
`

type IsPodcastSubscribedParams struct {
	UserID  int64  `json:"user_id"`
	FeedUrl string `json:"feed_url"`
}

func (q *Queries) IsPodcastSubscribed(ctx context.Context, arg IsPodcastSubscribedParams) (bool, error) {
	row := q.db.QueryRow(ctx, isPodcastSubscribed, arg.UserID, arg.FeedUrl)
	var subscribed bool
	err := row.Scan(&subscribed)
	return subscribed, err
}

const listPodcastContinue = `-- name: ListPodcastContinue :many
SELECT id, user_id, feed_url, episode_guid, title, artwork_url, audio_url, progress_seconds, total_seconds, completed, updated_at
FROM user_podcast_progress
WHERE user_id = $1 AND completed = false AND progress_seconds > 0
ORDER BY updated_at DESC
LIMIT $2
`

type ListPodcastContinueParams struct {
	UserID     int64 `json:"user_id"`
	TrackLimit int32 `json:"track_limit"`
}

// "Continue listening" — episodes the user started but didn't finish,
// newest activity first. Same indexed predicate as user_watch_progress
// so the partial index handles the filter cheaply.
func (q *Queries) ListPodcastContinue(ctx context.Context, arg ListPodcastContinueParams) ([]UserPodcastProgress, error) {
	rows, err := q.db.Query(ctx, listPodcastContinue, arg.UserID, arg.TrackLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UserPodcastProgress{}
	for rows.Next() {
		var i UserPodcastProgress
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.FeedUrl,
			&i.EpisodeGuid,
			&i.Title,
			&i.ArtworkUrl,
			&i.AudioUrl,
			&i.ProgressSeconds,
			&i.TotalSeconds,
			&i.Completed,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPodcastSubscriptions = `-- name: ListPodcastSubscriptions :many
SELECT id, user_id, feed_url, title, author, artwork_url, last_episode_at, created_at FROM user_podcast_subscriptions
WHERE user_id = $1
ORDER BY created_at DESC
`

// A user's subscribed feeds, newest-first.
func (q *Queries) ListPodcastSubscriptions(ctx context.Context, userID int64) ([]UserPodcastSubscription, error) {
	rows, err := q.db.Query(ctx, listPodcastSubscriptions, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UserPodcastSubscription{}
	for rows.Next() {
		var i UserPodcastSubscription
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.FeedUrl,
			&i.Title,
			&i.Author,
			&i.ArtworkUrl,
			&i.LastEpisodeAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removePodcastSubscription = `-- name: RemovePodcastSubscription :exec
DELETE FROM user_podcast_subscriptions
WHERE user_id = $1 AND feed_url = $2
`

type RemovePodcastSubscriptionParams struct {
	UserID  int64  `json:"user_id"`
	FeedUrl string `json:"feed_url"`
}

func (q *Queries) RemovePodcastSubscription(ctx context.Context, arg RemovePodcastSubscriptionParams) error {
	_, err := q.db.Exec(ctx, removePodcastSubscription, arg.UserID, arg.FeedUrl)
	return err
}

const upsertPodcastProgress = `-- name: UpsertPodcastProgress :one
INSERT INTO user_podcast_progress (
    user_id, feed_url, episode_guid, title, artwork_url, audio_url,
    progress_seconds, total_seconds, completed, updated_at
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, now())
ON CONFLICT (user_id, feed_url, episode_guid) DO UPDATE SET
    title            = EXCLUDED.title,
    artwork_url      = EXCLUDED.artwork_url,
    audio_url        = EXCLUDED.audio_url,
    progress_seconds = EXCLUDED.progress_seconds,
    total_seconds    = EXCLUDED.total_seconds,
    completed        = EXCLUDED.completed,
    updated_at       = now()
RETURNING id, user_id, feed_url, episode_guid, title, artwork_url, audio_url, progress_seconds, total_seconds, completed, updated_at
`

type UpsertPodcastProgressParams struct {
	UserID          int64  `json:"user_id"`
	FeedUrl         string `json:"feed_url"`
	EpisodeGuid     string `json:"episode_guid"`
	Title           string `json:"title"`
	ArtworkUrl      string `json:"artwork_url"`
	AudioUrl        string `json:"audio_url"`
	ProgressSeconds int32  `json:"progress_seconds"`
	TotalSeconds    int32  `json:"total_seconds"`
	Completed       bool   `json:"completed"`
}

// One row per (user, feed, episode) — same shape as user_watch_progress
// but for podcast episodes. Caller computes `completed` so the FE can mark
// an episode "done" whenever it wants (e.g. user hits the next button at
// the outro). progress_seconds=0 + completed=true means "I've heard this"
// without a position to resume from.
func (q *Queries) UpsertPodcastProgress(ctx context.Context, arg UpsertPodcastProgressParams) (UserPodcastProgress, error) {
	row := q.db.QueryRow(ctx, upsertPodcastProgress,
		arg.UserID,
		arg.FeedUrl,
		arg.EpisodeGuid,
		arg.Title,
		arg.ArtworkUrl,
		arg.AudioUrl,
		arg.ProgressSeconds,
		arg.TotalSeconds,
		arg.Completed,
	)
	var i UserPodcastProgress
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FeedUrl,
		&i.EpisodeGuid,
		&i.Title,
		&i.ArtworkUrl,
		&i.AudioUrl,
		&i.ProgressSeconds,
		&i.TotalSeconds,
		&i.Completed,
		&i.UpdatedAt,
	)
	return i, err
}
