// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ratings.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteExternalRatings = `-- name: DeleteExternalRatings :exec
DELETE FROM external_ratings WHERE media_item_id = $1
`

func (q *Queries) DeleteExternalRatings(ctx context.Context, mediaItemID int64) error {
	_, err := q.db.Exec(ctx, deleteExternalRatings, mediaItemID)
	return err
}

const listExternalRatings = `-- name: ListExternalRatings :many
SELECT id, media_item_id, source, value, score, votes, raw_value FROM external_ratings WHERE media_item_id = $1
`

func (q *Queries) ListExternalRatings(ctx context.Context, mediaItemID int64) ([]ExternalRating, error) {
	rows, err := q.db.Query(ctx, listExternalRatings, mediaItemID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ExternalRating{}
	for rows.Next() {
		var i ExternalRating
		if err := rows.Scan(
			&i.ID,
			&i.MediaItemID,
			&i.Source,
			&i.Value,
			&i.Score,
			&i.Votes,
			&i.RawValue,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertExternalRating = `-- name: UpsertExternalRating :one
INSERT INTO external_ratings (media_item_id, source, value, score, votes, raw_value)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (media_item_id, source) DO UPDATE SET value = $3, score = $4, votes = $5, raw_value = $6
RETURNING id, media_item_id, source, value, score, votes, raw_value
`

type UpsertExternalRatingParams struct {
	MediaItemID int64          `json:"media_item_id"`
	Source      string         `json:"source"`
	Value       string         `json:"value"`
	Score       pgtype.Numeric `json:"score"`
	Votes       int32          `json:"votes"`
	RawValue    string         `json:"raw_value"`
}

func (q *Queries) UpsertExternalRating(ctx context.Context, arg UpsertExternalRatingParams) (ExternalRating, error) {
	row := q.db.QueryRow(ctx, upsertExternalRating,
		arg.MediaItemID,
		arg.Source,
		arg.Value,
		arg.Score,
		arg.Votes,
		arg.RawValue,
	)
	var i ExternalRating
	err := row.Scan(
		&i.ID,
		&i.MediaItemID,
		&i.Source,
		&i.Value,
		&i.Score,
		&i.Votes,
		&i.RawValue,
	)
	return i, err
}
