// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: recommendations.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createMediaRecommendation = `-- name: CreateMediaRecommendation :exec
INSERT INTO media_recommendations (media_item_id, recommended_tmdb_id, title, poster_path, media_type, vote_average, release_date)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (media_item_id, recommended_tmdb_id) DO UPDATE SET
  title = EXCLUDED.title,
  poster_path = EXCLUDED.poster_path,
  vote_average = EXCLUDED.vote_average
`

type CreateMediaRecommendationParams struct {
	MediaItemID       int64          `json:"media_item_id"`
	RecommendedTmdbID int32          `json:"recommended_tmdb_id"`
	Title             string         `json:"title"`
	PosterPath        string         `json:"poster_path"`
	MediaType         string         `json:"media_type"`
	VoteAverage       pgtype.Numeric `json:"vote_average"`
	ReleaseDate       string         `json:"release_date"`
}

func (q *Queries) CreateMediaRecommendation(ctx context.Context, arg CreateMediaRecommendationParams) error {
	_, err := q.db.Exec(ctx, createMediaRecommendation,
		arg.MediaItemID,
		arg.RecommendedTmdbID,
		arg.Title,
		arg.PosterPath,
		arg.MediaType,
		arg.VoteAverage,
		arg.ReleaseDate,
	)
	return err
}

const listMediaRecommendations = `-- name: ListMediaRecommendations :many
SELECT id, media_item_id, recommended_tmdb_id, title, poster_path, media_type, vote_average, release_date FROM media_recommendations WHERE media_item_id = $1 ORDER BY vote_average DESC
`

func (q *Queries) ListMediaRecommendations(ctx context.Context, mediaItemID int64) ([]MediaRecommendation, error) {
	rows, err := q.db.Query(ctx, listMediaRecommendations, mediaItemID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MediaRecommendation{}
	for rows.Next() {
		var i MediaRecommendation
		if err := rows.Scan(
			&i.ID,
			&i.MediaItemID,
			&i.RecommendedTmdbID,
			&i.Title,
			&i.PosterPath,
			&i.MediaType,
			&i.VoteAverage,
			&i.ReleaseDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMediaRecommendationsWithLibrary = `-- name: ListMediaRecommendationsWithLibrary :many
SELECT mr.id, mr.media_item_id, mr.recommended_tmdb_id, mr.title, mr.poster_path, mr.media_type, mr.vote_average, mr.release_date,
  mi.id as local_media_item_id,
  mi.poster_path as local_poster_path
FROM media_recommendations mr
LEFT JOIN media_items mi ON mi.external_ids::jsonb @> jsonb_build_object('tmdb', mr.recommended_tmdb_id::text)
WHERE mr.media_item_id = $1
ORDER BY (mi.id IS NOT NULL) DESC, mr.vote_average DESC
`

type ListMediaRecommendationsWithLibraryRow struct {
	ID                int64          `json:"id"`
	MediaItemID       int64          `json:"media_item_id"`
	RecommendedTmdbID int32          `json:"recommended_tmdb_id"`
	Title             string         `json:"title"`
	PosterPath        string         `json:"poster_path"`
	MediaType         string         `json:"media_type"`
	VoteAverage       pgtype.Numeric `json:"vote_average"`
	ReleaseDate       string         `json:"release_date"`
	LocalMediaItemID  pgtype.Int8    `json:"local_media_item_id"`
	LocalPosterPath   pgtype.Text    `json:"local_poster_path"`
}

func (q *Queries) ListMediaRecommendationsWithLibrary(ctx context.Context, mediaItemID int64) ([]ListMediaRecommendationsWithLibraryRow, error) {
	rows, err := q.db.Query(ctx, listMediaRecommendationsWithLibrary, mediaItemID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMediaRecommendationsWithLibraryRow{}
	for rows.Next() {
		var i ListMediaRecommendationsWithLibraryRow
		if err := rows.Scan(
			&i.ID,
			&i.MediaItemID,
			&i.RecommendedTmdbID,
			&i.Title,
			&i.PosterPath,
			&i.MediaType,
			&i.VoteAverage,
			&i.ReleaseDate,
			&i.LocalMediaItemID,
			&i.LocalPosterPath,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
