// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: recommendations.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createMediaRecommendation = `-- name: CreateMediaRecommendation :exec
INSERT INTO media_recommendations (media_item_id, external_ids, title, poster_path, media_type, vote_average, release_date)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (media_item_id, title, media_type) DO UPDATE SET
  external_ids = EXCLUDED.external_ids,
  poster_path = EXCLUDED.poster_path,
  vote_average = EXCLUDED.vote_average
`

type CreateMediaRecommendationParams struct {
	MediaItemID int64          `json:"media_item_id"`
	ExternalIds []byte         `json:"external_ids"`
	Title       string         `json:"title"`
	PosterPath  string         `json:"poster_path"`
	MediaType   string         `json:"media_type"`
	VoteAverage pgtype.Numeric `json:"vote_average"`
	ReleaseDate string         `json:"release_date"`
}

func (q *Queries) CreateMediaRecommendation(ctx context.Context, arg CreateMediaRecommendationParams) error {
	_, err := q.db.Exec(ctx, createMediaRecommendation,
		arg.MediaItemID,
		arg.ExternalIds,
		arg.Title,
		arg.PosterPath,
		arg.MediaType,
		arg.VoteAverage,
		arg.ReleaseDate,
	)
	return err
}

const deleteMediaRecommendationsByItem = `-- name: DeleteMediaRecommendationsByItem :exec
DELETE FROM media_recommendations WHERE media_item_id = $1
`

func (q *Queries) DeleteMediaRecommendationsByItem(ctx context.Context, mediaItemID int64) error {
	_, err := q.db.Exec(ctx, deleteMediaRecommendationsByItem, mediaItemID)
	return err
}

const listMediaRecommendations = `-- name: ListMediaRecommendations :many
SELECT id, media_item_id, external_ids, title, poster_path, media_type, vote_average, release_date FROM media_recommendations WHERE media_item_id = $1 ORDER BY vote_average DESC
`

func (q *Queries) ListMediaRecommendations(ctx context.Context, mediaItemID int64) ([]MediaRecommendation, error) {
	rows, err := q.db.Query(ctx, listMediaRecommendations, mediaItemID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MediaRecommendation{}
	for rows.Next() {
		var i MediaRecommendation
		if err := rows.Scan(
			&i.ID,
			&i.MediaItemID,
			&i.ExternalIds,
			&i.Title,
			&i.PosterPath,
			&i.MediaType,
			&i.VoteAverage,
			&i.ReleaseDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMediaRecommendationsWithLibrary = `-- name: ListMediaRecommendationsWithLibrary :many
SELECT mr.id, mr.media_item_id, mr.external_ids, mr.title, mr.poster_path, mr.media_type, mr.vote_average, mr.release_date,
  COALESCE(mi.id, 0)::bigint as local_media_item_id,
  COALESCE(mi.slug, '')::text as local_slug,
  COALESCE(mi.poster_path, '')::text as local_poster_path
FROM media_recommendations mr
LEFT JOIN LATERAL (
  SELECT local_mi.id, local_mi.slug, local_mi.poster_path
  FROM jsonb_each_text(mr.external_ids) AS wanted(provider, external_id)
  JOIN media_item_external_ids ei
    ON ei.provider = wanted.provider
   AND ei.external_id = wanted.external_id
  JOIN media_item_cards local_mi ON local_mi.id = ei.media_item_id
  WHERE mr.external_ids != '{}'
    AND wanted.provider IN ('tmdb', 'imdb', 'tvdb')
  ORDER BY CASE wanted.provider WHEN 'tmdb' THEN 0 WHEN 'imdb' THEN 1 WHEN 'tvdb' THEN 2 ELSE 3 END,
           local_mi.id
  LIMIT 1
) mi ON true
WHERE mr.media_item_id = $1
ORDER BY (mi.id IS NOT NULL) DESC, mr.vote_average DESC
`

type ListMediaRecommendationsWithLibraryRow struct {
	ID               int64          `json:"id"`
	MediaItemID      int64          `json:"media_item_id"`
	ExternalIds      []byte         `json:"external_ids"`
	Title            string         `json:"title"`
	PosterPath       string         `json:"poster_path"`
	MediaType        string         `json:"media_type"`
	VoteAverage      pgtype.Numeric `json:"vote_average"`
	ReleaseDate      string         `json:"release_date"`
	LocalMediaItemID int64          `json:"local_media_item_id"`
	LocalSlug        string         `json:"local_slug"`
	LocalPosterPath  string         `json:"local_poster_path"`
}

func (q *Queries) ListMediaRecommendationsWithLibrary(ctx context.Context, mediaItemID int64) ([]ListMediaRecommendationsWithLibraryRow, error) {
	rows, err := q.db.Query(ctx, listMediaRecommendationsWithLibrary, mediaItemID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMediaRecommendationsWithLibraryRow{}
	for rows.Next() {
		var i ListMediaRecommendationsWithLibraryRow
		if err := rows.Scan(
			&i.ID,
			&i.MediaItemID,
			&i.ExternalIds,
			&i.Title,
			&i.PosterPath,
			&i.MediaType,
			&i.VoteAverage,
			&i.ReleaseDate,
			&i.LocalMediaItemID,
			&i.LocalSlug,
			&i.LocalPosterPath,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTopRecommendations = `-- name: ListTopRecommendations :many
WITH agg AS (
  SELECT mr.external_ids, mr.title, mr.poster_path, mr.media_type, mr.vote_average, mr.release_date,
         count(*)::int AS source_count
  FROM media_recommendations mr
  GROUP BY mr.external_ids, mr.title, mr.poster_path, mr.media_type, mr.vote_average, mr.release_date
  ORDER BY count(*) DESC, mr.vote_average DESC
  LIMIT $1
)
SELECT agg.external_ids, agg.title, agg.poster_path, agg.media_type, agg.vote_average, agg.release_date,
  COALESCE(mi.id, 0)::bigint as local_media_item_id,
  COALESCE(mi.slug, '')::text as local_slug,
  COALESCE(mi.poster_path, '')::text as local_poster_path,
  agg.source_count
FROM agg
LEFT JOIN LATERAL (
  SELECT local_mi.id, local_mi.slug, local_mi.poster_path
  FROM jsonb_each_text(agg.external_ids) AS wanted(provider, external_id)
  JOIN media_item_external_ids ei
    ON ei.provider = wanted.provider
   AND ei.external_id = wanted.external_id
  JOIN media_item_cards local_mi ON local_mi.id = ei.media_item_id
  WHERE agg.external_ids != '{}'
    AND wanted.provider IN ('tmdb', 'imdb', 'tvdb')
  ORDER BY CASE wanted.provider WHEN 'tmdb' THEN 0 WHEN 'imdb' THEN 1 WHEN 'tvdb' THEN 2 ELSE 3 END,
           local_mi.id
  LIMIT 1
) mi ON true
ORDER BY agg.source_count DESC, agg.vote_average DESC
`

type ListTopRecommendationsRow struct {
	ExternalIds      []byte         `json:"external_ids"`
	Title            string         `json:"title"`
	PosterPath       string         `json:"poster_path"`
	MediaType        string         `json:"media_type"`
	VoteAverage      pgtype.Numeric `json:"vote_average"`
	ReleaseDate      string         `json:"release_date"`
	LocalMediaItemID int64          `json:"local_media_item_id"`
	LocalSlug        string         `json:"local_slug"`
	LocalPosterPath  string         `json:"local_poster_path"`
	SourceCount      int32          `json:"source_count"`
}

// Top recommendations for home page: items recommended by multiple sources,
// weighted by vote. Aggregate media_recommendations alone first, then join
// media_items only for the top-N groups — the inlined form ran one GIN probe
// per rec row (30k) and count(DISTINCT) forced a 30k-row jsonb-keyed sort
// (~900ms vs ~35ms). count(*) is equivalent to count(DISTINCT media_item_id):
// the UNIQUE (media_item_id, title, media_type) constraint (which the upsert
// in CreateMediaRecommendation depends on) plus title/media_type in the GROUP
// BY means one media_item_id can't repeat within a group.
func (q *Queries) ListTopRecommendations(ctx context.Context, limit int32) ([]ListTopRecommendationsRow, error) {
	rows, err := q.db.Query(ctx, listTopRecommendations, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTopRecommendationsRow{}
	for rows.Next() {
		var i ListTopRecommendationsRow
		if err := rows.Scan(
			&i.ExternalIds,
			&i.Title,
			&i.PosterPath,
			&i.MediaType,
			&i.VoteAverage,
			&i.ReleaseDate,
			&i.LocalMediaItemID,
			&i.LocalSlug,
			&i.LocalPosterPath,
			&i.SourceCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
