// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: scheduled_tasks.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getScheduledTask = `-- name: GetScheduledTask :one
SELECT id, display_name, description, category, enabled, interval_hours, daily_start_time, daily_end_time, max_runtime_minutes, last_run_at, last_run_result, last_run_duration_sec, last_run_items_processed, last_run_items_total, next_run_at, created_at, updated_at FROM scheduled_tasks WHERE id = $1
`

func (q *Queries) GetScheduledTask(ctx context.Context, id string) (ScheduledTask, error) {
	row := q.db.QueryRow(ctx, getScheduledTask, id)
	var i ScheduledTask
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.Description,
		&i.Category,
		&i.Enabled,
		&i.IntervalHours,
		&i.DailyStartTime,
		&i.DailyEndTime,
		&i.MaxRuntimeMinutes,
		&i.LastRunAt,
		&i.LastRunResult,
		&i.LastRunDurationSec,
		&i.LastRunItemsProcessed,
		&i.LastRunItemsTotal,
		&i.NextRunAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listScheduledTasks = `-- name: ListScheduledTasks :many
SELECT id, display_name, description, category, enabled, interval_hours, daily_start_time, daily_end_time, max_runtime_minutes, last_run_at, last_run_result, last_run_duration_sec, last_run_items_processed, last_run_items_total, next_run_at, created_at, updated_at FROM scheduled_tasks ORDER BY category, display_name
`

func (q *Queries) ListScheduledTasks(ctx context.Context) ([]ScheduledTask, error) {
	rows, err := q.db.Query(ctx, listScheduledTasks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ScheduledTask{}
	for rows.Next() {
		var i ScheduledTask
		if err := rows.Scan(
			&i.ID,
			&i.DisplayName,
			&i.Description,
			&i.Category,
			&i.Enabled,
			&i.IntervalHours,
			&i.DailyStartTime,
			&i.DailyEndTime,
			&i.MaxRuntimeMinutes,
			&i.LastRunAt,
			&i.LastRunResult,
			&i.LastRunDurationSec,
			&i.LastRunItemsProcessed,
			&i.LastRunItemsTotal,
			&i.NextRunAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateScheduledTaskConfig = `-- name: UpdateScheduledTaskConfig :one
UPDATE scheduled_tasks
SET enabled = $2, interval_hours = $3,
    daily_start_time = $4, daily_end_time = $5,
    max_runtime_minutes = $6, updated_at = now()
WHERE id = $1 RETURNING id, display_name, description, category, enabled, interval_hours, daily_start_time, daily_end_time, max_runtime_minutes, last_run_at, last_run_result, last_run_duration_sec, last_run_items_processed, last_run_items_total, next_run_at, created_at, updated_at
`

type UpdateScheduledTaskConfigParams struct {
	ID                string `json:"id"`
	Enabled           bool   `json:"enabled"`
	IntervalHours     int32  `json:"interval_hours"`
	DailyStartTime    string `json:"daily_start_time"`
	DailyEndTime      string `json:"daily_end_time"`
	MaxRuntimeMinutes int32  `json:"max_runtime_minutes"`
}

func (q *Queries) UpdateScheduledTaskConfig(ctx context.Context, arg UpdateScheduledTaskConfigParams) (ScheduledTask, error) {
	row := q.db.QueryRow(ctx, updateScheduledTaskConfig,
		arg.ID,
		arg.Enabled,
		arg.IntervalHours,
		arg.DailyStartTime,
		arg.DailyEndTime,
		arg.MaxRuntimeMinutes,
	)
	var i ScheduledTask
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.Description,
		&i.Category,
		&i.Enabled,
		&i.IntervalHours,
		&i.DailyStartTime,
		&i.DailyEndTime,
		&i.MaxRuntimeMinutes,
		&i.LastRunAt,
		&i.LastRunResult,
		&i.LastRunDurationSec,
		&i.LastRunItemsProcessed,
		&i.LastRunItemsTotal,
		&i.NextRunAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateScheduledTaskRun = `-- name: UpdateScheduledTaskRun :exec
UPDATE scheduled_tasks
SET last_run_at = $2, last_run_result = $3, last_run_duration_sec = $4,
    last_run_items_processed = $5, last_run_items_total = $6,
    next_run_at = $7, updated_at = now()
WHERE id = $1
`

type UpdateScheduledTaskRunParams struct {
	ID                    string             `json:"id"`
	LastRunAt             pgtype.Timestamptz `json:"last_run_at"`
	LastRunResult         string             `json:"last_run_result"`
	LastRunDurationSec    int32              `json:"last_run_duration_sec"`
	LastRunItemsProcessed int32              `json:"last_run_items_processed"`
	LastRunItemsTotal     int32              `json:"last_run_items_total"`
	NextRunAt             pgtype.Timestamptz `json:"next_run_at"`
}

func (q *Queries) UpdateScheduledTaskRun(ctx context.Context, arg UpdateScheduledTaskRunParams) error {
	_, err := q.db.Exec(ctx, updateScheduledTaskRun,
		arg.ID,
		arg.LastRunAt,
		arg.LastRunResult,
		arg.LastRunDurationSec,
		arg.LastRunItemsProcessed,
		arg.LastRunItemsTotal,
		arg.NextRunAt,
	)
	return err
}
