// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: search.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const searchAlbums = `-- name: SearchAlbums :many
SELECT a.id, a.artist_id, a.title, a.slug, a.year, a.musicbrainz_id, a.album_type, a.genres, a.cover_path, a.release_date, a.label, a.country, a.barcode, a.total_tracks, a.total_discs, a.tags, a.integrated_lufs, a.true_peak_db, a.loudness_range_db, a.loudness_analyzed_at, a.search_vector, a.catalog_no, a.explicit, a.original_title, a.secondary_types, a.styles, a.language, a.duration_seconds, a.isrcs, a.rating, a.popularity, a.listeners, a.playcount, a.external_ids, a.artist_credits,
       mi.id AS artist_media_item_id,
       mi.title AS artist_name,
       mi.slug AS artist_slug
FROM albums a
JOIN artists ar ON ar.id = a.artist_id
JOIN media_items mi ON mi.id = ar.media_item_id
WHERE (
    lower(a.title) % lower($1)
    OR a.search_vector @@ websearch_to_tsquery('simple', $1)
    OR lower(a.title) ILIKE lower($1) || '%'
  )
ORDER BY
  greatest(
    similarity(lower(a.title), lower($1)),
    ts_rank(a.search_vector, websearch_to_tsquery('simple', $1)),
    CASE WHEN lower(a.title) ILIKE lower($1) || '%' THEN 1.0 ELSE 0.0 END
  ) DESC,
  a.title ASC
LIMIT $2 OFFSET $3
`

type SearchAlbumsParams struct {
	Lower  string `json:"lower"`
	Limit  int32  `json:"limit"`
	Offset int32  `json:"offset"`
}

type SearchAlbumsRow struct {
	ID                 int64              `json:"id"`
	ArtistID           int64              `json:"artist_id"`
	Title              string             `json:"title"`
	Slug               string             `json:"slug"`
	Year               string             `json:"year"`
	MusicbrainzID      string             `json:"musicbrainz_id"`
	AlbumType          string             `json:"album_type"`
	Genres             []string           `json:"genres"`
	CoverPath          string             `json:"cover_path"`
	ReleaseDate        pgtype.Date        `json:"release_date"`
	Label              string             `json:"label"`
	Country            string             `json:"country"`
	Barcode            string             `json:"barcode"`
	TotalTracks        int32              `json:"total_tracks"`
	TotalDiscs         int32              `json:"total_discs"`
	Tags               []string           `json:"tags"`
	IntegratedLufs     pgtype.Numeric     `json:"integrated_lufs"`
	TruePeakDb         pgtype.Numeric     `json:"true_peak_db"`
	LoudnessRangeDb    pgtype.Numeric     `json:"loudness_range_db"`
	LoudnessAnalyzedAt pgtype.Timestamptz `json:"loudness_analyzed_at"`
	SearchVector       interface{}        `json:"search_vector"`
	CatalogNo          string             `json:"catalog_no"`
	Explicit           bool               `json:"explicit"`
	OriginalTitle      string             `json:"original_title"`
	SecondaryTypes     []string           `json:"secondary_types"`
	Styles             []string           `json:"styles"`
	Language           string             `json:"language"`
	DurationSeconds    int32              `json:"duration_seconds"`
	Isrcs              []string           `json:"isrcs"`
	Rating             pgtype.Numeric     `json:"rating"`
	Popularity         int32              `json:"popularity"`
	Listeners          int64              `json:"listeners"`
	Playcount          int64              `json:"playcount"`
	ExternalIds        []byte             `json:"external_ids"`
	ArtistCredits      []byte             `json:"artist_credits"`
	ArtistMediaItemID  int64              `json:"artist_media_item_id"`
	ArtistName         string             `json:"artist_name"`
	ArtistSlug         string             `json:"artist_slug"`
}

func (q *Queries) SearchAlbums(ctx context.Context, arg SearchAlbumsParams) ([]SearchAlbumsRow, error) {
	rows, err := q.db.Query(ctx, searchAlbums, arg.Lower, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchAlbumsRow{}
	for rows.Next() {
		var i SearchAlbumsRow
		if err := rows.Scan(
			&i.ID,
			&i.ArtistID,
			&i.Title,
			&i.Slug,
			&i.Year,
			&i.MusicbrainzID,
			&i.AlbumType,
			&i.Genres,
			&i.CoverPath,
			&i.ReleaseDate,
			&i.Label,
			&i.Country,
			&i.Barcode,
			&i.TotalTracks,
			&i.TotalDiscs,
			&i.Tags,
			&i.IntegratedLufs,
			&i.TruePeakDb,
			&i.LoudnessRangeDb,
			&i.LoudnessAnalyzedAt,
			&i.SearchVector,
			&i.CatalogNo,
			&i.Explicit,
			&i.OriginalTitle,
			&i.SecondaryTypes,
			&i.Styles,
			&i.Language,
			&i.DurationSeconds,
			&i.Isrcs,
			&i.Rating,
			&i.Popularity,
			&i.Listeners,
			&i.Playcount,
			&i.ExternalIds,
			&i.ArtistCredits,
			&i.ArtistMediaItemID,
			&i.ArtistName,
			&i.ArtistSlug,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchAlbumsCount = `-- name: SearchAlbumsCount :one
SELECT count(*)
FROM albums a
WHERE (
    lower(a.title) % lower($1)
    OR a.search_vector @@ websearch_to_tsquery('simple', $1)
    OR lower(a.title) ILIKE lower($1) || '%'
  )
`

func (q *Queries) SearchAlbumsCount(ctx context.Context, lower string) (int64, error) {
	row := q.db.QueryRow(ctx, searchAlbumsCount, lower)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const searchAllMedia = `-- name: SearchAllMedia :many
SELECT mi.id, mi.library_id, mi.media_type, mi.title, mi.sort_title, mi.year, mi.description, mi.poster_path, mi.backdrop_path, mi.external_ids, mi.slug, mi.homepage, mi.tagline, mi.original_title, mi.original_language, mi.status, mi.provider_kind, mi.heya_slug, mi.heya_enriched_at, mi.metadata_refreshed_at, mi.created_at, mi.updated_at, mi.search_vector, mi.matched_at, mi.enrichment_status, mi.base_enriched_at, mi.people_enriched_at, mi.extras_enriched_at, mi.images_enriched_at, mi.structure_enriched_at, mi.last_enrich_attempt_at, mi.last_enrich_error
FROM media_items mi
WHERE (
    lower(mi.title) % lower($1)
    OR mi.search_vector @@ websearch_to_tsquery('english', $1)
    OR lower(mi.title) ILIKE lower($1) || '%'
  )
ORDER BY
  greatest(
    similarity(lower(mi.title), lower($1)),
    ts_rank(mi.search_vector, websearch_to_tsquery('english', $1)),
    CASE WHEN lower(mi.title) ILIKE lower($1) || '%' THEN 1.0 ELSE 0.0 END
  ) DESC,
  mi.title ASC
LIMIT $2 OFFSET $3
`

type SearchAllMediaParams struct {
	Lower  string `json:"lower"`
	Limit  int32  `json:"limit"`
	Offset int32  `json:"offset"`
}

func (q *Queries) SearchAllMedia(ctx context.Context, arg SearchAllMediaParams) ([]MediaItem, error) {
	rows, err := q.db.Query(ctx, searchAllMedia, arg.Lower, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MediaItem{}
	for rows.Next() {
		var i MediaItem
		if err := rows.Scan(
			&i.ID,
			&i.LibraryID,
			&i.MediaType,
			&i.Title,
			&i.SortTitle,
			&i.Year,
			&i.Description,
			&i.PosterPath,
			&i.BackdropPath,
			&i.ExternalIds,
			&i.Slug,
			&i.Homepage,
			&i.Tagline,
			&i.OriginalTitle,
			&i.OriginalLanguage,
			&i.Status,
			&i.ProviderKind,
			&i.HeyaSlug,
			&i.HeyaEnrichedAt,
			&i.MetadataRefreshedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SearchVector,
			&i.MatchedAt,
			&i.EnrichmentStatus,
			&i.BaseEnrichedAt,
			&i.PeopleEnrichedAt,
			&i.ExtrasEnrichedAt,
			&i.ImagesEnrichedAt,
			&i.StructureEnrichedAt,
			&i.LastEnrichAttemptAt,
			&i.LastEnrichError,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchCollections = `-- name: SearchCollections :many
SELECT c.id, c.external_ids, c.name, c.overview, c.poster_path, c.backdrop_path, c.search_vector
FROM collections c
WHERE (
    lower(c.name) % lower($1)
    OR c.search_vector @@ websearch_to_tsquery('english', $1)
    OR lower(c.name) ILIKE lower($1) || '%'
  )
ORDER BY
  greatest(
    similarity(lower(c.name), lower($1)),
    ts_rank(c.search_vector, websearch_to_tsquery('english', $1)),
    CASE WHEN lower(c.name) ILIKE lower($1) || '%' THEN 1.0 ELSE 0.0 END
  ) DESC,
  c.name ASC
LIMIT $2 OFFSET $3
`

type SearchCollectionsParams struct {
	Lower  string `json:"lower"`
	Limit  int32  `json:"limit"`
	Offset int32  `json:"offset"`
}

func (q *Queries) SearchCollections(ctx context.Context, arg SearchCollectionsParams) ([]Collection, error) {
	rows, err := q.db.Query(ctx, searchCollections, arg.Lower, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Collection{}
	for rows.Next() {
		var i Collection
		if err := rows.Scan(
			&i.ID,
			&i.ExternalIds,
			&i.Name,
			&i.Overview,
			&i.PosterPath,
			&i.BackdropPath,
			&i.SearchVector,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchCollectionsCount = `-- name: SearchCollectionsCount :one
SELECT count(*)
FROM collections c
WHERE (
    lower(c.name) % lower($1)
    OR c.search_vector @@ websearch_to_tsquery('english', $1)
    OR lower(c.name) ILIKE lower($1) || '%'
  )
`

func (q *Queries) SearchCollectionsCount(ctx context.Context, lower string) (int64, error) {
	row := q.db.QueryRow(ctx, searchCollectionsCount, lower)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const searchMediaByType = `-- name: SearchMediaByType :many

SELECT mi.id, mi.library_id, mi.media_type, mi.title, mi.sort_title, mi.year, mi.description, mi.poster_path, mi.backdrop_path, mi.external_ids, mi.slug, mi.homepage, mi.tagline, mi.original_title, mi.original_language, mi.status, mi.provider_kind, mi.heya_slug, mi.heya_enriched_at, mi.metadata_refreshed_at, mi.created_at, mi.updated_at, mi.search_vector, mi.matched_at, mi.enrichment_status, mi.base_enriched_at, mi.people_enriched_at, mi.extras_enriched_at, mi.images_enriched_at, mi.structure_enriched_at, mi.last_enrich_attempt_at, mi.last_enrich_error
FROM media_items mi
WHERE mi.media_type = $2
  AND (
    lower(mi.title) % lower($1)
    OR mi.search_vector @@ websearch_to_tsquery('english', $1)
    OR lower(mi.title) ILIKE lower($1) || '%'
  )
ORDER BY
  greatest(
    similarity(lower(mi.title), lower($1)),
    ts_rank(mi.search_vector, websearch_to_tsquery('english', $1)),
    CASE WHEN lower(mi.title) ILIKE lower($1) || '%' THEN 1.0 ELSE 0.0 END
  ) DESC,
  mi.title ASC
LIMIT $3 OFFSET $4
`

type SearchMediaByTypeParams struct {
	Lower     string    `json:"lower"`
	MediaType MediaType `json:"media_type"`
	Limit     int32     `json:"limit"`
	Offset    int32     `json:"offset"`
}

// Fuzzy + token search across all entity types.
// Combines pg_trgm similarity, tsvector matching, and case-insensitive prefix
// so it works for typos, partial words, and short queries alike. Ranked by
// greatest of those signals; popularity is a tie-breaker.
func (q *Queries) SearchMediaByType(ctx context.Context, arg SearchMediaByTypeParams) ([]MediaItem, error) {
	rows, err := q.db.Query(ctx, searchMediaByType,
		arg.Lower,
		arg.MediaType,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MediaItem{}
	for rows.Next() {
		var i MediaItem
		if err := rows.Scan(
			&i.ID,
			&i.LibraryID,
			&i.MediaType,
			&i.Title,
			&i.SortTitle,
			&i.Year,
			&i.Description,
			&i.PosterPath,
			&i.BackdropPath,
			&i.ExternalIds,
			&i.Slug,
			&i.Homepage,
			&i.Tagline,
			&i.OriginalTitle,
			&i.OriginalLanguage,
			&i.Status,
			&i.ProviderKind,
			&i.HeyaSlug,
			&i.HeyaEnrichedAt,
			&i.MetadataRefreshedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SearchVector,
			&i.MatchedAt,
			&i.EnrichmentStatus,
			&i.BaseEnrichedAt,
			&i.PeopleEnrichedAt,
			&i.ExtrasEnrichedAt,
			&i.ImagesEnrichedAt,
			&i.StructureEnrichedAt,
			&i.LastEnrichAttemptAt,
			&i.LastEnrichError,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchMediaByTypeCount = `-- name: SearchMediaByTypeCount :one
SELECT count(*)
FROM media_items mi
WHERE mi.media_type = $2
  AND (
    lower(mi.title) % lower($1)
    OR mi.search_vector @@ websearch_to_tsquery('english', $1)
    OR lower(mi.title) ILIKE lower($1) || '%'
  )
`

type SearchMediaByTypeCountParams struct {
	Lower     string    `json:"lower"`
	MediaType MediaType `json:"media_type"`
}

func (q *Queries) SearchMediaByTypeCount(ctx context.Context, arg SearchMediaByTypeCountParams) (int64, error) {
	row := q.db.QueryRow(ctx, searchMediaByTypeCount, arg.Lower, arg.MediaType)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const searchPeople = `-- name: SearchPeople :many
SELECT p.id, p.external_ids, p.name, p.also_known_as, p.biography, p.birthday, p.deathday, p.place_of_birth, p.gender, p.profile_path, p.homepage, p.popularity, p.slug, p.created_at, p.updated_at, p.sort_name, p.known_for_department, p.birth_year, p.heya_slug, p.heya_enriched_at, p.search_vector,
       (SELECT count(*) FROM media_cast WHERE person_id = p.id)::int AS cast_count,
       (SELECT count(*) FROM media_crew WHERE person_id = p.id)::int AS crew_count
FROM people p
WHERE (
    lower(p.name) % lower($1)
    OR p.search_vector @@ websearch_to_tsquery('simple', $1)
    OR lower(p.name) ILIKE lower($1) || '%'
  )
ORDER BY
  greatest(
    similarity(lower(p.name), lower($1)),
    ts_rank(p.search_vector, websearch_to_tsquery('simple', $1)),
    CASE WHEN lower(p.name) ILIKE lower($1) || '%' THEN 1.0 ELSE 0.0 END
  ) DESC,
  p.popularity DESC,
  p.name ASC
LIMIT $2 OFFSET $3
`

type SearchPeopleParams struct {
	Lower  string `json:"lower"`
	Limit  int32  `json:"limit"`
	Offset int32  `json:"offset"`
}

type SearchPeopleRow struct {
	ID                 int64              `json:"id"`
	ExternalIds        []byte             `json:"external_ids"`
	Name               string             `json:"name"`
	AlsoKnownAs        []string           `json:"also_known_as"`
	Biography          string             `json:"biography"`
	Birthday           string             `json:"birthday"`
	Deathday           string             `json:"deathday"`
	PlaceOfBirth       string             `json:"place_of_birth"`
	Gender             int32              `json:"gender"`
	ProfilePath        string             `json:"profile_path"`
	Homepage           string             `json:"homepage"`
	Popularity         pgtype.Numeric     `json:"popularity"`
	Slug               string             `json:"slug"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
	SortName           string             `json:"sort_name"`
	KnownForDepartment string             `json:"known_for_department"`
	BirthYear          int32              `json:"birth_year"`
	HeyaSlug           string             `json:"heya_slug"`
	HeyaEnrichedAt     pgtype.Timestamptz `json:"heya_enriched_at"`
	SearchVector       interface{}        `json:"search_vector"`
	CastCount          int32              `json:"cast_count"`
	CrewCount          int32              `json:"crew_count"`
}

func (q *Queries) SearchPeople(ctx context.Context, arg SearchPeopleParams) ([]SearchPeopleRow, error) {
	rows, err := q.db.Query(ctx, searchPeople, arg.Lower, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchPeopleRow{}
	for rows.Next() {
		var i SearchPeopleRow
		if err := rows.Scan(
			&i.ID,
			&i.ExternalIds,
			&i.Name,
			&i.AlsoKnownAs,
			&i.Biography,
			&i.Birthday,
			&i.Deathday,
			&i.PlaceOfBirth,
			&i.Gender,
			&i.ProfilePath,
			&i.Homepage,
			&i.Popularity,
			&i.Slug,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SortName,
			&i.KnownForDepartment,
			&i.BirthYear,
			&i.HeyaSlug,
			&i.HeyaEnrichedAt,
			&i.SearchVector,
			&i.CastCount,
			&i.CrewCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchPeopleCount = `-- name: SearchPeopleCount :one
SELECT count(*)
FROM people p
WHERE (
    lower(p.name) % lower($1)
    OR p.search_vector @@ websearch_to_tsquery('simple', $1)
    OR lower(p.name) ILIKE lower($1) || '%'
  )
`

func (q *Queries) SearchPeopleCount(ctx context.Context, lower string) (int64, error) {
	row := q.db.QueryRow(ctx, searchPeopleCount, lower)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const searchTracks = `-- name: SearchTracks :many
SELECT t.id, t.album_id, t.disc_number, t.track_number, t.title, t.duration, t.file_path, t.lyrics_path, t.search_vector, t.library_file_id, t.external_ids, t.isrc, t.recording_mbid, t.preview_url, t.explicit, t.artist_credits,
       a.title AS album_title,
       a.cover_path AS album_cover_path,
       mi.id AS artist_media_item_id,
       mi.title AS artist_name,
       mi.slug AS artist_slug
FROM tracks t
JOIN albums a ON a.id = t.album_id
JOIN artists ar ON ar.id = a.artist_id
JOIN media_items mi ON mi.id = ar.media_item_id
WHERE (
    lower(t.title) % lower($1)
    OR t.search_vector @@ websearch_to_tsquery('simple', $1)
    OR lower(t.title) ILIKE lower($1) || '%'
  )
ORDER BY
  greatest(
    similarity(lower(t.title), lower($1)),
    ts_rank(t.search_vector, websearch_to_tsquery('simple', $1)),
    CASE WHEN lower(t.title) ILIKE lower($1) || '%' THEN 1.0 ELSE 0.0 END
  ) DESC,
  t.title ASC
LIMIT $2 OFFSET $3
`

type SearchTracksParams struct {
	Lower  string `json:"lower"`
	Limit  int32  `json:"limit"`
	Offset int32  `json:"offset"`
}

type SearchTracksRow struct {
	ID                int64       `json:"id"`
	AlbumID           int64       `json:"album_id"`
	DiscNumber        int32       `json:"disc_number"`
	TrackNumber       int32       `json:"track_number"`
	Title             string      `json:"title"`
	Duration          int32       `json:"duration"`
	FilePath          string      `json:"file_path"`
	LyricsPath        string      `json:"lyrics_path"`
	SearchVector      interface{} `json:"search_vector"`
	LibraryFileID     pgtype.Int8 `json:"library_file_id"`
	ExternalIds       []byte      `json:"external_ids"`
	Isrc              string      `json:"isrc"`
	RecordingMbid     string      `json:"recording_mbid"`
	PreviewUrl        string      `json:"preview_url"`
	Explicit          bool        `json:"explicit"`
	ArtistCredits     []byte      `json:"artist_credits"`
	AlbumTitle        string      `json:"album_title"`
	AlbumCoverPath    string      `json:"album_cover_path"`
	ArtistMediaItemID int64       `json:"artist_media_item_id"`
	ArtistName        string      `json:"artist_name"`
	ArtistSlug        string      `json:"artist_slug"`
}

func (q *Queries) SearchTracks(ctx context.Context, arg SearchTracksParams) ([]SearchTracksRow, error) {
	rows, err := q.db.Query(ctx, searchTracks, arg.Lower, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchTracksRow{}
	for rows.Next() {
		var i SearchTracksRow
		if err := rows.Scan(
			&i.ID,
			&i.AlbumID,
			&i.DiscNumber,
			&i.TrackNumber,
			&i.Title,
			&i.Duration,
			&i.FilePath,
			&i.LyricsPath,
			&i.SearchVector,
			&i.LibraryFileID,
			&i.ExternalIds,
			&i.Isrc,
			&i.RecordingMbid,
			&i.PreviewUrl,
			&i.Explicit,
			&i.ArtistCredits,
			&i.AlbumTitle,
			&i.AlbumCoverPath,
			&i.ArtistMediaItemID,
			&i.ArtistName,
			&i.ArtistSlug,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchTracksCount = `-- name: SearchTracksCount :one
SELECT count(*)
FROM tracks t
WHERE (
    lower(t.title) % lower($1)
    OR t.search_vector @@ websearch_to_tsquery('simple', $1)
    OR lower(t.title) ILIKE lower($1) || '%'
  )
`

func (q *Queries) SearchTracksCount(ctx context.Context, lower string) (int64, error) {
	row := q.db.QueryRow(ctx, searchTracksCount, lower)
	var count int64
	err := row.Scan(&count)
	return count, err
}
