// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sessions.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (user_id, token_hash, expires_at, kind, name, user_agent, ip)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, user_id, token_hash, expires_at, created_at, kind, name, last_seen_at, user_agent, ip
`

type CreateSessionParams struct {
	UserID    int64              `json:"user_id"`
	TokenHash string             `json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	Kind      string             `json:"kind"`
	Name      pgtype.Text        `json:"name"`
	UserAgent pgtype.Text        `json:"user_agent"`
	Ip        pgtype.Text        `json:"ip"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, createSession,
		arg.UserID,
		arg.TokenHash,
		arg.ExpiresAt,
		arg.Kind,
		arg.Name,
		arg.UserAgent,
		arg.Ip,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.Kind,
		&i.Name,
		&i.LastSeenAt,
		&i.UserAgent,
		&i.Ip,
	)
	return i, err
}

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :exec
DELETE FROM sessions WHERE expires_at IS NOT NULL AND expires_at <= now()
`

func (q *Queries) DeleteExpiredSessions(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredSessions)
	return err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions WHERE token_hash = $1
`

func (q *Queries) DeleteSession(ctx context.Context, tokenHash string) error {
	_, err := q.db.Exec(ctx, deleteSession, tokenHash)
	return err
}

const deleteSessionByIDAdmin = `-- name: DeleteSessionByIDAdmin :exec
DELETE FROM sessions WHERE id = $1
`

// Admin-only single-session revoke — no user_id scope, so the admin
// console can boot any device or token by id.
func (q *Queries) DeleteSessionByIDAdmin(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteSessionByIDAdmin, id)
	return err
}

const deleteUserOtherSessions = `-- name: DeleteUserOtherSessions :exec
DELETE FROM sessions
WHERE user_id = $1
  AND kind IN ('session', 'jellyfin_session')
  AND token_hash <> $2
`

type DeleteUserOtherSessionsParams struct {
	UserID    int64  `json:"user_id"`
	TokenHash string `json:"token_hash"`
}

// "Sign out of every other device" — keep only the session backing the
// current request, drop the rest. Scope to kind='session' so a user's
// long-lived API tokens aren't affected.
func (q *Queries) DeleteUserOtherSessions(ctx context.Context, arg DeleteUserOtherSessionsParams) error {
	_, err := q.db.Exec(ctx, deleteUserOtherSessions, arg.UserID, arg.TokenHash)
	return err
}

const deleteUserSessionByID = `-- name: DeleteUserSessionByID :exec
DELETE FROM sessions WHERE id = $1 AND user_id = $2
`

type DeleteUserSessionByIDParams struct {
	ID     int64 `json:"id"`
	UserID int64 `json:"user_id"`
}

// Single-session revoke scoped to user_id so a user can't tear down someone
// else's session even if they guess an ID.
func (q *Queries) DeleteUserSessionByID(ctx context.Context, arg DeleteUserSessionByIDParams) error {
	_, err := q.db.Exec(ctx, deleteUserSessionByID, arg.ID, arg.UserID)
	return err
}

const deleteUserSessions = `-- name: DeleteUserSessions :exec
DELETE FROM sessions WHERE user_id = $1
`

func (q *Queries) DeleteUserSessions(ctx context.Context, userID int64) error {
	_, err := q.db.Exec(ctx, deleteUserSessions, userID)
	return err
}

const getSessionByToken = `-- name: GetSessionByToken :one
SELECT id, user_id, token_hash, expires_at, created_at, kind, name, last_seen_at, user_agent, ip FROM sessions
WHERE token_hash = $1
  AND (expires_at IS NULL OR expires_at > now())
`

func (q *Queries) GetSessionByToken(ctx context.Context, tokenHash string) (Session, error) {
	row := q.db.QueryRow(ctx, getSessionByToken, tokenHash)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.Kind,
		&i.Name,
		&i.LastSeenAt,
		&i.UserAgent,
		&i.Ip,
	)
	return i, err
}

const getSessionWithUserByToken = `-- name: GetSessionWithUserByToken :one
SELECT sessions.id, sessions.user_id, sessions.token_hash, sessions.expires_at, sessions.created_at, sessions.kind, sessions.name, sessions.last_seen_at, sessions.user_agent, sessions.ip, users.id, users.username, users.email, users.password_hash, users.is_admin, users.settings, users.created_at, users.updated_at, users.favorites_threshold
FROM sessions
JOIN users ON users.id = sessions.user_id
WHERE sessions.token_hash = $1
  AND (sessions.expires_at IS NULL OR sessions.expires_at > now())
`

type GetSessionWithUserByTokenRow struct {
	Session Session `json:"session"`
	User    User    `json:"user"`
}

// Auth-middleware hot path: session + owning user in one round trip.
// Nearly every API request pays this lookup, so the two dependent queries
// it replaces doubled the fixed per-request latency floor.
func (q *Queries) GetSessionWithUserByToken(ctx context.Context, tokenHash string) (GetSessionWithUserByTokenRow, error) {
	row := q.db.QueryRow(ctx, getSessionWithUserByToken, tokenHash)
	var i GetSessionWithUserByTokenRow
	err := row.Scan(
		&i.Session.ID,
		&i.Session.UserID,
		&i.Session.TokenHash,
		&i.Session.ExpiresAt,
		&i.Session.CreatedAt,
		&i.Session.Kind,
		&i.Session.Name,
		&i.Session.LastSeenAt,
		&i.Session.UserAgent,
		&i.Session.Ip,
		&i.User.ID,
		&i.User.Username,
		&i.User.Email,
		&i.User.PasswordHash,
		&i.User.IsAdmin,
		&i.User.Settings,
		&i.User.CreatedAt,
		&i.User.UpdatedAt,
		&i.User.FavoritesThreshold,
	)
	return i, err
}

const listAllSessionsForAdmin = `-- name: ListAllSessionsForAdmin :many
SELECT s.id, s.user_id, s.kind, s.name, s.expires_at, s.created_at,
       s.last_seen_at, s.user_agent, s.ip,
       u.username, u.is_admin
FROM sessions s
JOIN users u ON u.id = s.user_id
WHERE s.expires_at IS NULL OR s.expires_at > now()
ORDER BY s.last_seen_at DESC
`

type ListAllSessionsForAdminRow struct {
	ID         int64              `json:"id"`
	UserID     int64              `json:"user_id"`
	Kind       string             `json:"kind"`
	Name       pgtype.Text        `json:"name"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	LastSeenAt pgtype.Timestamptz `json:"last_seen_at"`
	UserAgent  pgtype.Text        `json:"user_agent"`
	Ip         pgtype.Text        `json:"ip"`
	Username   string             `json:"username"`
	IsAdmin    bool               `json:"is_admin"`
}

// Admin-only roster: every active session across every user, joined to the
// owning username for display. Sorted by last activity descending.
func (q *Queries) ListAllSessionsForAdmin(ctx context.Context) ([]ListAllSessionsForAdminRow, error) {
	rows, err := q.db.Query(ctx, listAllSessionsForAdmin)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAllSessionsForAdminRow{}
	for rows.Next() {
		var i ListAllSessionsForAdminRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Kind,
			&i.Name,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.LastSeenAt,
			&i.UserAgent,
			&i.Ip,
			&i.Username,
			&i.IsAdmin,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserSessionsByKind = `-- name: ListUserSessionsByKind :many
SELECT id, user_id, token_hash, expires_at, created_at, kind, name, last_seen_at, user_agent, ip
FROM sessions
WHERE user_id = $1
  AND (kind = $2 OR ($2 = 'session' AND kind = 'jellyfin_session'))
  AND (expires_at IS NULL OR expires_at > now())
ORDER BY last_seen_at DESC
`

type ListUserSessionsByKindParams struct {
	UserID int64  `json:"user_id"`
	Kind   string `json:"kind"`
}

// For the "My sessions" and "API tokens" pages — most-recent activity first.
func (q *Queries) ListUserSessionsByKind(ctx context.Context, arg ListUserSessionsByKindParams) ([]Session, error) {
	rows, err := q.db.Query(ctx, listUserSessionsByKind, arg.UserID, arg.Kind)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Session{}
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.TokenHash,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.Kind,
			&i.Name,
			&i.LastSeenAt,
			&i.UserAgent,
			&i.Ip,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const touchSession = `-- name: TouchSession :exec
UPDATE sessions
SET last_seen_at = now()
WHERE token_hash = $1
  AND last_seen_at < now() - interval '60 seconds'
`

// Bump last_seen_at on the session backing a request. Throttle is in SQL
// (no-op UPDATE when the row was touched in the last minute) so the
// middleware can fire-and-forget without holding any in-memory state.
func (q *Queries) TouchSession(ctx context.Context, tokenHash string) error {
	_, err := q.db.Exec(ctx, touchSession, tokenHash)
	return err
}
