// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: system_settings.sql

package sqlc

import (
	"context"
)

const deleteSystemSetting = `-- name: DeleteSystemSetting :exec
DELETE FROM system_settings WHERE key = $1
`

func (q *Queries) DeleteSystemSetting(ctx context.Context, key string) error {
	_, err := q.db.Exec(ctx, deleteSystemSetting, key)
	return err
}

const getSystemSetting = `-- name: GetSystemSetting :one
SELECT value FROM system_settings WHERE key = $1
`

func (q *Queries) GetSystemSetting(ctx context.Context, key string) ([]byte, error) {
	row := q.db.QueryRow(ctx, getSystemSetting, key)
	var value []byte
	err := row.Scan(&value)
	return value, err
}

const upsertSystemSetting = `-- name: UpsertSystemSetting :exec
INSERT INTO system_settings (key, value, updated_at)
VALUES ($1, $2, now())
ON CONFLICT (key) DO UPDATE SET value = $2, updated_at = now()
`

type UpsertSystemSettingParams struct {
	Key   string `json:"key"`
	Value []byte `json:"value"`
}

func (q *Queries) UpsertSystemSetting(ctx context.Context, arg UpsertSystemSettingParams) error {
	_, err := q.db.Exec(ctx, upsertSystemSetting, arg.Key, arg.Value)
	return err
}
