// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user_ratings.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countUserRatedTracks = `-- name: CountUserRatedTracks :one
SELECT count(*) FROM user_track_ratings
WHERE user_id = $1
  AND rating >= $2
  AND rating <= $3
`

type CountUserRatedTracksParams struct {
	UserID    int64 `json:"user_id"`
	MinRating int16 `json:"min_rating"`
	MaxRating int16 `json:"max_rating"`
}

func (q *Queries) CountUserRatedTracks(ctx context.Context, arg CountUserRatedTracksParams) (int64, error) {
	row := q.db.QueryRow(ctx, countUserRatedTracks, arg.UserID, arg.MinRating, arg.MaxRating)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteUserTrackRating = `-- name: DeleteUserTrackRating :exec
DELETE FROM user_track_ratings
WHERE user_id = $1 AND track_id = $2
`

type DeleteUserTrackRatingParams struct {
	UserID  int64 `json:"user_id"`
	TrackID int64 `json:"track_id"`
}

func (q *Queries) DeleteUserTrackRating(ctx context.Context, arg DeleteUserTrackRatingParams) error {
	_, err := q.db.Exec(ctx, deleteUserTrackRating, arg.UserID, arg.TrackID)
	return err
}

const getUserFavoritesThreshold = `-- name: GetUserFavoritesThreshold :one
SELECT favorites_threshold FROM users WHERE id = $1
`

func (q *Queries) GetUserFavoritesThreshold(ctx context.Context, id int64) (int16, error) {
	row := q.db.QueryRow(ctx, getUserFavoritesThreshold, id)
	var favorites_threshold int16
	err := row.Scan(&favorites_threshold)
	return favorites_threshold, err
}

const getUserRatedTracksStats = `-- name: GetUserRatedTracksStats :one
SELECT count(*)                             AS track_count,
       COALESCE(sum(t.duration), 0)::bigint AS total_duration,
       count(DISTINCT al.artist_id)         AS artist_count,
       max(utr.updated_at)::timestamptz     AS last_rated_at
FROM user_track_ratings utr
JOIN tracks t  ON t.id  = utr.track_id
JOIN albums al ON al.id = t.album_id
WHERE utr.user_id = $1
  AND utr.rating >= $2
  AND utr.rating <= $3
`

type GetUserRatedTracksStatsParams struct {
	UserID    int64 `json:"user_id"`
	MinRating int16 `json:"min_rating"`
	MaxRating int16 `json:"max_rating"`
}

type GetUserRatedTracksStatsRow struct {
	TrackCount    int64              `json:"track_count"`
	TotalDuration int64              `json:"total_duration"`
	ArtistCount   int64              `json:"artist_count"`
	LastRatedAt   pgtype.Timestamptz `json:"last_rated_at"`
}

// Aggregates for a rating band's ledger strip (Loved Songs hero): track
// count, total runtime, distinct artists, most recent rating touch. One
// pass over the user's rated set — small by construction.
func (q *Queries) GetUserRatedTracksStats(ctx context.Context, arg GetUserRatedTracksStatsParams) (GetUserRatedTracksStatsRow, error) {
	row := q.db.QueryRow(ctx, getUserRatedTracksStats, arg.UserID, arg.MinRating, arg.MaxRating)
	var i GetUserRatedTracksStatsRow
	err := row.Scan(
		&i.TrackCount,
		&i.TotalDuration,
		&i.ArtistCount,
		&i.LastRatedAt,
	)
	return i, err
}

const getUserTrackRating = `-- name: GetUserTrackRating :one
SELECT rating FROM user_track_ratings
WHERE user_id = $1 AND track_id = $2
`

type GetUserTrackRatingParams struct {
	UserID  int64 `json:"user_id"`
	TrackID int64 `json:"track_id"`
}

func (q *Queries) GetUserTrackRating(ctx context.Context, arg GetUserTrackRatingParams) (int16, error) {
	row := q.db.QueryRow(ctx, getUserTrackRating, arg.UserID, arg.TrackID)
	var rating int16
	err := row.Scan(&rating)
	return rating, err
}

const getUserTrackRatingsForTrackIDs = `-- name: GetUserTrackRatingsForTrackIDs :many
SELECT track_id, rating
FROM user_track_ratings
WHERE user_id = $1 AND track_id = ANY($2::bigint[])
`

type GetUserTrackRatingsForTrackIDsParams struct {
	UserID  int64   `json:"user_id"`
	Column2 []int64 `json:"column_2"`
}

type GetUserTrackRatingsForTrackIDsRow struct {
	TrackID int64 `json:"track_id"`
	Rating  int16 `json:"rating"`
}

// Bulk lookup for a track-list view — returns (track_id, rating) for the
// subset of input ids the user has rated. Driver passes the rest as nulls
// in its merge.
func (q *Queries) GetUserTrackRatingsForTrackIDs(ctx context.Context, arg GetUserTrackRatingsForTrackIDsParams) ([]GetUserTrackRatingsForTrackIDsRow, error) {
	rows, err := q.db.Query(ctx, getUserTrackRatingsForTrackIDs, arg.UserID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetUserTrackRatingsForTrackIDsRow{}
	for rows.Next() {
		var i GetUserTrackRatingsForTrackIDsRow
		if err := rows.Scan(&i.TrackID, &i.Rating); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserRatedTracks = `-- name: ListUserRatedTracks :many
SELECT t.id              AS track_id,
       t.title           AS track_title,
       t.duration        AS duration,
       t.disc_number     AS disc_number,
       t.track_number    AS track_number,
       t.explicit        AS explicit,
       al.id             AS album_id,
       al.title          AS album_title,
       al.slug           AS album_slug,
       al.cover_path     AS album_cover_path,
       al.year           AS album_year,
       al.genres         AS album_genres,
       al.label          AS album_label,
       al.release_date   AS album_release_date,
       a.id              AS artist_id,
       a.name            AS artist_name,
       mi.slug           AS artist_slug,
       utr.rating        AS rating,
       utr.updated_at    AS rated_at,
       EXISTS (SELECT 1 FROM track_files tf JOIN library_files lf ON lf.id = tf.library_file_id WHERE tf.track_id = t.id AND lf.deleted_at IS NULL) AS available,
       bf.format          AS format,
       bf.bitrate_kbps    AS bitrate_kbps,
       bf.sample_rate_hz  AS sample_rate_hz,
       bf.bit_depth       AS bit_depth,
       bf.channels        AS channels,
       bf.size_bytes      AS size_bytes,
       bf.integrated_lufs AS integrated_lufs,
       blf.created_at     AS library_added_at,
       tfc.bpm            AS bpm,
       tfc.key_root       AS key_root,
       tfc.key_mode       AS key_mode,
       COALESCE((SELECT string_agg((ac.value ->> 'name') || COALESCE(ac.value ->> 'join_phrase', ''), '' ORDER BY ac.ord)
          FROM jsonb_array_elements(CASE WHEN jsonb_typeof(t.artist_credits) = 'array' THEN t.artist_credits ELSE '[]'::jsonb END)
               WITH ORDINALITY AS ac(value, ord)), '')::text AS artists_display,
       COALESCE((SELECT string_agg(DISTINCT cr.value ->> 'artist_name', ', ')
          FROM jsonb_array_elements(CASE WHEN jsonb_typeof(t.credits) = 'array' THEN t.credits ELSE '[]'::jsonb END) AS cr(value)
         WHERE cr.value ->> 'role' = 'composer'), '')::text AS composer,
       (SELECT count(*) FROM play_events pe WHERE pe.user_id = utr.user_id AND pe.track_id = t.id) AS play_count,
       (SELECT max(pe.played_at) FROM play_events pe WHERE pe.user_id = utr.user_id AND pe.track_id = t.id)::timestamptz AS last_played_at
FROM user_track_ratings utr
JOIN tracks      t  ON t.id  = utr.track_id
JOIN albums      al ON al.id = t.album_id
JOIN artists     a  ON a.id  = al.artist_id
JOIN media_item_cards mi ON mi.id = a.media_item_id
LEFT JOIN track_files bf ON bf.id = (
    SELECT tf.id
    FROM track_files tf
    JOIN library_files lf ON lf.id = tf.library_file_id
    WHERE tf.track_id = t.id AND lf.deleted_at IS NULL
    ORDER BY tf.quality_score DESC, tf.id ASC
    LIMIT 1
)
LEFT JOIN library_files blf ON blf.id = bf.library_file_id
LEFT JOIN track_facets tfc ON tfc.track_id = t.id
WHERE utr.user_id = $1
  AND utr.rating  >= $2
  AND utr.rating  <= $3
ORDER BY utr.rating DESC, utr.updated_at DESC
LIMIT $5 OFFSET $4
`

type ListUserRatedTracksParams struct {
	UserID     int64 `json:"user_id"`
	MinRating  int16 `json:"min_rating"`
	MaxRating  int16 `json:"max_rating"`
	Offset     int32 `json:"offset_"`
	TrackLimit int32 `json:"track_limit"`
}

type ListUserRatedTracksRow struct {
	TrackID          int64              `json:"track_id"`
	TrackTitle       string             `json:"track_title"`
	Duration         int32              `json:"duration"`
	DiscNumber       int32              `json:"disc_number"`
	TrackNumber      int32              `json:"track_number"`
	Explicit         bool               `json:"explicit"`
	AlbumID          int64              `json:"album_id"`
	AlbumTitle       string             `json:"album_title"`
	AlbumSlug        string             `json:"album_slug"`
	AlbumCoverPath   string             `json:"album_cover_path"`
	AlbumYear        string             `json:"album_year"`
	AlbumGenres      []string           `json:"album_genres"`
	AlbumLabel       string             `json:"album_label"`
	AlbumReleaseDate pgtype.Date        `json:"album_release_date"`
	ArtistID         int64              `json:"artist_id"`
	ArtistName       string             `json:"artist_name"`
	ArtistSlug       string             `json:"artist_slug"`
	Rating           int16              `json:"rating"`
	RatedAt          pgtype.Timestamptz `json:"rated_at"`
	Available        bool               `json:"available"`
	Format           pgtype.Text        `json:"format"`
	BitrateKbps      pgtype.Int4        `json:"bitrate_kbps"`
	SampleRateHz     pgtype.Int4        `json:"sample_rate_hz"`
	BitDepth         pgtype.Int4        `json:"bit_depth"`
	Channels         pgtype.Int4        `json:"channels"`
	SizeBytes        pgtype.Int8        `json:"size_bytes"`
	IntegratedLufs   pgtype.Numeric     `json:"integrated_lufs"`
	LibraryAddedAt   pgtype.Timestamptz `json:"library_added_at"`
	Bpm              pgtype.Float4      `json:"bpm"`
	KeyRoot          pgtype.Int2        `json:"key_root"`
	KeyMode          pgtype.Int2        `json:"key_mode"`
	ArtistsDisplay   string             `json:"artists_display"`
	Composer         string             `json:"composer"`
	PlayCount        int64              `json:"play_count"`
	LastPlayedAt     pgtype.Timestamptz `json:"last_played_at"`
}

// Paginated list of every track the user has rated, sorted by rating
// desc then most-recently-rated. Carries album+artist context so the FE
// renders self-contained rows. Filters by min_rating for the Favorites
// view (use 1 to get everything rated).
//
// Enrichment columns (best file, facets, play stats, composer) mirror
// ListPlaylistTracks — see the comment there for the LATERAL-avoidance and
// jsonb-extraction rationale. Kept as direct joins without a keys-subquery
// wrap: the joined set is one user's rated tracks (thousands at most), not
// the whole catalog.
func (q *Queries) ListUserRatedTracks(ctx context.Context, arg ListUserRatedTracksParams) ([]ListUserRatedTracksRow, error) {
	rows, err := q.db.Query(ctx, listUserRatedTracks,
		arg.UserID,
		arg.MinRating,
		arg.MaxRating,
		arg.Offset,
		arg.TrackLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUserRatedTracksRow{}
	for rows.Next() {
		var i ListUserRatedTracksRow
		if err := rows.Scan(
			&i.TrackID,
			&i.TrackTitle,
			&i.Duration,
			&i.DiscNumber,
			&i.TrackNumber,
			&i.Explicit,
			&i.AlbumID,
			&i.AlbumTitle,
			&i.AlbumSlug,
			&i.AlbumCoverPath,
			&i.AlbumYear,
			&i.AlbumGenres,
			&i.AlbumLabel,
			&i.AlbumReleaseDate,
			&i.ArtistID,
			&i.ArtistName,
			&i.ArtistSlug,
			&i.Rating,
			&i.RatedAt,
			&i.Available,
			&i.Format,
			&i.BitrateKbps,
			&i.SampleRateHz,
			&i.BitDepth,
			&i.Channels,
			&i.SizeBytes,
			&i.IntegratedLufs,
			&i.LibraryAddedAt,
			&i.Bpm,
			&i.KeyRoot,
			&i.KeyMode,
			&i.ArtistsDisplay,
			&i.Composer,
			&i.PlayCount,
			&i.LastPlayedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setUserTrackRating = `-- name: SetUserTrackRating :exec

INSERT INTO user_track_ratings (user_id, track_id, rating)
VALUES ($1, $2, $3)
ON CONFLICT (user_id, track_id) DO UPDATE
    SET rating = EXCLUDED.rating,
        updated_at = now()
`

type SetUserTrackRatingParams struct {
	UserID  int64 `json:"user_id"`
	TrackID int64 `json:"track_id"`
	Rating  int16 `json:"rating"`
}

// Per-user track ratings. UI displays 5 stars in half-step increments;
// the column stores 1..10 so half-stars round-trip cleanly.
//
// List/Count take a [min_rating, max_rating] band (not just a floor): the
// Favorites page's reaction bands (down 1-3, liked 6-8, loved 9-10) page
// server-side through the same random-access catalog as everything else.
// Upsert: writes a rating or replaces the existing one. Touch updated_at
// on conflict so "recently rated" ordering reflects last edit.
func (q *Queries) SetUserTrackRating(ctx context.Context, arg SetUserTrackRatingParams) error {
	_, err := q.db.Exec(ctx, setUserTrackRating, arg.UserID, arg.TrackID, arg.Rating)
	return err
}

const updateUserFavoritesThreshold = `-- name: UpdateUserFavoritesThreshold :exec
UPDATE users SET favorites_threshold = $2 WHERE id = $1
`

type UpdateUserFavoritesThresholdParams struct {
	ID                 int64 `json:"id"`
	FavoritesThreshold int16 `json:"favorites_threshold"`
}

func (q *Queries) UpdateUserFavoritesThreshold(ctx context.Context, arg UpdateUserFavoritesThresholdParams) error {
	_, err := q.db.Exec(ctx, updateUserFavoritesThreshold, arg.ID, arg.FavoritesThreshold)
	return err
}
