// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user_state.sql

package sqlc

import (
	"context"
)

const listFavoritedIDs = `-- name: ListFavoritedIDs :many
SELECT entity_id FROM user_favorites
WHERE user_id = $1 AND entity_type = $2
`

type ListFavoritedIDsParams struct {
	UserID     int64  `json:"user_id"`
	EntityType string `json:"entity_type"`
}

// All favorited entity IDs by type
func (q *Queries) ListFavoritedIDs(ctx context.Context, arg ListFavoritedIDsParams) ([]int64, error) {
	rows, err := q.db.Query(ctx, listFavoritedIDs, arg.UserID, arg.EntityType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var entity_id int64
		if err := rows.Scan(&entity_id); err != nil {
			return nil, err
		}
		items = append(items, entity_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFavoritedMediaIDsByType = `-- name: ListFavoritedMediaIDsByType :many
SELECT f.entity_id
FROM user_favorites f
JOIN media_items mi ON mi.id = f.entity_id
WHERE f.user_id = $1 AND f.entity_type = 'media_item' AND mi.media_type = $2
`

type ListFavoritedMediaIDsByTypeParams struct {
	UserID    int64     `json:"user_id"`
	MediaType MediaType `json:"media_type"`
}

// Favorited media_item IDs scoped to a media type. Movies and TV shows are both
// favorited as entity_type='media_item', so the per-section Loved count/list
// must filter by the item's media_type — a loved show must not count on Movies.
func (q *Queries) ListFavoritedMediaIDsByType(ctx context.Context, arg ListFavoritedMediaIDsByTypeParams) ([]int64, error) {
	rows, err := q.db.Query(ctx, listFavoritedMediaIDsByType, arg.UserID, arg.MediaType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var entity_id int64
		if err := rows.Scan(&entity_id); err != nil {
			return nil, err
		}
		items = append(items, entity_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listShowWatchCounts = `-- name: ListShowWatchCounts :many
SELECT ts.media_item_id,
       ts.number_of_episodes::int AS total_episodes,
       COALESCE(w.n, 0)::int AS watched_episodes
FROM tv_series ts
LEFT JOIN (
    SELECT s.series_id, count(*) AS n
    FROM user_watch_progress wp
    JOIN tv_episodes e ON e.id = wp.entity_id
    JOIN tv_seasons s ON s.id = e.season_id
    WHERE wp.user_id = $1 AND wp.entity_type = 'episode' AND wp.completed = true
    GROUP BY s.series_id
) w ON w.series_id = ts.id
`

type ListShowWatchCountsRow struct {
	MediaItemID     int64 `json:"media_item_id"`
	TotalEpisodes   int32 `json:"total_episodes"`
	WatchedEpisodes int32 `json:"watched_episodes"`
}

// Per-show watched: total episodes vs watched episodes, grouped by media_item_id.
// Fires on every TV browse page. Drives from the user's watch rows (dozens)
// instead of re-aggregating the whole episode catalog (~80k rows, ~80ms) per
// load; total comes from the denormalized tv_series.number_of_episodes, which
// is the same catalog count the browse card already displays as "X eps".
func (q *Queries) ListShowWatchCounts(ctx context.Context, userID int64) ([]ListShowWatchCountsRow, error) {
	rows, err := q.db.Query(ctx, listShowWatchCounts, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListShowWatchCountsRow{}
	for rows.Next() {
		var i ListShowWatchCountsRow
		if err := rows.Scan(&i.MediaItemID, &i.TotalEpisodes, &i.WatchedEpisodes); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWatchedEpisodeIDsForSeries = `-- name: ListWatchedEpisodeIDsForSeries :many

SELECT wp.entity_id AS episode_id
FROM user_watch_progress wp
JOIN tv_episodes e ON e.id = wp.entity_id
JOIN tv_seasons s ON s.id = e.season_id
WHERE wp.user_id = $1 AND wp.entity_type = 'episode' AND wp.completed = true AND s.series_id = $2
`

type ListWatchedEpisodeIDsForSeriesParams struct {
	UserID   int64 `json:"user_id"`
	SeriesID int64 `json:"series_id"`
}

// Per-season watched: total vs watched, grouped by season
// Per-episode watched IDs for a single series
func (q *Queries) ListWatchedEpisodeIDsForSeries(ctx context.Context, arg ListWatchedEpisodeIDsForSeriesParams) ([]int64, error) {
	rows, err := q.db.Query(ctx, listWatchedEpisodeIDsForSeries, arg.UserID, arg.SeriesID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var episode_id int64
		if err := rows.Scan(&episode_id); err != nil {
			return nil, err
		}
		items = append(items, episode_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWatchedMovieIDs = `-- name: ListWatchedMovieIDs :many
SELECT entity_id AS media_item_id FROM user_watch_progress
WHERE user_id = $1 AND entity_type = 'movie' AND completed = true
`

// Watched movie IDs
func (q *Queries) ListWatchedMovieIDs(ctx context.Context, userID int64) ([]int64, error) {
	rows, err := q.db.Query(ctx, listWatchedMovieIDs, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var media_item_id int64
		if err := rows.Scan(&media_item_id); err != nil {
			return nil, err
		}
		items = append(items, media_item_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
