// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user_album_artist_ratings.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countUserRatedAlbums = `-- name: CountUserRatedAlbums :one
SELECT count(*) FROM user_album_ratings
WHERE user_id = $1
  AND rating >= $2
  AND rating <= $3
`

type CountUserRatedAlbumsParams struct {
	UserID    int64 `json:"user_id"`
	MinRating int16 `json:"min_rating"`
	MaxRating int16 `json:"max_rating"`
}

func (q *Queries) CountUserRatedAlbums(ctx context.Context, arg CountUserRatedAlbumsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countUserRatedAlbums, arg.UserID, arg.MinRating, arg.MaxRating)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUserRatedArtists = `-- name: CountUserRatedArtists :one
SELECT count(*) FROM user_artist_ratings
WHERE user_id = $1
  AND rating >= $2
  AND rating <= $3
`

type CountUserRatedArtistsParams struct {
	UserID    int64 `json:"user_id"`
	MinRating int16 `json:"min_rating"`
	MaxRating int16 `json:"max_rating"`
}

func (q *Queries) CountUserRatedArtists(ctx context.Context, arg CountUserRatedArtistsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countUserRatedArtists, arg.UserID, arg.MinRating, arg.MaxRating)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteUserAlbumRating = `-- name: DeleteUserAlbumRating :exec
DELETE FROM user_album_ratings
WHERE user_id = $1 AND album_id = $2
`

type DeleteUserAlbumRatingParams struct {
	UserID  int64 `json:"user_id"`
	AlbumID int64 `json:"album_id"`
}

func (q *Queries) DeleteUserAlbumRating(ctx context.Context, arg DeleteUserAlbumRatingParams) error {
	_, err := q.db.Exec(ctx, deleteUserAlbumRating, arg.UserID, arg.AlbumID)
	return err
}

const deleteUserArtistRating = `-- name: DeleteUserArtistRating :exec
DELETE FROM user_artist_ratings
WHERE user_id = $1 AND artist_id = $2
`

type DeleteUserArtistRatingParams struct {
	UserID   int64 `json:"user_id"`
	ArtistID int64 `json:"artist_id"`
}

func (q *Queries) DeleteUserArtistRating(ctx context.Context, arg DeleteUserArtistRatingParams) error {
	_, err := q.db.Exec(ctx, deleteUserArtistRating, arg.UserID, arg.ArtistID)
	return err
}

const getUserAlbumRating = `-- name: GetUserAlbumRating :one
SELECT rating FROM user_album_ratings
WHERE user_id = $1 AND album_id = $2
`

type GetUserAlbumRatingParams struct {
	UserID  int64 `json:"user_id"`
	AlbumID int64 `json:"album_id"`
}

func (q *Queries) GetUserAlbumRating(ctx context.Context, arg GetUserAlbumRatingParams) (int16, error) {
	row := q.db.QueryRow(ctx, getUserAlbumRating, arg.UserID, arg.AlbumID)
	var rating int16
	err := row.Scan(&rating)
	return rating, err
}

const getUserAlbumRatingsForIDs = `-- name: GetUserAlbumRatingsForIDs :many
SELECT album_id, rating
FROM user_album_ratings
WHERE user_id = $1 AND album_id = ANY($2::bigint[])
`

type GetUserAlbumRatingsForIDsParams struct {
	UserID  int64   `json:"user_id"`
	Column2 []int64 `json:"column_2"`
}

type GetUserAlbumRatingsForIDsRow struct {
	AlbumID int64 `json:"album_id"`
	Rating  int16 `json:"rating"`
}

func (q *Queries) GetUserAlbumRatingsForIDs(ctx context.Context, arg GetUserAlbumRatingsForIDsParams) ([]GetUserAlbumRatingsForIDsRow, error) {
	rows, err := q.db.Query(ctx, getUserAlbumRatingsForIDs, arg.UserID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetUserAlbumRatingsForIDsRow{}
	for rows.Next() {
		var i GetUserAlbumRatingsForIDsRow
		if err := rows.Scan(&i.AlbumID, &i.Rating); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserArtistRating = `-- name: GetUserArtistRating :one
SELECT rating FROM user_artist_ratings
WHERE user_id = $1 AND artist_id = $2
`

type GetUserArtistRatingParams struct {
	UserID   int64 `json:"user_id"`
	ArtistID int64 `json:"artist_id"`
}

func (q *Queries) GetUserArtistRating(ctx context.Context, arg GetUserArtistRatingParams) (int16, error) {
	row := q.db.QueryRow(ctx, getUserArtistRating, arg.UserID, arg.ArtistID)
	var rating int16
	err := row.Scan(&rating)
	return rating, err
}

const getUserArtistRatingsForIDs = `-- name: GetUserArtistRatingsForIDs :many
SELECT artist_id, rating
FROM user_artist_ratings
WHERE user_id = $1 AND artist_id = ANY($2::bigint[])
`

type GetUserArtistRatingsForIDsParams struct {
	UserID  int64   `json:"user_id"`
	Column2 []int64 `json:"column_2"`
}

type GetUserArtistRatingsForIDsRow struct {
	ArtistID int64 `json:"artist_id"`
	Rating   int16 `json:"rating"`
}

func (q *Queries) GetUserArtistRatingsForIDs(ctx context.Context, arg GetUserArtistRatingsForIDsParams) ([]GetUserArtistRatingsForIDsRow, error) {
	rows, err := q.db.Query(ctx, getUserArtistRatingsForIDs, arg.UserID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetUserArtistRatingsForIDsRow{}
	for rows.Next() {
		var i GetUserArtistRatingsForIDsRow
		if err := rows.Scan(&i.ArtistID, &i.Rating); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserRatedAlbums = `-- name: ListUserRatedAlbums :many
SELECT al.id, al.artist_id, al.title, al.slug, al.year, al.musicbrainz_id, al.album_type, al.genres, al.cover_path, al.release_date, al.label, al.country, al.barcode, al.total_tracks, al.total_discs, al.tags, al.integrated_lufs, al.true_peak_db, al.loudness_range_db, al.loudness_analyzed_at, al.search_vector, al.catalog_no, al.explicit, al.original_title, al.secondary_types, al.styles, al.language, al.duration_seconds, al.isrcs, al.rating, al.popularity, al.listeners, al.playcount, al.external_ids, al.artist_credits, al.field_provenance, al.sort_artist, al.sort_title,
       a.name        AS artist_name,
       mi.slug       AS artist_slug,
       uar.rating    AS rating,
       uar.updated_at AS rated_at
FROM user_album_ratings uar
JOIN albums      al ON al.id = uar.album_id
JOIN artists     a  ON a.id  = al.artist_id
JOIN media_item_cards mi ON mi.id = a.media_item_id
WHERE uar.user_id = $1
  AND uar.rating  >= $2
  AND uar.rating  <= $3
ORDER BY uar.rating DESC, uar.updated_at DESC
LIMIT $5 OFFSET $4
`

type ListUserRatedAlbumsParams struct {
	UserID     int64 `json:"user_id"`
	MinRating  int16 `json:"min_rating"`
	MaxRating  int16 `json:"max_rating"`
	Offset     int32 `json:"offset_"`
	AlbumLimit int32 `json:"album_limit"`
}

type ListUserRatedAlbumsRow struct {
	ID                 int64              `json:"id"`
	ArtistID           int64              `json:"artist_id"`
	Title              string             `json:"title"`
	Slug               string             `json:"slug"`
	Year               string             `json:"year"`
	MusicbrainzID      string             `json:"musicbrainz_id"`
	AlbumType          string             `json:"album_type"`
	Genres             []string           `json:"genres"`
	CoverPath          string             `json:"cover_path"`
	ReleaseDate        pgtype.Date        `json:"release_date"`
	Label              string             `json:"label"`
	Country            string             `json:"country"`
	Barcode            string             `json:"barcode"`
	TotalTracks        int32              `json:"total_tracks"`
	TotalDiscs         int32              `json:"total_discs"`
	Tags               []string           `json:"tags"`
	IntegratedLufs     pgtype.Numeric     `json:"integrated_lufs"`
	TruePeakDb         pgtype.Numeric     `json:"true_peak_db"`
	LoudnessRangeDb    pgtype.Numeric     `json:"loudness_range_db"`
	LoudnessAnalyzedAt pgtype.Timestamptz `json:"loudness_analyzed_at"`
	SearchVector       interface{}        `json:"search_vector"`
	CatalogNo          string             `json:"catalog_no"`
	Explicit           bool               `json:"explicit"`
	OriginalTitle      string             `json:"original_title"`
	SecondaryTypes     []string           `json:"secondary_types"`
	Styles             []string           `json:"styles"`
	Language           string             `json:"language"`
	DurationSeconds    int32              `json:"duration_seconds"`
	Isrcs              []string           `json:"isrcs"`
	Rating             pgtype.Numeric     `json:"rating"`
	Popularity         int32              `json:"popularity"`
	Listeners          int64              `json:"listeners"`
	Playcount          int64              `json:"playcount"`
	ExternalIds        []byte             `json:"external_ids"`
	ArtistCredits      []byte             `json:"artist_credits"`
	FieldProvenance    []byte             `json:"field_provenance"`
	SortArtist         string             `json:"sort_artist"`
	SortTitle          string             `json:"sort_title"`
	ArtistName         string             `json:"artist_name"`
	ArtistSlug         string             `json:"artist_slug"`
	Rating_2           int16              `json:"rating_2"`
	RatedAt            pgtype.Timestamptz `json:"rated_at"`
}

// Paginated rated albums. Carries artist context so the FE renders rows
// without follow-up lookups.
func (q *Queries) ListUserRatedAlbums(ctx context.Context, arg ListUserRatedAlbumsParams) ([]ListUserRatedAlbumsRow, error) {
	rows, err := q.db.Query(ctx, listUserRatedAlbums,
		arg.UserID,
		arg.MinRating,
		arg.MaxRating,
		arg.Offset,
		arg.AlbumLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUserRatedAlbumsRow{}
	for rows.Next() {
		var i ListUserRatedAlbumsRow
		if err := rows.Scan(
			&i.ID,
			&i.ArtistID,
			&i.Title,
			&i.Slug,
			&i.Year,
			&i.MusicbrainzID,
			&i.AlbumType,
			&i.Genres,
			&i.CoverPath,
			&i.ReleaseDate,
			&i.Label,
			&i.Country,
			&i.Barcode,
			&i.TotalTracks,
			&i.TotalDiscs,
			&i.Tags,
			&i.IntegratedLufs,
			&i.TruePeakDb,
			&i.LoudnessRangeDb,
			&i.LoudnessAnalyzedAt,
			&i.SearchVector,
			&i.CatalogNo,
			&i.Explicit,
			&i.OriginalTitle,
			&i.SecondaryTypes,
			&i.Styles,
			&i.Language,
			&i.DurationSeconds,
			&i.Isrcs,
			&i.Rating,
			&i.Popularity,
			&i.Listeners,
			&i.Playcount,
			&i.ExternalIds,
			&i.ArtistCredits,
			&i.FieldProvenance,
			&i.SortArtist,
			&i.SortTitle,
			&i.ArtistName,
			&i.ArtistSlug,
			&i.Rating_2,
			&i.RatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserRatedArtists = `-- name: ListUserRatedArtists :many
SELECT a.id, a.media_item_id, a.musicbrainz_id, a.name, a.sort_name, a.disambiguation, a.biography, a.search_vector, a.discography_enriched_at, a.cover_art_enriched_at, a.listeners, a.playcount, a.popularity, a.annotation, a.urls, a.wikipedia_links, a.profiles, a.aliases, a.groups, a.members, a.artist_type, a.begin_date, a.begin_year, a.end_date, a.ended, a.deathday, a.birthplace, a.tags, a.genres, a.metadata_sources,
       mi.slug         AS slug,
       mi.public_id    AS media_item_public_id,
       mi.poster_path  AS poster_path,
       (SELECT count(*) FROM albums al WHERE al.artist_id = a.id) AS album_count,
       (SELECT count(*) FROM tracks t JOIN albums al ON al.id = t.album_id WHERE al.artist_id = a.id) AS track_count,
       uar.rating      AS rating,
       uar.updated_at  AS rated_at
FROM user_artist_ratings uar
JOIN artists     a  ON a.id  = uar.artist_id
JOIN media_item_cards mi ON mi.id = a.media_item_id
WHERE uar.user_id = $1
  AND uar.rating  >= $2
  AND uar.rating  <= $3
ORDER BY uar.rating DESC, uar.updated_at DESC
LIMIT $5 OFFSET $4
`

type ListUserRatedArtistsParams struct {
	UserID      int64 `json:"user_id"`
	MinRating   int16 `json:"min_rating"`
	MaxRating   int16 `json:"max_rating"`
	Offset      int32 `json:"offset_"`
	ArtistLimit int32 `json:"artist_limit"`
}

type ListUserRatedArtistsRow struct {
	ID                    int64              `json:"id"`
	MediaItemID           int64              `json:"media_item_id"`
	MusicbrainzID         string             `json:"musicbrainz_id"`
	Name                  string             `json:"name"`
	SortName              string             `json:"sort_name"`
	Disambiguation        string             `json:"disambiguation"`
	Biography             string             `json:"biography"`
	SearchVector          interface{}        `json:"search_vector"`
	DiscographyEnrichedAt pgtype.Timestamptz `json:"discography_enriched_at"`
	CoverArtEnrichedAt    pgtype.Timestamptz `json:"cover_art_enriched_at"`
	Listeners             int64              `json:"listeners"`
	Playcount             int64              `json:"playcount"`
	Popularity            int32              `json:"popularity"`
	Annotation            string             `json:"annotation"`
	Urls                  []byte             `json:"urls"`
	WikipediaLinks        []byte             `json:"wikipedia_links"`
	Profiles              []byte             `json:"profiles"`
	Aliases               []string           `json:"aliases"`
	Groups                []byte             `json:"groups"`
	Members               []byte             `json:"members"`
	ArtistType            string             `json:"artist_type"`
	BeginDate             string             `json:"begin_date"`
	BeginYear             int32              `json:"begin_year"`
	EndDate               string             `json:"end_date"`
	Ended                 bool               `json:"ended"`
	Deathday              string             `json:"deathday"`
	Birthplace            string             `json:"birthplace"`
	Tags                  []string           `json:"tags"`
	Genres                []string           `json:"genres"`
	MetadataSources       []string           `json:"metadata_sources"`
	Slug                  string             `json:"slug"`
	MediaItemPublicID     uuid.UUID          `json:"media_item_public_id"`
	PosterPath            string             `json:"poster_path"`
	AlbumCount            int64              `json:"album_count"`
	TrackCount            int64              `json:"track_count"`
	Rating                int16              `json:"rating"`
	RatedAt               pgtype.Timestamptz `json:"rated_at"`
}

// Paginated rated artists with album/track counts so the tile matches the
// shape of /api/me/loved/artists (drop-in replacement for that endpoint).
func (q *Queries) ListUserRatedArtists(ctx context.Context, arg ListUserRatedArtistsParams) ([]ListUserRatedArtistsRow, error) {
	rows, err := q.db.Query(ctx, listUserRatedArtists,
		arg.UserID,
		arg.MinRating,
		arg.MaxRating,
		arg.Offset,
		arg.ArtistLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUserRatedArtistsRow{}
	for rows.Next() {
		var i ListUserRatedArtistsRow
		if err := rows.Scan(
			&i.ID,
			&i.MediaItemID,
			&i.MusicbrainzID,
			&i.Name,
			&i.SortName,
			&i.Disambiguation,
			&i.Biography,
			&i.SearchVector,
			&i.DiscographyEnrichedAt,
			&i.CoverArtEnrichedAt,
			&i.Listeners,
			&i.Playcount,
			&i.Popularity,
			&i.Annotation,
			&i.Urls,
			&i.WikipediaLinks,
			&i.Profiles,
			&i.Aliases,
			&i.Groups,
			&i.Members,
			&i.ArtistType,
			&i.BeginDate,
			&i.BeginYear,
			&i.EndDate,
			&i.Ended,
			&i.Deathday,
			&i.Birthplace,
			&i.Tags,
			&i.Genres,
			&i.MetadataSources,
			&i.Slug,
			&i.MediaItemPublicID,
			&i.PosterPath,
			&i.AlbumCount,
			&i.TrackCount,
			&i.Rating,
			&i.RatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setUserAlbumRating = `-- name: SetUserAlbumRating :exec


INSERT INTO user_album_ratings (user_id, album_id, rating)
VALUES ($1, $2, $3)
ON CONFLICT (user_id, album_id) DO UPDATE
    SET rating = EXCLUDED.rating,
        updated_at = now()
`

type SetUserAlbumRatingParams struct {
	UserID  int64 `json:"user_id"`
	AlbumID int64 `json:"album_id"`
	Rating  int16 `json:"rating"`
}

// Album + artist rating CRUD. Same shape as user_track_ratings — separate
// tables (rather than polymorphic) so each FK constraint can cascade
// correctly when the parent row is deleted.
// ============== Albums ==============
func (q *Queries) SetUserAlbumRating(ctx context.Context, arg SetUserAlbumRatingParams) error {
	_, err := q.db.Exec(ctx, setUserAlbumRating, arg.UserID, arg.AlbumID, arg.Rating)
	return err
}

const setUserArtistRating = `-- name: SetUserArtistRating :exec

INSERT INTO user_artist_ratings (user_id, artist_id, rating)
VALUES ($1, $2, $3)
ON CONFLICT (user_id, artist_id) DO UPDATE
    SET rating = EXCLUDED.rating,
        updated_at = now()
`

type SetUserArtistRatingParams struct {
	UserID   int64 `json:"user_id"`
	ArtistID int64 `json:"artist_id"`
	Rating   int16 `json:"rating"`
}

// ============== Artists ==============
func (q *Queries) SetUserArtistRating(ctx context.Context, arg SetUserArtistRatingParams) error {
	_, err := q.db.Exec(ctx, setUserArtistRating, arg.UserID, arg.ArtistID, arg.Rating)
	return err
}
