// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package sqlc

import (
	"context"
)

const countUsers = `-- name: CountUsers :one
SELECT count(*) FROM users
`

func (q *Queries) CountUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (username, email, password_hash, is_admin)
VALUES ($1, $2, $3, $4)
RETURNING id, username, email, password_hash, is_admin, settings, created_at, updated_at, favorites_threshold
`

type CreateUserParams struct {
	Username     string `json:"username"`
	Email        string `json:"email"`
	PasswordHash string `json:"password_hash"`
	IsAdmin      bool   `json:"is_admin"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Username,
		arg.Email,
		arg.PasswordHash,
		arg.IsAdmin,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.IsAdmin,
		&i.Settings,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FavoritesThreshold,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteUser, id)
	return err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, username, email, password_hash, is_admin, settings, created_at, updated_at, favorites_threshold FROM users WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.IsAdmin,
		&i.Settings,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FavoritesThreshold,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, username, email, password_hash, is_admin, settings, created_at, updated_at, favorites_threshold FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.IsAdmin,
		&i.Settings,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FavoritesThreshold,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, username, email, password_hash, is_admin, settings, created_at, updated_at, favorites_threshold FROM users WHERE username = $1
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.IsAdmin,
		&i.Settings,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FavoritesThreshold,
	)
	return i, err
}

const getUserSettings = `-- name: GetUserSettings :one
SELECT settings FROM users WHERE id = $1
`

func (q *Queries) GetUserSettings(ctx context.Context, id int64) ([]byte, error) {
	row := q.db.QueryRow(ctx, getUserSettings, id)
	var settings []byte
	err := row.Scan(&settings)
	return settings, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, username, email, password_hash, is_admin, settings, created_at, updated_at, favorites_threshold FROM users ORDER BY created_at ASC
`

func (q *Queries) ListUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Email,
			&i.PasswordHash,
			&i.IsAdmin,
			&i.Settings,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.FavoritesThreshold,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET username = $2, email = $3, is_admin = $4, updated_at = now()
WHERE id = $1
RETURNING id, username, email, password_hash, is_admin, settings, created_at, updated_at, favorites_threshold
`

type UpdateUserParams struct {
	ID       int64  `json:"id"`
	Username string `json:"username"`
	Email    string `json:"email"`
	IsAdmin  bool   `json:"is_admin"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.ID,
		arg.Username,
		arg.Email,
		arg.IsAdmin,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.IsAdmin,
		&i.Settings,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FavoritesThreshold,
	)
	return i, err
}

const updateUserPassword = `-- name: UpdateUserPassword :exec
UPDATE users SET password_hash = $2, updated_at = now() WHERE id = $1
`

type UpdateUserPasswordParams struct {
	ID           int64  `json:"id"`
	PasswordHash string `json:"password_hash"`
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error {
	_, err := q.db.Exec(ctx, updateUserPassword, arg.ID, arg.PasswordHash)
	return err
}

const updateUserPasswordAndDeleteOtherSessions = `-- name: UpdateUserPasswordAndDeleteOtherSessions :exec
WITH updated AS (
    UPDATE users SET password_hash = $2, updated_at = now() WHERE users.id = $1
    RETURNING users.id
)
DELETE FROM sessions
USING updated
WHERE sessions.user_id = updated.id
  AND sessions.token_hash <> $3
`

type UpdateUserPasswordAndDeleteOtherSessionsParams struct {
	ID           int64  `json:"id"`
	PasswordHash string `json:"password_hash"`
	TokenHash    string `json:"token_hash"`
}

// A self-service password change keeps only the credential that authorised
// the change. Other browser/Jellyfin sessions and API tokens are invalidated
// atomically with the password update.
func (q *Queries) UpdateUserPasswordAndDeleteOtherSessions(ctx context.Context, arg UpdateUserPasswordAndDeleteOtherSessionsParams) error {
	_, err := q.db.Exec(ctx, updateUserPasswordAndDeleteOtherSessions, arg.ID, arg.PasswordHash, arg.TokenHash)
	return err
}

const updateUserPasswordAndDeleteSessions = `-- name: UpdateUserPasswordAndDeleteSessions :exec
WITH updated AS (
    UPDATE users SET password_hash = $2, updated_at = now() WHERE users.id = $1
    RETURNING users.id
)
DELETE FROM sessions
USING updated
WHERE sessions.user_id = updated.id
`

type UpdateUserPasswordAndDeleteSessionsParams struct {
	ID           int64  `json:"id"`
	PasswordHash string `json:"password_hash"`
}

// Admin/CLI resets cannot prove possession of any user session, so revoke all
// sessions and API tokens atomically with the password update.
func (q *Queries) UpdateUserPasswordAndDeleteSessions(ctx context.Context, arg UpdateUserPasswordAndDeleteSessionsParams) error {
	_, err := q.db.Exec(ctx, updateUserPasswordAndDeleteSessions, arg.ID, arg.PasswordHash)
	return err
}

const updateUserSettings = `-- name: UpdateUserSettings :exec
UPDATE users SET settings = $1, updated_at = now() WHERE id = $2
`

type UpdateUserSettingsParams struct {
	Settings []byte `json:"settings"`
	ID       int64  `json:"id"`
}

func (q *Queries) UpdateUserSettings(ctx context.Context, arg UpdateUserSettingsParams) error {
	_, err := q.db.Exec(ctx, updateUserSettings, arg.Settings, arg.ID)
	return err
}
