// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: watch_progress.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getNextUnwatchedEpisode = `-- name: GetNextUnwatchedEpisode :one
SELECT e.id AS episode_id, e.episode_number, e.title, e.runtime_minutes,
       s.id AS season_id, s.season_number,
       ts.media_item_id
FROM tv_episodes e
JOIN tv_seasons s ON s.id = e.season_id
JOIN tv_series ts ON ts.id = s.series_id
LEFT JOIN user_watch_progress wp ON wp.entity_id = e.id AND wp.entity_type = 'episode' AND wp.completed = true AND wp.user_id = $1
WHERE ts.media_item_id = $2 AND wp.entity_id IS NULL
ORDER BY (CASE WHEN s.season_number = 0 THEN 1 ELSE 0 END), s.season_number ASC, e.episode_number ASC
LIMIT 1
`

type GetNextUnwatchedEpisodeParams struct {
	UserID      int64 `json:"user_id"`
	MediaItemID int64 `json:"media_item_id"`
}

type GetNextUnwatchedEpisodeRow struct {
	EpisodeID      int64  `json:"episode_id"`
	EpisodeNumber  int32  `json:"episode_number"`
	Title          string `json:"title"`
	RuntimeMinutes int32  `json:"runtime_minutes"`
	SeasonID       int64  `json:"season_id"`
	SeasonNumber   int32  `json:"season_number"`
	MediaItemID    int64  `json:"media_item_id"`
}

// Next unwatched episode for a series (ordered by season then episode number)
func (q *Queries) GetNextUnwatchedEpisode(ctx context.Context, arg GetNextUnwatchedEpisodeParams) (GetNextUnwatchedEpisodeRow, error) {
	row := q.db.QueryRow(ctx, getNextUnwatchedEpisode, arg.UserID, arg.MediaItemID)
	var i GetNextUnwatchedEpisodeRow
	err := row.Scan(
		&i.EpisodeID,
		&i.EpisodeNumber,
		&i.Title,
		&i.RuntimeMinutes,
		&i.SeasonID,
		&i.SeasonNumber,
		&i.MediaItemID,
	)
	return i, err
}

const getWatchProgress = `-- name: GetWatchProgress :one
SELECT id, user_id, entity_type, entity_id, progress_seconds, total_seconds, completed, updated_at FROM user_watch_progress
WHERE user_id = $1 AND entity_type = $2 AND entity_id = $3
`

type GetWatchProgressParams struct {
	UserID     int64  `json:"user_id"`
	EntityType string `json:"entity_type"`
	EntityID   int64  `json:"entity_id"`
}

func (q *Queries) GetWatchProgress(ctx context.Context, arg GetWatchProgressParams) (UserWatchProgress, error) {
	row := q.db.QueryRow(ctx, getWatchProgress, arg.UserID, arg.EntityType, arg.EntityID)
	var i UserWatchProgress
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.EntityType,
		&i.EntityID,
		&i.ProgressSeconds,
		&i.TotalSeconds,
		&i.Completed,
		&i.UpdatedAt,
	)
	return i, err
}

const isEpisodeWatched = `-- name: IsEpisodeWatched :one
SELECT EXISTS(
  SELECT 1 FROM user_watch_progress WHERE user_id = $1 AND entity_type = 'episode' AND entity_id = $2 AND completed = true
) AS watched
`

type IsEpisodeWatchedParams struct {
	UserID   int64 `json:"user_id"`
	EntityID int64 `json:"entity_id"`
}

func (q *Queries) IsEpisodeWatched(ctx context.Context, arg IsEpisodeWatchedParams) (bool, error) {
	row := q.db.QueryRow(ctx, isEpisodeWatched, arg.UserID, arg.EntityID)
	var watched bool
	err := row.Scan(&watched)
	return watched, err
}

const listContinueWatching = `-- name: ListContinueWatching :many
SELECT wp.id, wp.entity_type, wp.entity_id, wp.progress_seconds, wp.total_seconds, wp.updated_at,
       COALESCE(mi.id, ep_mi.id) AS media_item_id,
       COALESCE(mi.public_id, ep_mi.public_id) AS media_item_public_id,
       COALESCE(mi.library_id, ep_mi.library_id) AS library_id,
       COALESCE(mi.title, ep_mi.title) AS title,
       COALESCE(mi.poster_path, ep_mi.poster_path) AS poster_path,
       COALESCE(mi.slug, ep_mi.slug) AS slug,
       COALESCE(mi.media_type, ep_mi.media_type)::text AS media_type,
       ep.episode_number,
       ep.title AS episode_title,
       s.season_number
FROM user_watch_progress wp
LEFT JOIN media_item_cards mi ON wp.entity_type = 'movie' AND mi.id = wp.entity_id
LEFT JOIN tv_episodes ep ON wp.entity_type = 'episode' AND ep.id = wp.entity_id
LEFT JOIN tv_seasons s ON ep.season_id = s.id
LEFT JOIN tv_series ts ON s.series_id = ts.id
LEFT JOIN media_item_cards ep_mi ON ts.media_item_id = ep_mi.id
WHERE wp.user_id = $1 AND wp.completed = false AND wp.progress_seconds > 30
  -- Skip items whose file is missing on disk. For a movie that's any live
  -- file on the media item; for an episode it must be the specific file
  -- matching this season+episode (a sibling episode surviving doesn't make
  -- THIS one playable), mirroring BuildEpisodeFileMap's parse_result match.
  AND (
    (wp.entity_type = 'movie' AND EXISTS (
      SELECT 1 FROM library_files lf
      WHERE lf.media_item_id = mi.id AND lf.deleted_at IS NULL
    ))
    OR (wp.entity_type = 'episode' AND EXISTS (
      SELECT 1 FROM library_files lf
      WHERE lf.media_item_id = ep_mi.id AND lf.deleted_at IS NULL AND lf.status = 'matched'
        AND lf.parse_result->'parsed'->'release'->'seasons'  @> to_jsonb(s.season_number)
        AND lf.parse_result->'parsed'->'release'->'episodes' @> to_jsonb(ep.episode_number)
    ))
  )
ORDER BY wp.updated_at DESC
LIMIT 20
`

type ListContinueWatchingRow struct {
	ID                int64              `json:"id"`
	EntityType        string             `json:"entity_type"`
	EntityID          int64              `json:"entity_id"`
	ProgressSeconds   int32              `json:"progress_seconds"`
	TotalSeconds      int32              `json:"total_seconds"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	MediaItemID       int64              `json:"media_item_id"`
	MediaItemPublicID uuid.UUID          `json:"media_item_public_id"`
	LibraryID         int64              `json:"library_id"`
	Title             string             `json:"title"`
	PosterPath        string             `json:"poster_path"`
	Slug              string             `json:"slug"`
	MediaType         string             `json:"media_type"`
	EpisodeNumber     pgtype.Int4        `json:"episode_number"`
	EpisodeTitle      pgtype.Text        `json:"episode_title"`
	SeasonNumber      pgtype.Int4        `json:"season_number"`
}

// Continue watching: incomplete progress across movies and episodes
func (q *Queries) ListContinueWatching(ctx context.Context, userID int64) ([]ListContinueWatchingRow, error) {
	rows, err := q.db.Query(ctx, listContinueWatching, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListContinueWatchingRow{}
	for rows.Next() {
		var i ListContinueWatchingRow
		if err := rows.Scan(
			&i.ID,
			&i.EntityType,
			&i.EntityID,
			&i.ProgressSeconds,
			&i.TotalSeconds,
			&i.UpdatedAt,
			&i.MediaItemID,
			&i.MediaItemPublicID,
			&i.LibraryID,
			&i.Title,
			&i.PosterPath,
			&i.Slug,
			&i.MediaType,
			&i.EpisodeNumber,
			&i.EpisodeTitle,
			&i.SeasonNumber,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEpisodeProgressForSeries = `-- name: ListEpisodeProgressForSeries :many
SELECT wp.entity_id AS episode_id, wp.progress_seconds, wp.total_seconds, wp.completed
FROM user_watch_progress wp
JOIN tv_episodes e ON e.id = wp.entity_id
JOIN tv_seasons s ON s.id = e.season_id
WHERE wp.user_id = $1 AND wp.entity_type = 'episode' AND s.series_id = $2
`

type ListEpisodeProgressForSeriesParams struct {
	UserID   int64 `json:"user_id"`
	SeriesID int64 `json:"series_id"`
}

type ListEpisodeProgressForSeriesRow struct {
	EpisodeID       int64 `json:"episode_id"`
	ProgressSeconds int32 `json:"progress_seconds"`
	TotalSeconds    int32 `json:"total_seconds"`
	Completed       bool  `json:"completed"`
}

// Episode progress for a specific series (for showing progress bars on episode cards)
func (q *Queries) ListEpisodeProgressForSeries(ctx context.Context, arg ListEpisodeProgressForSeriesParams) ([]ListEpisodeProgressForSeriesRow, error) {
	rows, err := q.db.Query(ctx, listEpisodeProgressForSeries, arg.UserID, arg.SeriesID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEpisodeProgressForSeriesRow{}
	for rows.Next() {
		var i ListEpisodeProgressForSeriesRow
		if err := rows.Scan(
			&i.EpisodeID,
			&i.ProgressSeconds,
			&i.TotalSeconds,
			&i.Completed,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFavoritedMediaItemIDs = `-- name: ListFavoritedMediaItemIDs :many
SELECT entity_id FROM user_favorites
WHERE user_id = $1 AND entity_type = 'media_item'
`

func (q *Queries) ListFavoritedMediaItemIDs(ctx context.Context, userID int64) ([]int64, error) {
	rows, err := q.db.Query(ctx, listFavoritedMediaItemIDs, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var entity_id int64
		if err := rows.Scan(&entity_id); err != nil {
			return nil, err
		}
		items = append(items, entity_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentlyWatched = `-- name: ListRecentlyWatched :many
SELECT DISTINCT ON (COALESCE(mi.id, ep_mi.id))
       wp.id, wp.entity_type, wp.entity_id, wp.updated_at,
       COALESCE(mi.id, ep_mi.id) AS media_item_id,
       COALESCE(mi.public_id, ep_mi.public_id) AS media_item_public_id,
       COALESCE(mi.library_id, ep_mi.library_id) AS library_id,
       COALESCE(mi.title, ep_mi.title) AS title,
       COALESCE(mi.poster_path, ep_mi.poster_path) AS poster_path,
       COALESCE(mi.slug, ep_mi.slug) AS slug,
       COALESCE(mi.media_type, ep_mi.media_type)::text AS media_type
FROM user_watch_progress wp
LEFT JOIN media_item_cards mi ON wp.entity_type = 'movie' AND mi.id = wp.entity_id
LEFT JOIN tv_episodes ep ON wp.entity_type = 'episode' AND ep.id = wp.entity_id
LEFT JOIN tv_seasons s ON ep.season_id = s.id
LEFT JOIN tv_series ts ON s.series_id = ts.id
LEFT JOIN media_item_cards ep_mi ON ts.media_item_id = ep_mi.id
WHERE wp.user_id = $1 AND wp.completed = true
ORDER BY COALESCE(mi.id, ep_mi.id), wp.updated_at DESC
LIMIT 20
`

type ListRecentlyWatchedRow struct {
	ID                int64              `json:"id"`
	EntityType        string             `json:"entity_type"`
	EntityID          int64              `json:"entity_id"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	MediaItemID       int64              `json:"media_item_id"`
	MediaItemPublicID uuid.UUID          `json:"media_item_public_id"`
	LibraryID         int64              `json:"library_id"`
	Title             string             `json:"title"`
	PosterPath        string             `json:"poster_path"`
	Slug              string             `json:"slug"`
	MediaType         string             `json:"media_type"`
}

// Recently watched (completed items)
func (q *Queries) ListRecentlyWatched(ctx context.Context, userID int64) ([]ListRecentlyWatchedRow, error) {
	rows, err := q.db.Query(ctx, listRecentlyWatched, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRecentlyWatchedRow{}
	for rows.Next() {
		var i ListRecentlyWatchedRow
		if err := rows.Scan(
			&i.ID,
			&i.EntityType,
			&i.EntityID,
			&i.UpdatedAt,
			&i.MediaItemID,
			&i.MediaItemPublicID,
			&i.LibraryID,
			&i.Title,
			&i.PosterPath,
			&i.Slug,
			&i.MediaType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentlyWatchedEpisodes = `-- name: ListRecentlyWatchedEpisodes :many
SELECT wp.entity_id AS episode_id, wp.updated_at,
       ts.media_item_id,
       ep_mi.public_id AS media_item_public_id,
       ep_mi.library_id,
       ep_mi.title AS series_title,
       ep_mi.slug AS series_slug,
       s.season_number,
       ep.episode_number,
       ep.title AS episode_title
FROM user_watch_progress wp
JOIN tv_episodes ep ON ep.id = wp.entity_id
JOIN tv_seasons s ON s.id = ep.season_id
JOIN tv_series ts ON ts.id = s.series_id
JOIN media_item_cards ep_mi ON ep_mi.id = ts.media_item_id
WHERE wp.user_id = $1 AND wp.entity_type = 'episode' AND wp.completed = true
ORDER BY wp.updated_at DESC
LIMIT 24
`

type ListRecentlyWatchedEpisodesRow struct {
	EpisodeID         int64              `json:"episode_id"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	MediaItemID       int64              `json:"media_item_id"`
	MediaItemPublicID uuid.UUID          `json:"media_item_public_id"`
	LibraryID         int64              `json:"library_id"`
	SeriesTitle       string             `json:"series_title"`
	SeriesSlug        string             `json:"series_slug"`
	SeasonNumber      int32              `json:"season_number"`
	EpisodeNumber     int32              `json:"episode_number"`
	EpisodeTitle      string             `json:"episode_title"`
}

// Recently watched EPISODES (not deduped to the show) — the TV "Recently
// Watched" rail shows one tile per episode, each painted with the show's poster
// (media_item_id) and an "S02E03 · Title" subtitle. Distinct from
// ListRecentlyWatched, which collapses to one row per media item.
func (q *Queries) ListRecentlyWatchedEpisodes(ctx context.Context, userID int64) ([]ListRecentlyWatchedEpisodesRow, error) {
	rows, err := q.db.Query(ctx, listRecentlyWatchedEpisodes, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRecentlyWatchedEpisodesRow{}
	for rows.Next() {
		var i ListRecentlyWatchedEpisodesRow
		if err := rows.Scan(
			&i.EpisodeID,
			&i.UpdatedAt,
			&i.MediaItemID,
			&i.MediaItemPublicID,
			&i.LibraryID,
			&i.SeriesTitle,
			&i.SeriesSlug,
			&i.SeasonNumber,
			&i.EpisodeNumber,
			&i.EpisodeTitle,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWatchedEpisodeNumbersForMediaItems = `-- name: ListWatchedEpisodeNumbersForMediaItems :many
SELECT ts.media_item_id, s.season_number, e.episode_number
FROM user_watch_progress wp
JOIN tv_episodes e ON e.id = wp.entity_id
JOIN tv_seasons s ON s.id = e.season_id
JOIN tv_series ts ON ts.id = s.series_id
WHERE wp.user_id = $1 AND wp.entity_type = 'episode' AND wp.completed = true
  AND ts.media_item_id = ANY($2::bigint[])
`

type ListWatchedEpisodeNumbersForMediaItemsParams struct {
	UserID       int64   `json:"user_id"`
	MediaItemIds []int64 `json:"media_item_ids"`
}

type ListWatchedEpisodeNumbersForMediaItemsRow struct {
	MediaItemID   int64 `json:"media_item_id"`
	SeasonNumber  int32 `json:"season_number"`
	EpisodeNumber int32 `json:"episode_number"`
}

// Season/episode numbers of a user's completed episodes across many series —
// the watched numerator of presentShowWatchCounts. Numbers (not ids) so the
// caller can intersect with the parsed file keys the same way the totals do.
func (q *Queries) ListWatchedEpisodeNumbersForMediaItems(ctx context.Context, arg ListWatchedEpisodeNumbersForMediaItemsParams) ([]ListWatchedEpisodeNumbersForMediaItemsRow, error) {
	rows, err := q.db.Query(ctx, listWatchedEpisodeNumbersForMediaItems, arg.UserID, arg.MediaItemIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListWatchedEpisodeNumbersForMediaItemsRow{}
	for rows.Next() {
		var i ListWatchedEpisodeNumbersForMediaItemsRow
		if err := rows.Scan(&i.MediaItemID, &i.SeasonNumber, &i.EpisodeNumber); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markEpisodeWatched = `-- name: MarkEpisodeWatched :exec
INSERT INTO user_watch_progress (user_id, entity_type, entity_id, completed, updated_at)
VALUES ($1, 'episode', $2, true, now())
ON CONFLICT (user_id, entity_type, entity_id) DO UPDATE SET completed = true, updated_at = now()
`

type MarkEpisodeWatchedParams struct {
	UserID   int64 `json:"user_id"`
	EntityID int64 `json:"entity_id"`
}

func (q *Queries) MarkEpisodeWatched(ctx context.Context, arg MarkEpisodeWatchedParams) error {
	_, err := q.db.Exec(ctx, markEpisodeWatched, arg.UserID, arg.EntityID)
	return err
}

const markEpisodesWatched = `-- name: MarkEpisodesWatched :exec
INSERT INTO user_watch_progress (user_id, entity_type, entity_id, completed, updated_at)
SELECT $1, 'episode', eid, true, now()
FROM unnest($2::bigint[]) AS eid
ON CONFLICT (user_id, entity_type, entity_id) DO UPDATE SET completed = true, updated_at = now()
`

type MarkEpisodesWatchedParams struct {
	UserID  int64   `json:"user_id"`
	Column2 []int64 `json:"column_2"`
}

// Bulk mark a specific set of episodes watched. Season/show bulk-mark resolves
// to only the episodes we actually hold a file for (see presentEpisodeIDs), so
// unaired catalog episodes are never pre-marked — otherwise a later-arriving
// episode would show as already watched.
func (q *Queries) MarkEpisodesWatched(ctx context.Context, arg MarkEpisodesWatchedParams) error {
	_, err := q.db.Exec(ctx, markEpisodesWatched, arg.UserID, arg.Column2)
	return err
}

const markMovieWatched = `-- name: MarkMovieWatched :exec
INSERT INTO user_watch_progress (user_id, entity_type, entity_id, completed, updated_at)
VALUES ($1, 'movie', $2, true, now())
ON CONFLICT (user_id, entity_type, entity_id) DO UPDATE SET completed = true, updated_at = now()
`

type MarkMovieWatchedParams struct {
	UserID   int64 `json:"user_id"`
	EntityID int64 `json:"entity_id"`
}

func (q *Queries) MarkMovieWatched(ctx context.Context, arg MarkMovieWatchedParams) error {
	_, err := q.db.Exec(ctx, markMovieWatched, arg.UserID, arg.EntityID)
	return err
}

const unmarkEpisodeWatched = `-- name: UnmarkEpisodeWatched :exec
DELETE FROM user_watch_progress WHERE user_id = $1 AND entity_type = 'episode' AND entity_id = $2
`

type UnmarkEpisodeWatchedParams struct {
	UserID   int64 `json:"user_id"`
	EntityID int64 `json:"entity_id"`
}

func (q *Queries) UnmarkEpisodeWatched(ctx context.Context, arg UnmarkEpisodeWatchedParams) error {
	_, err := q.db.Exec(ctx, unmarkEpisodeWatched, arg.UserID, arg.EntityID)
	return err
}

const unmarkMovieWatched = `-- name: UnmarkMovieWatched :exec
DELETE FROM user_watch_progress WHERE user_id = $1 AND entity_type = 'movie' AND entity_id = $2
`

type UnmarkMovieWatchedParams struct {
	UserID   int64 `json:"user_id"`
	EntityID int64 `json:"entity_id"`
}

func (q *Queries) UnmarkMovieWatched(ctx context.Context, arg UnmarkMovieWatchedParams) error {
	_, err := q.db.Exec(ctx, unmarkMovieWatched, arg.UserID, arg.EntityID)
	return err
}

const unmarkSeasonWatched = `-- name: UnmarkSeasonWatched :exec
DELETE FROM user_watch_progress
WHERE user_id = $1 AND entity_type = 'episode'
AND entity_id IN (SELECT id FROM tv_episodes WHERE season_id = $2)
`

type UnmarkSeasonWatchedParams struct {
	UserID   int64 `json:"user_id"`
	SeasonID int64 `json:"season_id"`
}

func (q *Queries) UnmarkSeasonWatched(ctx context.Context, arg UnmarkSeasonWatchedParams) error {
	_, err := q.db.Exec(ctx, unmarkSeasonWatched, arg.UserID, arg.SeasonID)
	return err
}

const unmarkShowWatched = `-- name: UnmarkShowWatched :exec
DELETE FROM user_watch_progress
WHERE user_id = $1 AND entity_type = 'episode' AND entity_id IN (
  SELECT e.id FROM tv_episodes e
  JOIN tv_seasons s ON s.id = e.season_id
  JOIN tv_series ts ON ts.id = s.series_id
  WHERE ts.media_item_id = $2
)
`

type UnmarkShowWatchedParams struct {
	UserID      int64 `json:"user_id"`
	MediaItemID int64 `json:"media_item_id"`
}

func (q *Queries) UnmarkShowWatched(ctx context.Context, arg UnmarkShowWatchedParams) error {
	_, err := q.db.Exec(ctx, unmarkShowWatched, arg.UserID, arg.MediaItemID)
	return err
}

const upsertWatchProgress = `-- name: UpsertWatchProgress :one
INSERT INTO user_watch_progress (user_id, entity_type, entity_id, progress_seconds, total_seconds, completed, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, now())
ON CONFLICT (user_id, entity_type, entity_id) DO UPDATE SET
    progress_seconds = EXCLUDED.progress_seconds,
    total_seconds = EXCLUDED.total_seconds,
    completed = EXCLUDED.completed,
    updated_at = now()
RETURNING id, user_id, entity_type, entity_id, progress_seconds, total_seconds, completed, updated_at
`

type UpsertWatchProgressParams struct {
	UserID          int64  `json:"user_id"`
	EntityType      string `json:"entity_type"`
	EntityID        int64  `json:"entity_id"`
	ProgressSeconds int32  `json:"progress_seconds"`
	TotalSeconds    int32  `json:"total_seconds"`
	Completed       bool   `json:"completed"`
}

func (q *Queries) UpsertWatchProgress(ctx context.Context, arg UpsertWatchProgressParams) (UserWatchProgress, error) {
	row := q.db.QueryRow(ctx, upsertWatchProgress,
		arg.UserID,
		arg.EntityType,
		arg.EntityID,
		arg.ProgressSeconds,
		arg.TotalSeconds,
		arg.Completed,
	)
	var i UserWatchProgress
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.EntityType,
		&i.EntityID,
		&i.ProgressSeconds,
		&i.TotalSeconds,
		&i.Completed,
		&i.UpdatedAt,
	)
	return i, err
}
