// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: watch_history.sql

package sqlc

import (
	"context"
)

const createWatchHistory = `-- name: CreateWatchHistory :one
INSERT INTO watch_history (user_id, media_item_id, progress_seconds, total_seconds, completed)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_id, media_item_id, progress_seconds, total_seconds, completed, watched_at
`

type CreateWatchHistoryParams struct {
	UserID          int64 `json:"user_id"`
	MediaItemID     int64 `json:"media_item_id"`
	ProgressSeconds int32 `json:"progress_seconds"`
	TotalSeconds    int32 `json:"total_seconds"`
	Completed       bool  `json:"completed"`
}

func (q *Queries) CreateWatchHistory(ctx context.Context, arg CreateWatchHistoryParams) (WatchHistory, error) {
	row := q.db.QueryRow(ctx, createWatchHistory,
		arg.UserID,
		arg.MediaItemID,
		arg.ProgressSeconds,
		arg.TotalSeconds,
		arg.Completed,
	)
	var i WatchHistory
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.MediaItemID,
		&i.ProgressSeconds,
		&i.TotalSeconds,
		&i.Completed,
		&i.WatchedAt,
	)
	return i, err
}

const getLatestWatchHistory = `-- name: GetLatestWatchHistory :one
SELECT id, user_id, media_item_id, progress_seconds, total_seconds, completed, watched_at FROM watch_history
WHERE user_id = $1 AND media_item_id = $2
ORDER BY watched_at DESC
LIMIT 1
`

type GetLatestWatchHistoryParams struct {
	UserID      int64 `json:"user_id"`
	MediaItemID int64 `json:"media_item_id"`
}

func (q *Queries) GetLatestWatchHistory(ctx context.Context, arg GetLatestWatchHistoryParams) (WatchHistory, error) {
	row := q.db.QueryRow(ctx, getLatestWatchHistory, arg.UserID, arg.MediaItemID)
	var i WatchHistory
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.MediaItemID,
		&i.ProgressSeconds,
		&i.TotalSeconds,
		&i.Completed,
		&i.WatchedAt,
	)
	return i, err
}

const listContinueWatching = `-- name: ListContinueWatching :many
SELECT DISTINCT ON (wh.media_item_id)
    wh.id, wh.user_id, wh.media_item_id, wh.progress_seconds, wh.total_seconds, wh.completed, wh.watched_at
FROM watch_history wh
WHERE wh.user_id = $1 AND wh.completed = false AND wh.progress_seconds > 0
ORDER BY wh.media_item_id, wh.watched_at DESC
`

func (q *Queries) ListContinueWatching(ctx context.Context, userID int64) ([]WatchHistory, error) {
	rows, err := q.db.Query(ctx, listContinueWatching, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WatchHistory{}
	for rows.Next() {
		var i WatchHistory
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.MediaItemID,
			&i.ProgressSeconds,
			&i.TotalSeconds,
			&i.Completed,
			&i.WatchedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWatchHistoryByUser = `-- name: ListWatchHistoryByUser :many
SELECT id, user_id, media_item_id, progress_seconds, total_seconds, completed, watched_at FROM watch_history
WHERE user_id = $1
ORDER BY watched_at DESC
LIMIT $2 OFFSET $3
`

type ListWatchHistoryByUserParams struct {
	UserID int64 `json:"user_id"`
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListWatchHistoryByUser(ctx context.Context, arg ListWatchHistoryByUserParams) ([]WatchHistory, error) {
	rows, err := q.db.Query(ctx, listWatchHistoryByUser, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WatchHistory{}
	for rows.Next() {
		var i WatchHistory
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.MediaItemID,
			&i.ProgressSeconds,
			&i.TotalSeconds,
			&i.Completed,
			&i.WatchedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateWatchProgress = `-- name: UpdateWatchProgress :one
UPDATE watch_history
SET progress_seconds = $2, total_seconds = $3, completed = $4, watched_at = now()
WHERE id = $1
RETURNING id, user_id, media_item_id, progress_seconds, total_seconds, completed, watched_at
`

type UpdateWatchProgressParams struct {
	ID              int64 `json:"id"`
	ProgressSeconds int32 `json:"progress_seconds"`
	TotalSeconds    int32 `json:"total_seconds"`
	Completed       bool  `json:"completed"`
}

func (q *Queries) UpdateWatchProgress(ctx context.Context, arg UpdateWatchProgressParams) (WatchHistory, error) {
	row := q.db.QueryRow(ctx, updateWatchProgress,
		arg.ID,
		arg.ProgressSeconds,
		arg.TotalSeconds,
		arg.Completed,
	)
	var i WatchHistory
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.MediaItemID,
		&i.ProgressSeconds,
		&i.TotalSeconds,
		&i.Completed,
		&i.WatchedAt,
	)
	return i, err
}
