export default defineNuxtConfig({
  ssr: false,
  compatibilityDate: '2025-05-19',
  devtools: { enabled: true },

  modules: ['@nuxtjs/tailwindcss', 'nuxt-open-fetch', 'nuxt-phosphor-icons', '@vueuse/nuxt', '@nuxt/image'],

  image: {
    providers: {
      heya: {
        name: 'heya',
        provider: '~/providers/heya.ts',
      },
    },
    provider: 'heya',
  },

  // Typed OpenAPI client. The schema is regenerated by `make gen-api-client`
  // (lefthook + CI gate prevent drift). The module generates `useHeya` (real
  // useFetch wrapper) and `$heya` ($fetch wrapper); auth is wired through
  // openFetch hooks in plugins/heyaApi.client.ts.
  openFetch: {
    clients: {
      heya: {
        baseURL: '',
        schema: './shared/api.openapi.json',
      },
    },
  },

  components: [
    { path: '~/components', pathPrefix: false },
  ],

  // Vite ships `server.allowedHosts` defaulting to localhost-only, which
  // rejects any request with an external Host header — Tailscale MagicDNS
  // names, Funnel URLs, the laptop's LAN IP when probing from another
  // device. Caddy forwards the original Host header through, so Vite at
  // :3000 sees e.g. `mybox.tailnet.ts.net` and 403s with the "not allowed"
  // message. We allow the whole `.ts.net` suffix so any tailnet device can
  // hit the dev server without per-machine config; localhost stays implicit.
  // Dev-only — embedded SPA in prod never touches Vite.
  vite: {
    server: {
      allowedHosts: ['.ts.net'],
    },
  },

  css: [
    '@fontsource/inter/400.css',
    '@fontsource/inter/500.css',
    '@fontsource/inter/600.css',
    '@fontsource/inter/700.css',
    '@fontsource/jetbrains-mono/400.css',
    '@fontsource/jetbrains-mono/500.css',
    '@fontsource/jetbrains-mono/600.css',
    '@fontsource/jetbrains-mono/700.css',
    '~/assets/css/heya.css',
    '~/assets/css/main.css',
    '~/assets/css/surface.css',
  ],

  runtimeConfig: {
    public: {
      apiBase: '/api',
    },
  },

  app: {
    head: {
      title: 'Heya',
      meta: [
        { charset: 'utf-8' },
        { name: 'viewport', content: 'width=device-width, initial-scale=1, viewport-fit=cover' },
        { name: 'theme-color', content: '#0a0a12' },
      ],
      link: [
        { rel: 'icon', type: 'image/svg+xml', href: '/favicon.svg' },
      ],
      // Inline style so the document is dark from byte 0 — before any CSS file
      // loads and before the spa-loading-template renders. Kills the white
      // browser-default flash on cold loads / slow connections.
      style: [
        { innerHTML: 'html,body{background:#0a0a12;margin:0;color-scheme:dark}' },
      ],
    },
  },

})
